# Generated by Django 4.0.2 on 2022-03-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0027_report_generator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_case', to='cases.case')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
