# Generated by Django 4.0.3 on 2022-04-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_populate_report_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_version',
            field=models.TextField(blank=True, default='spreadsheet'),
        ),
        migrations.AlterField(
            model_name='publishedreport',
            name='version',
            field=models.IntegerField(),
        ),
    ]
