# Generated by Django 4.0.3 on 2022-04-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_report_version_alter_publishedreport_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_version',
            field=models.TextField(default='spreadsheet'),
        ),
    ]
