# Generated by Django 4.0.2 on 2022-03-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_editable_cells"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablerow",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
