# Generated by Django 4.0.3 on 2022-04-19 14:27

from django.db import migrations, models

from ..models import REPORT_VERSION_DEFAULT


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_remove_report_ready_for_qa"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_version",
            field=models.TextField(default=REPORT_VERSION_DEFAULT),
        ),
    ]
