# Generated by Django 5.1.3 on 2024-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_report_report_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_version",
            field=models.TextField(default="v1_5_0__20241125"),
        ),
    ]
