# Generated by Django 4.0.3 on 2022-04-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_report_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_version',
            field=models.TextField(default='v1_20220406'),
        ),
    ]
