# Generated by Django 4.0.3 on 2022-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_report_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedreport',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
