# Generated by Django 5.1.4 on 2025-01-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_alter_report_report_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_version",
            field=models.TextField(default="v1_6_0__20250122"),
        ),
    ]
