# Generated by Django 5.1.8 on 2025-04-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_alter_report_report_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_version",
            field=models.TextField(default="v1_7_0__20250416"),
        ),
    ]
