# Generated by Django 4.0.2 on 2022-04-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_report_wrapper_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublishedReport",
        ),
    ]
