# Generated by Django 5.1.8 on 2025-04-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_alter_report_report_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_version",
            field=models.TextField(default="v1_8_0__20250424"),
        ),
    ]
