# Generated by Django 5.2.1 on 2025-06-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_basecase"),
        ("reports", "0008_alter_report_report_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="base_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_basecase",
                to="cases.basecase",
            ),
        ),
        migrations.AddField(
            model_name="reportvisitsmetrics",
            name="base_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cases.basecase",
            ),
        ),
    ]
