# Generated by Django 5.2.1 on 2025-06-04 13:42

from django.db import migrations


def populate_base_case(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")
    Report = apps.get_model("reports", "Report")
    ReportVisitsMetrics = apps.get_model("reports", "ReportVisitsMetrics")
    for count, simplified_case in enumerate(
        SimplifiedCase.objects.all().order_by("id"), start=1
    ):
        print(
            f"{count}: Migrating Reports and ReportVisitsMetrics Case number {simplified_case.case_number}"
        )
        for report in Report.objects.filter(case_id=simplified_case.case_id):
            report.base_case_id = simplified_case.basecase_ptr
            report.save()
        for report_visits_metric in ReportVisitsMetrics.objects.filter(
            case_id=simplified_case.case_id
        ):
            report_visits_metric.base_case_id = simplified_case.basecase_ptr
            report_visits_metric.save()

    ReportWrapper = apps.get_model("reports", "ReportWrapper")
    report_wrapper = ReportWrapper.objects.all().first()
    if report_wrapper is not None:
        report_wrapper.title = """Accessibility report for {% if report.base_case.website_name %}{{ report.base_case.website_name }}{% else %}{{ report.base_case.domain }}{% endif %}"""
        report_wrapper.save()


def reverse_code(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    Report.objects.all().update(base_case_id=None)
    ReportVisitsMetrics = apps.get_model("reports", "ReportVisitsMetrics")
    ReportVisitsMetrics.objects.all().update(base_case_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_report_base_case_reportvisitsmetrics_base_case"),
        ("simplified", "0003_populate_simplified_cases"),
    ]

    operations = [
        migrations.RunPython(populate_base_case, reverse_code=reverse_code),
    ]
