# Generated by Django 5.2.3 on 2025-07-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_populate_base_case"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="case",
        ),
        migrations.RemoveField(
            model_name="reportvisitsmetrics",
            name="case",
        ),
    ]
