# Generated by Django 4.1b1 on 2022-07-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_reset_base_template_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_last_generated_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
