# Generated by Django 6.1.1 on 2026-09-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0011_remove_report_case_remove_reportvisitsmetrics_case"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_version",
            field=models.TextField(default="v1_9_0__20250917"),
        ),
    ]
