# Generated by Django 4.1 on 2022-09-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0013_reportfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_rebuilt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
