# Generated by Django 4.1.1 on 2022-09-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0014_report_report_rebuilt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportvisitsmetrics",
            name="fingerprint_hash",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
