# Generated by Django 4.1.1 on 2022-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0015_alter_reportvisitsmetrics_fingerprint_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetemplate",
            name="new_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="section",
            name="new_page",
            field=models.BooleanField(default=True),
        ),
    ]
