# Generated by Django 4.1.1 on 2022-10-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0042_alter_case_report_methodology_and_more"),
        ("reports", "0016_basetemplate_new_page_section_new_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="report",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_case",
                to="cases.case",
            ),
        ),
    ]
