# Generated by Django 4.1.4 on 2023-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0017_remove_report_is_deleted_alter_report_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
