# Generated by Django 4.1.7 on 2023-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0018_report_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablerow",
            name="section",
        ),
        migrations.AddField(
            model_name="basetemplate",
            name="editable_url_label",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="basetemplate",
            name="editable_url_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="TableRow",
        ),
    ]
