# Generated by Django 4.1.7 on 2023-04-05 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0018_report_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablerow",
            name="section",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="TableRow",
        ),
    ]
