# Generated by Django 4.1.7 on 2023-04-05 14:14

from django.db import migrations


def populate_editable_url_names(apps, schema_editor):  # pylint: disable=unused-argument
    """Populate editable_url_names in base templates"""
    # pylint: disable=invalid-name
    BaseTemplate = apps.get_model("reports", "BaseTemplate")
    try:
        website_base_template = BaseTemplate.objects.get(
            name="How accessible the website is"
        )
        website_base_template.editable_url_name = "audits:edit-website-decision"
        website_base_template.editable_url_label = (
            "Edit test > Website compliance decision"
        )
        website_base_template.save()
        pages_base_template = BaseTemplate.objects.get(name="Pages we checked")
        pages_base_template.editable_url_name = "audits:edit-audit-pages"
        pages_base_template.editable_url_label = "Edit test > Pages"
        pages_base_template.save()
        statement_base_template = BaseTemplate.objects.get(
            name="Your accessibility statement"
        )
        statement_base_template.editable_url_name = "audits:edit-statement-decision"
        statement_base_template.editable_url_label = (
            "Edit test > Accessibility statement compliance decision"
        )
        statement_base_template.save()
        what_next_base_template = BaseTemplate.objects.get(name="What to do next")
        what_next_base_template.editable_url_name = "audits:edit-audit-report-options"
        what_next_base_template.editable_url_label = "Edit test > Report options"
        what_next_base_template.save()
    except BaseTemplate.DoesNotExist:
        pass


def remove_editable_url_names(apps, schema_editor):  # pylint: disable=unused-argument
    """Delete all case events"""
    # pylint: disable=invalid-name
    BaseTemplate = apps.get_model("reports", "BaseTemplate")
    for base_template in BaseTemplate.objects.all():
        base_template.editable_url_name = ""
        base_template.save()


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0019_remove_tablerow_section_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_editable_url_names, reverse_code=remove_editable_url_names
        )
    ]
