# Generated by Django 4.1.7 on 2023-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0023_update_report_template_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_version",
            field=models.TextField(default="v1_2_0__20230523"),
        ),
    ]
