# Generated by Django 4.2.4 on 2023-09-28 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0024_alter_report_report_version"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportFeedback",
        ),
    ]
