# Generated by Django 4.1.4 on 2022-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("200", "Valid"),
                            ("error", "Error"),
                            ("webdriver", "Webdriver error"),
                            ("other", "Other"),
                        ],
                        default="200",
                        max_length=10,
                    ),
                ),
                ("response_status_code", models.IntegerField(default=0)),
                ("response_headers", models.TextField(blank=True, default="")),
                ("response_content", models.TextField(blank=True, default="")),
                ("critical", models.IntegerField(default=0)),
                ("serious", models.IntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("violations", models.TextField(blank=True, default="")),
                ("results", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
