# Generated by Django 4.1.4 on 2022-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="final_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
