# Generated by Django 4.1.4 on 2022-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="axe_core_critical_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="website",
            name="axe_core_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="website",
            name="axe_core_results",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="website",
            name="axe_core_serious_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="website",
            name="axe_core_violations",
            field=models.TextField(blank=True, default=""),
        ),
    ]
