# Generated by Django 3.2 on 2021-04-11 14:06

from django.db import migrations, models
from accessibility_monitoring_platform.settings.base import UNDER_TEST


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AxeRule",
            fields=[
                ("rule_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("description", models.TextField(null=True)),
                ("impact", models.TextField(null=True)),
                ("selector", models.TextField(null=True)),
                ("tags", models.TextField(null=True)),
                ("help", models.TextField(null=True)),
            ],
            options={
                "db_table": "axe_rule",
                "managed": UNDER_TEST,
            },
        ),
        migrations.CreateModel(
            name="AxeWcag",
            fields=[
                ("axe_rule_id", models.IntegerField(primary_key=True, serialize=False)),
                ("wcag_criterion_number", models.CharField(max_length=9)),
            ],
            options={
                "db_table": "axe_wcag",
                "managed": UNDER_TEST,
            },
        ),
        migrations.CreateModel(
            name="TestresultAxeData",
            fields=[
                (
                    "test_data_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("test_id", models.IntegerField()),
                ("rule_name", models.TextField()),
                ("test_status", models.TextField()),
                ("nodes", models.TextField(null=True)),
            ],
            options={
                "db_table": "testresult_axe_data",
                "managed": UNDER_TEST,
            },
        ),
        migrations.CreateModel(
            name="TestresultAxeHeader",
            fields=[
                ("test_id", models.IntegerField(primary_key=True, serialize=False)),
                ("test_timestamp", models.DateTimeField(blank=True, null=True)),
                ("url", models.TextField(null=True)),
                ("domain_name", models.TextField(null=True)),
                ("axe_version", models.TextField(null=True)),
                ("test_environment", models.TextField(null=True)),
                ("time_taken", models.FloatField(null=True)),
                ("test_succeeded", models.BooleanField(null=True)),
                ("further_info", models.TextField(null=True)),
            ],
            options={
                "db_table": "testresult_axe_header",
                "ordering": ["domain_name", "test_timestamp", "test_id"],
                "managed": UNDER_TEST,
            },
        ),
        migrations.CreateModel(
            name="WcagCriteria",
            fields=[
                (
                    "criterion_number",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(null=True)),
                ("wcag_version", models.CharField(max_length=4, null=True)),
                ("wcag_level", models.CharField(max_length=4, null=True)),
            ],
            options={
                "db_table": "wcag_criteria",
                "managed": UNDER_TEST,
            },
        ),
        migrations.CreateModel(
            name="WcagRecommendation",
            fields=[
                (
                    "recommendation_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("criterion_number", models.CharField(max_length=9)),
                ("recommendation", models.TextField(null=True)),
            ],
            options={
                "db_table": "wcag_recommendation",
                "managed": UNDER_TEST,
            },
        ),
    ]
