# Generated by Django 4.2.8 on 2024-01-05 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("reminders", "0001_initial"),
        ("reminders", "0002_auto_20220127_1444"),
        ("reminders", "0003_remove_reminder_user"),
        ("reminders", "0004_reminder_updated"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0022_auto_20220127_1444"),
        ("cases", "0017_remove_case_service_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("description", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminder_case",
                        to="cases.case",
                    ),
                ),
                ("updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
