# Generated by Django 5.0.6 on 2024-07-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reminder",
        ),
    ]
