# Generated by Django 4.1.4 on 2023-02-28 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reminders", "0002_auto_20220127_1444"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reminder",
            name="user",
        ),
    ]
