services:
  db:
    image: postgres:14.13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres-data-full-stack:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
      build:
          dockerfile: ./amp_platform.DockerFile
      image: "amp_platform"
      ports:
          - "8001:8001"
      depends_on:
          - db
          - localstack
      environment:
          - ALLOWED_HOSTS='* localhost 0.0.0.0 0.0.0.0:8001 web web:8001' # Only localhost:8001 works for localstack
          - SECRET_KEY='123456789'
          - DEBUG=FALSE
          - INTEGRATION_TEST=FALSE
          - 'DB_SECRET={"dbname":"postgres","username":"admin","password":"secret","host":"db","port":5432}'
          - DB_NAME=bucketname
      healthcheck:
          test: curl --fail http://localhost:8001/healthcheck || exit 1
      stdin_open: true
      tty: true

  report_viewer:
      build:
          dockerfile: ./amp_viewer.DockerFile
      image: "amp_viewer"
      ports:
          - "8002:8001"
      depends_on:
          - db
          - localstack
          - web
      environment:
          - ALLOWED_HOSTS='* localhost 0.0.0.0 0.0.0.0:8001'
          - SECRET_KEY='123456789'
          - DEBUG=FALSE
          - INTEGRATION_TEST=FALSE
          - 'DB_SECRET={"dbname":"postgres","username":"admin","password":"secret","host":"db","port":5432}'
          - DB_NAME=bucketname
  localstack:
    image: localstack/localstack
    hostname: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
      - DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db-data:
  pgadmin-data:
