version: "3.7"
services:
  db:
    image: postgres:11.12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
      build:
          dockerfile: ./custom.Dockerfile
      image: "144664177605.dkr.ecr.eu-west-2.amazonaws.com/amp/a11ymon-app"
      ports:
          - "8001:8001"
      depends_on:
          - db
          - localstack
      environment:
          - ALLOWED_HOSTS='* localhost 0.0.0.0 0.0.0.0:8001 web web:8001'
          - SECRET_KEY='123456789'
          - DEBUG=TRUE
          - INTEGRATION_TEST=TRUE
          - PORT='8001'
          - POSTGRES_NAME=postgres
          - DB="{'username':'admin','password':'secret'}"
          - POSTGRES_HOST=db
          - POSTGRES_PORT=5432
          - APP_PLATFORM=TRUE
      healthcheck:
          test: curl --fail http://localhost:8001/healthcheck || exit 1
      stdin_open: true
      tty: true

  report_viewer:
      image: "144664177605.dkr.ecr.eu-west-2.amazonaws.com/amp/a11ymon-app"
      ports:
          - "8002:8001"
      depends_on:
          - db
          - localstack
          - web
      environment:
          - ALLOWED_HOSTS='* localhost 0.0.0.0 0.0.0.0:8001'
          - SECRET_KEY='123456789'
          - DEBUG=TRUE
          - INTEGRATION_TEST=TRUE
          - PORT='8001'
          - POSTGRES_NAME=postgres
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=secret
          - POSTGRES_HOST=db
          - POSTGRES_PORT=5432
          - APP_PLATFORM=FALSE

  localstack:
    image: localstack/localstack
    hostname: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
      - DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db-data:
  pgadmin-data:
