# Generated by Django 5.2.1 on 2025-06-03 07:55

from django.apps import apps as global_apps
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def populate_contenttypes(apps, schema_editor):
    simplified_app_config = global_apps.get_app_config("simplified")
    create_contenttypes(simplified_app_config)


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("simplified", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_contenttypes, reverse_code=reverse_code),
    ]
