# Generated by Django 5.2.1 on 2025-06-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplified", "0003_populate_simplified_cases"),
    ]

    operations = [
        migrations.RenameField(
            model_name="casecompliance",
            old_name="case",
            new_name="simplified_case",
        ),
        migrations.RenameField(
            model_name="caseevent",
            old_name="case",
            new_name="simplified_case",
        ),
        migrations.RenameField(
            model_name="casestatus",
            old_name="case",
            new_name="simplified_case",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="case",
            new_name="simplified_case",
        ),
        migrations.RenameField(
            model_name="equalitybodycorrespondence",
            old_name="case",
            new_name="simplified_case",
        ),
        migrations.RenameField(
            model_name="simplifiedeventhistory",
            old_name="case",
            new_name="simplified_case",
        ),
        migrations.RenameField(
            model_name="zendeskticket",
            old_name="case",
            new_name="simplified_case",
        ),
    ]
