# Generated by Django 5.2.3 on 2025-07-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simplified", "0004_rename_case_casecompliance_simplified_case_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simplifiedcase",
            name="case",
        ),
    ]
