# Generated by Django 5.2.3 on 2025-07-24 06:54

from django.db import migrations


def cleanup_previous_case_urls(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")

    for simplified_case in SimplifiedCase.objects.exclude(previous_case_url=""):
        old_previous_case_url: str = simplified_case.previous_case_url
        new_previous_case_url: str = old_previous_case_url.replace(
            "/cases/", "/simplified/"
        )
        simplified_case.archive = simplified_case.archive.replace(
            old_previous_case_url, new_previous_case_url
        )
        simplified_case.previous_case_url = new_previous_case_url
        simplified_case.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("simplified", "0007_alter_casestatus_status"),
    ]

    operations = [
        migrations.RunPython(cleanup_previous_case_urls, reverse_code=reverse_code),
    ]
