# Generated by Django 5.2.9 on 2025-12-22 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplified", "0009_alter_casestatus_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimplifiedCaseHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("note", "Entered note"),
                            ("status", "Changed status"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("id_within_case", models.IntegerField(blank=True, default=0)),
                (
                    "simplified_case_status",
                    models.CharField(
                        choices=[
                            ("000-unassigned-case", "Unassigned case"),
                            ("050-test-in-progress", "Test in progress"),
                            ("060-report-in-progress", "Report in progress"),
                            ("070-unassigned-qa-case", "Report ready to QA"),
                            ("080-qa-in-progress", "QA in progress"),
                            ("090-report-ready-to-send", "Report ready to send"),
                            ("100-in-report-correspondence", "Report sent"),
                            ("120-in-12-week-period", "Waiting for 12-week deadline"),
                            (
                                "140-after-12-week-correspondence",
                                "After 12-week correspondence",
                            ),
                            ("150-reviewing-changes", "Reviewing changes"),
                            ("160-final-decision-due", "Final decision due"),
                            (
                                "170-case-closed-waiting-to-be-sent",
                                "Waiting to be sent to equalities body",
                            ),
                            (
                                "180-case-closed-sent-to-equalities-body",
                                "Sent to equalities body",
                            ),
                            (
                                "190-in-correspondence-with-equalities-body",
                                "In correspondence with equalities body",
                            ),
                            ("200-complete", "Complete"),
                            ("900-deactivated", "Deactivated"),
                            ("910-unknown", "Unknown"),
                        ],
                        default="000-unassigned-case",
                        max_length=200,
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "simplified_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simplified.simplifiedcase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Simplified Case history",
                "ordering": ["-created"],
            },
        ),
    ]
