# Generated by Django 5.2.9 on 2025-12-22 13:21

from datetime import datetime, timezone
from unittest.mock import Mock, patch

from django.db import migrations

DEFAULT_CREATED_BY_USER_ID: int = 2
CASE_NOTE_TIME_AUDIT_METADATA: datetime = datetime(1970, 1, 1, tzinfo=timezone.utc)
CASE_NOTE_TIME_INITIAL_WEBSITE: datetime = datetime(1970, 1, 2, tzinfo=timezone.utc)
CASE_NOTE_TIME_INITIAL_STATEMENT: datetime = datetime(1970, 1, 3, tzinfo=timezone.utc)
CASE_NOTE_TIME_CORRESPONDENCE: datetime = datetime(1970, 1, 4, tzinfo=timezone.utc)
CASE_NOTE_TIME_TWELVE_WEEK_CORRESPONDENCE: datetime = datetime(
    1970, 1, 5, tzinfo=timezone.utc
)
CASE_NOTE_TIME_AUDIT_RETEST_METADATA: datetime = datetime(
    1970, 1, 6, tzinfo=timezone.utc
)
CASE_NOTE_TIME_12_WEEK_WEBSITE: datetime = datetime(1970, 1, 7, tzinfo=timezone.utc)
CASE_NOTE_TIME_12_WEEK_STATEMENT: datetime = datetime(1970, 1, 8, tzinfo=timezone.utc)
CASE_NOTE_TIME_CASE_PROGRESS: datetime = datetime(1970, 1, 9, tzinfo=timezone.utc)
CASE_NOTE_TIME_PSB_APPEAL: datetime = datetime(1970, 1, 10, tzinfo=timezone.utc)
CASE_NOTE_TIME_EQUALITY_BODY: datetime = datetime(1970, 1, 11, tzinfo=timezone.utc)
CASE_NOTE_TIME_NO_PSB_CONTACT: datetime = datetime(1970, 1, 12, tzinfo=timezone.utc)


def populate_case_notes(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")
    CaseCompliance = apps.get_model("simplified", "CaseCompliance")
    Audit = apps.get_model("audits", "Audit")
    SimplifiedCaseHistory = apps.get_model("simplified", "SimplifiedCaseHistory")

    User = apps.get_model("auth", "User")
    user = User.objects.filter(id=DEFAULT_CREATED_BY_USER_ID).first()
    if user is None:  # In test environment
        return

    for simplified_case in SimplifiedCase.objects.all():
        id_within_case: int = 0
        created_by_id: int = (
            simplified_case.auditor_id
            if simplified_case.auditor_id is not None
            else DEFAULT_CREATED_BY_USER_ID
        )
        if simplified_case.archive == "":
            audit: Audit = Audit.objects.filter(
                simplified_case_id=simplified_case.id
            ).first()
            if audit is not None and audit.exemptions_notes:
                with patch(
                    "django.utils.timezone.now",
                    Mock(return_value=CASE_NOTE_TIME_AUDIT_METADATA),
                ):
                    id_within_case += 1
                    SimplifiedCaseHistory.objects.create(
                        simplified_case=simplified_case,
                        id_within_case=id_within_case,
                        value=audit.exemptions_notes,
                        label="Initial test notes",
                        created_by_id=created_by_id,
                    )
            case_compliance: CaseCompliance = CaseCompliance.objects.filter(
                simplified_case_id=simplified_case.id
            ).first()
            if case_compliance is not None:
                if case_compliance.website_compliance_notes_initial:
                    with patch(
                        "django.utils.timezone.now",
                        Mock(return_value=CASE_NOTE_TIME_INITIAL_WEBSITE),
                    ):
                        id_within_case += 1
                        SimplifiedCaseHistory.objects.create(
                            simplified_case=simplified_case,
                            id_within_case=id_within_case,
                            value=case_compliance.website_compliance_notes_initial,
                            label="Initial website compliance notes",
                            created_by_id=created_by_id,
                        )
                if case_compliance.statement_compliance_notes_initial:
                    with patch(
                        "django.utils.timezone.now",
                        Mock(return_value=CASE_NOTE_TIME_INITIAL_STATEMENT),
                    ):
                        id_within_case += 1
                        SimplifiedCaseHistory.objects.create(
                            simplified_case=simplified_case,
                            id_within_case=id_within_case,
                            value=case_compliance.statement_compliance_notes_initial,
                            label="Initial statement compliance notes",
                            created_by_id=created_by_id,
                        )
            if simplified_case.twelve_week_correspondence_notes:
                with patch(
                    "django.utils.timezone.now",
                    Mock(return_value=CASE_NOTE_TIME_TWELVE_WEEK_CORRESPONDENCE),
                ):
                    id_within_case += 1
                    SimplifiedCaseHistory.objects.create(
                        simplified_case=simplified_case,
                        id_within_case=id_within_case,
                        value=simplified_case.twelve_week_correspondence_notes,
                        label="12-week correspondence notes",
                        created_by_id=created_by_id,
                    )
            if audit is not None and audit.audit_retest_metadata_notes:
                with patch(
                    "django.utils.timezone.now",
                    Mock(return_value=CASE_NOTE_TIME_AUDIT_RETEST_METADATA),
                ):
                    id_within_case += 1
                    SimplifiedCaseHistory.objects.create(
                        simplified_case=simplified_case,
                        id_within_case=id_within_case,
                        value=audit.audit_retest_metadata_notes,
                        label="12-week test notes",
                        created_by_id=created_by_id,
                    )
            if case_compliance is not None:
                if case_compliance.website_compliance_notes_12_week:
                    with patch(
                        "django.utils.timezone.now",
                        Mock(return_value=CASE_NOTE_TIME_12_WEEK_WEBSITE),
                    ):
                        id_within_case += 1
                        SimplifiedCaseHistory.objects.create(
                            simplified_case=simplified_case,
                            id_within_case=id_within_case,
                            value=case_compliance.website_compliance_notes_12_week,
                            label="12-week website compliance decision notes",
                            created_by_id=created_by_id,
                        )
                if case_compliance.statement_compliance_notes_12_week:
                    with patch(
                        "django.utils.timezone.now",
                        Mock(return_value=CASE_NOTE_TIME_12_WEEK_STATEMENT),
                    ):
                        id_within_case += 1
                        SimplifiedCaseHistory.objects.create(
                            simplified_case=simplified_case,
                            id_within_case=id_within_case,
                            value=case_compliance.statement_compliance_notes_12_week,
                            label="12-week statement compliance decision notes",
                            created_by_id=created_by_id,
                        )
            if simplified_case.psb_progress_notes:
                with patch(
                    "django.utils.timezone.now",
                    Mock(return_value=CASE_NOTE_TIME_CASE_PROGRESS),
                ):
                    id_within_case += 1
                    SimplifiedCaseHistory.objects.create(
                        simplified_case=simplified_case,
                        id_within_case=id_within_case,
                        value=simplified_case.psb_progress_notes,
                        label="Case progress notes",
                        created_by_id=created_by_id,
                    )
        if simplified_case.psb_appeal_notes:
            with patch(
                "django.utils.timezone.now",
                Mock(return_value=CASE_NOTE_TIME_PSB_APPEAL),
            ):
                id_within_case += 1
                SimplifiedCaseHistory.objects.create(
                    simplified_case=simplified_case,
                    id_within_case=id_within_case,
                    value=simplified_case.psb_appeal_notes,
                    label="Public sector body appeal notes",
                    created_by_id=created_by_id,
                )
        if simplified_case.equality_body_notes:
            with patch(
                "django.utils.timezone.now",
                Mock(return_value=CASE_NOTE_TIME_EQUALITY_BODY),
            ):
                id_within_case += 1
                SimplifiedCaseHistory.objects.create(
                    simplified_case=simplified_case,
                    id_within_case=id_within_case,
                    value=simplified_case.equality_body_notes,
                    label="Equality body notes",
                    created_by_id=created_by_id,
                )
        if simplified_case.no_psb_contact_notes:
            with patch(
                "django.utils.timezone.now",
                Mock(return_value=CASE_NOTE_TIME_NO_PSB_CONTACT),
            ):
                id_within_case += 1
                SimplifiedCaseHistory.objects.create(
                    simplified_case=simplified_case,
                    id_within_case=id_within_case,
                    value=simplified_case.no_psb_contact_notes,
                    label="Public sector body is unresponsive notes",
                    created_by_id=created_by_id,
                )


def reverse_code(apps, schema_editor):
    SimplifiedCaseHistory = apps.get_model("simplified", "SimplifiedCaseHistory")
    for simplified_case_history in SimplifiedCaseHistory.objects.all():
        simplified_case_history.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("simplified", "0010_simplifiedcasehistory"),
    ]

    operations = [
        migrations.RunPython(populate_case_notes, reverse_code=reverse_code),
    ]
