# Generated by Django 6.0.1 on 2026-01-23 14:01

from django.db import migrations


def update_archived_case_idientifiers(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")

    for simplified_case in SimplifiedCase.objects.exclude(archive=""):
        simplified_case.case_identifier += "A"
        simplified_case.save()


def reverse_code(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")

    for simplified_case in SimplifiedCase.objects.exclude(archive=""):
        if simplified_case.case_identifier[-1] == "A":
            simplified_case.case_identifier = simplified_case.case_identifier[:-1]
            simplified_case.save()


class Migration(migrations.Migration):

    dependencies = [
        ("simplified", "0011_populate_case_notes"),
    ]

    operations = [
        migrations.RunPython(
            update_archived_case_idientifiers, reverse_code=reverse_code
        ),
    ]
