version: "3.7"
services:
    db:
        image: postgres:11.12
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5433:5433"
        command: -p 5433

    web:
        image: "django_amp:latest"
        command: >
            bash -c "
            sleep 10;
            psql postgres://admin:secret@db:5433/postgres -c \"create database accessibility_monitoring_app;\";
            python3 manage.py collectstatic --noinput;
            python3 manage.py migrate;
            echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(\'admin@email.com\', \'admin@email.com\', \'secret\')\" | python3 manage.py shell;
            python3 manage.py recache_statuses;
            waitress-serve --port=8001 accessibility_monitoring_platform.wsgi:application;
            "
        ports:
            - "8001:8001"
        depends_on:
            - db
        environment:
            - PGPASSWORD=secret
            - VCAP_SERVICES={'postgres':[{'credentials':{'uri':'postgres://admin:secret@db:5433/accessibility_monitoring_app'},'name':'monitoring-platform-default-db'},{'credentials':{'uri':'postgres://admin:secret@db:5433/a11ymon'},'name':'a11ymon-postgres'}]}
            - ALLOWED_HOSTS='* localhost 0.0.0.0 0.0.0.0:8001'
            - SECRET_KEY='123456789'
            - DEBUG=TRUE
            - PORT='8001'
        links:
            - "db:db"
