version: "3.7"
services:
    cypress:
        image: "cypress/included:12.5.1"
        environment:
            - CYPRESS_SMOKE_TESTS_USERNAME=${SMOKE_TESTS_USERNAME}
            - CYPRESS_SMOKE_TESTS_PASSWORD=${SMOKE_TESTS_PASSWORD}
        volumes:
            - ./cypress:/cypress
            - ./staging-platform.cypress.config.js:/cypress.config.js
