# Generated by Django 4.2.8 on 2024-01-05 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# accessibility_monitoring_platform.apps.s3_read_write.migrations.0005_cleanup_latest_published
def cleanup_latest_published(apps, schema_editor):  # pylint: disable=unused-argument
    S3Report = apps.get_model("s3_read_write", "S3Report")
    s3_reports_by_case = {}
    for s3_report in S3Report.objects.all():
        if s3_report.case_id in s3_reports_by_case:
            s3_reports_by_case[s3_report.case_id].append(s3_report)
        else:
            s3_reports_by_case[s3_report.case_id] = [s3_report]

    for s3_reports in s3_reports_by_case.values():
        s3_reports[-1].latest_published = True
        s3_reports[-1].save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    S3Report = apps.get_model("s3_read_write", "S3Report")
    for s3_report in S3Report.objects.all():
        s3_report.latest_published = False
        s3_report.save()


class Migration(migrations.Migration):
    replaces = [
        ("s3_read_write", "0001_initial"),
        ("s3_read_write", "0002_remove_s3report_platform_version"),
        ("s3_read_write", "0003_s3report_html"),
        ("s3_read_write", "0004_rename_deprecated_s3report_latest_published_and_more"),
        ("s3_read_write", "0005_cleanup_latest_published"),
    ]

    initial = True

    dependencies = [
        ("cases", "0023_auto_20220201_1532"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="S3Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s3_directory", models.TextField(blank=True, default="")),
                ("version", models.IntegerField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("latest_published", models.BooleanField(default=False)),
                ("guid", models.CharField(blank=True, max_length=40)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cases.case"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("html", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.RunPython(
            code=cleanup_latest_published,
            reverse_code=reverse_code,
        ),
    ]
