# Generated by Django 5.2.1 on 2025-06-04 13:37

from django.db import migrations


def populate_base_case(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")
    S3Report = apps.get_model("s3_read_write", "S3Report")
    for count, simplified_case in enumerate(
        SimplifiedCase.objects.all().order_by("id"), start=1
    ):
        print(f"{count}: Migrating S3Report Case number {simplified_case.case_number}")
        for s3_report in S3Report.objects.filter(case_id=simplified_case.case_id):
            s3_report.base_case_id = simplified_case.basecase_ptr
            s3_report.save()


def reverse_code(apps, schema_editor):
    S3Report = apps.get_model("s3_read_write", "S3Report")
    S3Report.objects.all().update(base_case_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("s3_read_write", "0002_s3report_base_case"),
        ("simplified", "0003_populate_simplified_cases"),
    ]

    operations = [
        migrations.RunPython(populate_base_case, reverse_code=reverse_code),
    ]
