# Generated by Django 4.1.2 on 2022-11-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("s3_read_write", "0003_s3report_html"),
    ]

    operations = [
        migrations.RenameField(
            model_name="s3report",
            old_name="deprecated",
            new_name="latest_published",
        ),
        migrations.RemoveField(
            model_name="s3report",
            name="visible",
        ),
    ]
