# Generated by Django 6.1.1 on 2026-09-22 13:57

import logging

from django.conf import settings
from django.db import migrations

from accessibility_monitoring_platform.apps.common.s3_utils import S3Wrapper

logger = logging.getLogger(__name__)


class S3UpdateKey(S3Wrapper):
    def check_file_on_s3(self, old_key: str) -> bool:
        try:
            self.s3_client.head_object(Bucket=self.bucket, Key=old_key)
            return True
        except self.s3_client.exceptions.ClientError:
            return False

    def update_key(self, old_key: str, new_key: str) -> None:
        breakpoint()
        self.s3_resource.meta.client.copy(
            {"Bucket": self.bucket, "Key": old_key}, self.bucket, new_key
        )
        self.s3_client.delete_object(Bucket=self.bucket, Key=old_key)


def correct_report_s3_keys(apps, schema_editor):
    if settings.UNDER_TEST:
        return
    S3Report = apps.get_model("s3_read_write", "S3Report")
    s3_update_key: S3UpdateKey = S3UpdateKey()
    for s3_report in S3Report.objects.all().order_by("id"):
        if not s3_report.s3_directory.startswith(f"caseid_{s3_report.base_case_id}/"):
            old_s3_directory: str = s3_report.s3_directory
            old_prefix, old_suffix = old_s3_directory.split("/")
            new_s3_directory: str = f"caseid_{s3_report.base_case_id}/{old_suffix}"
            if s3_update_key.check_file_on_s3(old_key=old_s3_directory) is True:
                logger.warning("Missing published report in S3: %s", old_s3_directory)
                s3_update_key.update_key(
                    old_key=old_s3_directory, new_key=new_s3_directory
                )
                s3_report.s3_directory = new_s3_directory
                s3_report.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("s3_read_write", "0004_remove_s3report_case"),
    ]

    operations = [
        migrations.RunPython(correct_report_s3_keys, reverse_code=reverse_code),
    ]
