# Generated by Django 6.0 on 2026-02-10 15:18

import accessibility_monitoring_platform.apps.s3_read_write.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("s3_read_write", "0004_remove_s3report_case"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_center", models.CharField(max_length=255)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        storage=accessibility_monitoring_platform.apps.s3_read_write.models.InvoiceFileS3Storage,
                        upload_to=accessibility_monitoring_platform.apps.s3_read_write.models.get_invoice_s3_file_path,
                    ),
                ),
            ],
        ),
    ]
