# Generated by Django 6.0.1 on 2026-02-13 15:23

import accessibility_monitoring_platform.apps.s3_read_write.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("s3_read_write", "0005_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=accessibility_monitoring_platform.apps.s3_read_write.models.InvoiceFileS3Storage(),
                upload_to=accessibility_monitoring_platform.apps.s3_read_write.models.get_invoice_s3_file_path,
            ),
        ),
    ]
