# Generated by Django 5.0.4 on 2024-06-05 08:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "published_report_data_updated_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("date_of_test", models.DateField(default=datetime.date.today)),
                (
                    "screen_size",
                    models.CharField(
                        choices=[
                            ("15in", "15 inch"),
                            ("14in", "14 inch"),
                            ("13in", "13 inch"),
                        ],
                        default="15in",
                        max_length=20,
                    ),
                ),
                (
                    "exemptions_state",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("exemptions_notes", models.TextField(blank=True, default="")),
                (
                    "audit_metadata_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                ("audit_pages_complete_date", models.DateField(blank=True, null=True)),
                (
                    "audit_website_decision_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "accessibility_statement_backup_url",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "accessibility_statement_backup_url_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "archive_declaration_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("not-present", "Not included"),
                            ("other", "Other"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Declaration",
                    ),
                ),
                ("archive_declaration_notes", models.TextField(blank=True, default="")),
                (
                    "archive_scope_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("not-present", "Not included"),
                            ("incomplete", "Does not cover entire website"),
                            ("other", "Other"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Scope",
                    ),
                ),
                ("archive_scope_notes", models.TextField(blank=True, default="")),
                (
                    "archive_compliance_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("incorrect", "Present but incorrect"),
                            ("not-present", "Not present"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Compliance Status",
                    ),
                ),
                ("archive_compliance_notes", models.TextField(blank=True, default="")),
                (
                    "archive_non_regulation_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("incorrect", "Present but incorrect"),
                            ("not-present", "Not present"),
                            ("n/a", "N/A"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Non-accessible Content - non compliance with regulations",
                    ),
                ),
                (
                    "archive_non_regulation_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_disproportionate_burden_state",
                    models.CharField(
                        choices=[
                            ("no-assessment", "Claim with no assessment"),
                            ("assessment", "Claim with assessment"),
                            ("no-claim", "No claim or no statement"),
                            ("not-checked", "Not checked"),
                        ],
                        default="no-claim",
                        max_length=20,
                        verbose_name="Non-accessible Content - disproportionate burden",
                    ),
                ),
                (
                    "archive_disproportionate_burden_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_content_not_in_scope_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("incorrect", "Present but incorrect"),
                            ("not-present", "Not present"),
                            ("n/a", "N/A"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Non-accessible Content - the content is not within the scope of the applicable legislation",
                    ),
                ),
                (
                    "archive_content_not_in_scope_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_preparation_date_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("not-present", "Not included"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Preparation Date",
                    ),
                ),
                (
                    "archive_preparation_date_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_statement_1_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "archive_method_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("incomplete", "Present but missing detail"),
                            ("not-present", "Not present"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Method",
                    ),
                ),
                ("archive_method_notes", models.TextField(blank=True, default="")),
                (
                    "archive_review_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("out-of-date", "Present but out of date"),
                            ("not-present", "Not included"),
                            ("n/a", "N/A"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Review",
                    ),
                ),
                ("archive_review_notes", models.TextField(blank=True, default="")),
                (
                    "archive_feedback_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("incomplete", "Present but missing detail"),
                            ("not-present", "Not present"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Feedback",
                    ),
                ),
                ("archive_feedback_notes", models.TextField(blank=True, default="")),
                (
                    "archive_contact_information_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("incomplete", "Present but missing detail"),
                            ("not-present", "Not present"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Contact Information",
                    ),
                ),
                (
                    "archive_contact_information_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_enforcement_procedure_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("not-present", "Not included"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                        verbose_name="Enforcement Procedure",
                    ),
                ),
                (
                    "archive_enforcement_procedure_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_access_requirements_state",
                    models.CharField(
                        choices=[
                            ("req-met", "Meets requirements"),
                            ("req-not-met", "Does not meet requirements"),
                            ("n/a", "N/A"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="req-not-met",
                        max_length=20,
                        verbose_name="Access Requirements",
                    ),
                ),
                (
                    "archive_access_requirements_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_statement_2_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_statement_decision_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_summary_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "archive_accessibility_statement_state",
                    models.CharField(
                        choices=[
                            (
                                "not-found",
                                "An accessibility statement for the website was not found.",
                            ),
                            (
                                "found",
                                "An accessibility statement for the website was found in the correct format.",
                            ),
                            (
                                "found-but",
                                "An accessibility statement for the website was found but:",
                            ),
                        ],
                        default="not-found",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_not_correct_format",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_not_specific_enough",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_missing_accessibility_issues",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_missing_mandatory_wording",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_missing_mandatory_wording_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_accessibility_statement_needs_more_re_disproportionate",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_needs_more_re_accessibility",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_deadline_not_complete",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_deadline_not_complete_wording",
                    models.TextField(
                        blank=True,
                        default="it includes a deadline of XXX for fixing XXX issues and this has not been completed",
                    ),
                ),
                (
                    "archive_accessibility_statement_deadline_not_sufficient",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_deadline_not_sufficient_wording",
                    models.TextField(
                        blank=True,
                        default="it includes a deadline of XXX for fixing XXX issues and this is not sufficient",
                    ),
                ),
                (
                    "archive_accessibility_statement_out_of_date",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_eass_link",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_template_update",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_accessible",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_prominent",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_report_options_next",
                    models.CharField(
                        choices=[
                            ("errors", "Errors were found"),
                            ("no-errors", "No serious errors were found"),
                        ],
                        default="errors",
                        max_length=20,
                    ),
                ),
                (
                    "archive_report_next_change_statement",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_report_next_no_statement",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_report_next_statement_not_right",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_report_next_statement_matches",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_report_next_disproportionate_burden",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "archive_accessibility_statement_report_text_wording",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_report_options_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_report_options_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_statement_pages_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_extra_report_text",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "audit_statement_overview_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_statement_website_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_statement_compliance_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_statement_non_accessible_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_statement_preparation_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_statement_feedback_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_statement_custom_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "initial_disproportionate_burden_claim",
                    models.CharField(
                        choices=[
                            ("no-assessment", "Claim with no assessment"),
                            ("assessment", "Claim with assessment"),
                            ("no-claim", "No claim or no statement"),
                            ("not-checked", "Not checked"),
                        ],
                        default="not-checked",
                        max_length=20,
                    ),
                ),
                (
                    "initial_disproportionate_burden_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "initial_disproportionate_burden_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "archive_audit_report_text_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                ("retest_date", models.DateField(blank=True, null=True)),
                (
                    "audit_retest_metadata_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "audit_retest_metadata_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_pages_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_website_decision_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "twelve_week_accessibility_statement_url",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "audit_retest_accessibility_statement_backup_url",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "audit_retest_accessibility_statement_backup_url_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "archive_audit_retest_declaration_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("not-present", "Not included"),
                            ("other", "Other"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_declaration_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_scope_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("not-present", "Not included"),
                            ("incomplete", "Does not cover entire website"),
                            ("other", "Other"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_scope_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_compliance_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("incorrect", "Present but incorrect"),
                            ("not-present", "Not present"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_compliance_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_non_regulation_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("incorrect", "Present but incorrect"),
                            ("not-present", "Not present"),
                            ("n/a", "N/A"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_non_regulation_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_disproportionate_burden_state",
                    models.CharField(
                        choices=[
                            ("no-assessment", "Claim with no assessment"),
                            ("assessment", "Claim with assessment"),
                            ("no-claim", "No claim or no statement"),
                            ("not-checked", "Not checked"),
                        ],
                        default="no-claim",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_disproportionate_burden_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_content_not_in_scope_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("incorrect", "Present but incorrect"),
                            ("not-present", "Not present"),
                            ("n/a", "N/A"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_content_not_in_scope_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_preparation_date_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("not-present", "Not included"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_preparation_date_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_statement_1_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "archive_audit_retest_method_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("incomplete", "Present but missing detail"),
                            ("not-present", "Not present"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_method_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_review_state",
                    models.CharField(
                        choices=[
                            ("present", "Present and correct"),
                            ("out-of-date", "Present but out of date"),
                            ("not-present", "Not included"),
                            ("n/a", "N/A"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_review_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_feedback_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("incomplete", "Present but missing detail"),
                            ("not-present", "Not present"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_feedback_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_contact_information_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("incomplete", "Present but missing detail"),
                            ("not-present", "Not present"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_contact_information_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_enforcement_procedure_state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("not-present", "Not included"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="not-present",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_enforcement_procedure_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_access_requirements_state",
                    models.CharField(
                        choices=[
                            ("req-met", "Meets requirements"),
                            ("req-not-met", "Does not meet requirements"),
                            ("n/a", "N/A"),
                            ("other", "Other (Please specify)"),
                        ],
                        default="req-not-met",
                        max_length=20,
                    ),
                ),
                (
                    "archive_audit_retest_access_requirements_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "archive_audit_retest_statement_2_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_pages_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_overview_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_website_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_compliance_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_non_accessible_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_preparation_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_feedback_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_custom_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "twelve_week_disproportionate_burden_claim",
                    models.CharField(
                        choices=[
                            ("no-assessment", "Claim with no assessment"),
                            ("assessment", "Claim with assessment"),
                            ("no-claim", "No claim or no statement"),
                            ("not-checked", "Not checked"),
                        ],
                        default="not-checked",
                        max_length=20,
                    ),
                ),
                (
                    "twelve_week_disproportionate_burden_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "twelve_week_disproportionate_burden_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_comparison_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "audit_retest_statement_decision_complete_date",
                    models.DateField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("axe", "Axe"), ("pdf", "PDF")],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "check_result_state",
                    models.CharField(
                        choices=[
                            ("error", "Error found"),
                            ("no-error", "No issue"),
                            ("not-tested", "Not tested"),
                        ],
                        default="not-tested",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "retest_state",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("not-fixed", "Not fixed"),
                            ("not-retested", "Not retested"),
                        ],
                        default="not-retested",
                        max_length=20,
                    ),
                ),
                ("retest_notes", models.TextField(blank=True, default="")),
                ("updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("extra", "Additional"),
                            ("home", "Home"),
                            ("contact", "Contact"),
                            ("statement", "Accessibility statement"),
                            ("coronavirus", "Coronavirus"),
                            ("pdf", "PDF"),
                            ("form", "Form"),
                        ],
                        default="extra",
                        max_length=20,
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("url", models.TextField(blank=True, default="")),
                ("location", models.TextField(blank=True, default="")),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("no_errors_date", models.DateField(blank=True, null=True)),
                (
                    "not_found",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "is_contact_page",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                ("retest_complete_date", models.DateField(blank=True, null=True)),
                ("retest_page_missing_date", models.DateField(blank=True, null=True)),
                ("retest_notes", models.TextField(blank=True, default="")),
                ("updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Retest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("id_within_case", models.IntegerField(blank=True, default=1)),
                ("date_of_retest", models.DateField(default=datetime.date.today)),
                ("retest_notes", models.TextField(blank=True, default="")),
                (
                    "retest_compliance_state",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("partially-compliant", "Partially compliant"),
                            ("not-known", "Not known"),
                        ],
                        default="not-known",
                        max_length=20,
                    ),
                ),
                ("compliance_notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("comparison_complete_date", models.DateField(blank=True, null=True)),
                ("compliance_complete_date", models.DateField(blank=True, null=True)),
                (
                    "statement_pages_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_overview_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_website_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_compliance_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_non_accessible_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_preparation_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_feedback_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_custom_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_results_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "disproportionate_burden_claim",
                    models.CharField(
                        choices=[
                            ("no-assessment", "Claim with no assessment"),
                            ("assessment", "Claim with assessment"),
                            ("no-claim", "No claim or no statement"),
                            ("not-checked", "Not checked"),
                        ],
                        default="not-checked",
                        max_length=20,
                    ),
                ),
                (
                    "disproportionate_burden_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "disproportionate_burden_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_compliance_state",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("not-compliant", "Not compliant or no statement"),
                            ("unknown", "Not assessed"),
                        ],
                        default="unknown",
                        max_length=200,
                    ),
                ),
                (
                    "statement_compliance_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "statement_decision_complete_date",
                    models.DateField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["case_id", "-id_within_case"],
            },
        ),
        migrations.CreateModel(
            name="RetestCheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "retest_state",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("not-fixed", "Not fixed"),
                            ("not-retested", "Not retested"),
                        ],
                        default="not-retested",
                        max_length=20,
                    ),
                ),
                ("retest_notes", models.TextField(blank=True, default="")),
                ("updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RetestPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("missing_date", models.DateField(blank=True, null=True)),
                ("additional_issues_notes", models.TextField(blank=True, default="")),
                ("complete_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RetestStatementCheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("overview", "Statement overview"),
                            ("website", "Statement information"),
                            ("compliance", "Compliance status"),
                            ("non-accessible", "Non-accessible content"),
                            ("preparation", "Statement preparation"),
                            ("feedback", "Feedback and enforcement procedure"),
                            ("custom", "Custom statement issues"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "check_result_state",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not-tested", "Not tested"),
                        ],
                        default="not-tested",
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["statement_check__position", "id"],
            },
        ),
        migrations.CreateModel(
            name="StatementCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("overview", "Statement overview"),
                            ("website", "Statement information"),
                            ("compliance", "Compliance status"),
                            ("non-accessible", "Non-accessible content"),
                            ("preparation", "Statement preparation"),
                            ("feedback", "Feedback and enforcement procedure"),
                            ("custom", "Custom statement issues"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("label", models.TextField(blank=True, default="")),
                ("success_criteria", models.TextField(blank=True, default="")),
                ("report_text", models.TextField(blank=True, default="")),
                ("position", models.IntegerField(default=0)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="StatementCheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("overview", "Statement overview"),
                            ("website", "Statement information"),
                            ("compliance", "Compliance status"),
                            ("non-accessible", "Non-accessible content"),
                            ("preparation", "Statement preparation"),
                            ("feedback", "Feedback and enforcement procedure"),
                            ("custom", "Custom statement issues"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "check_result_state",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not-tested", "Not tested"),
                        ],
                        default="not-tested",
                        max_length=10,
                    ),
                ),
                ("report_comment", models.TextField(blank=True, default="")),
                ("auditor_notes", models.TextField(blank=True, default="")),
                (
                    "retest_state",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not-tested", "Not tested"),
                        ],
                        default="not-tested",
                        max_length=10,
                    ),
                ),
                ("retest_comment", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["statement_check__position", "id"],
            },
        ),
        migrations.CreateModel(
            name="StatementPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("url", models.TextField(blank=True, default="")),
                ("backup_url", models.TextField(blank=True, default="")),
                (
                    "added_stage",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("12-week-retest", "12-week retest"),
                            ("retest", "Equality body retest"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WcagDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("axe", "Axe"), ("pdf", "PDF")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("hint", models.TextField(blank=True, default="")),
                ("url_on_w3", models.TextField(blank=True, default="")),
                ("report_boilerplate", models.TextField(blank=True, default="")),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
