# Generated by Django 3.2.8 on 2022-01-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_populate_wcag_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_statement_decision_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_website_decision_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
