# Generated by Django 5.0.7 on 2024-07-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_populate_statement_checks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="date_of_test",
            field=models.DateField(blank=True, null=True),
        ),
    ]
