# Generated by Django 3.2.8 on 2022-01-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20220126_1004'),
        ('audits', '0003_auto_20220127_1445'),
    ]

    operations = [
    ]
