# Generated by Django 5.0.7 on 2024-07-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_populate_statement_checks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audit",
            old_name="audit_summary_complete_date",
            new_name="audit_statement_summary_complete_date",
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_wcag_summary_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
