# Generated by Django 3.2.11 on 2022-02-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_merge_0003_auto_20220126_1004_0003_auto_20220127_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='overall_compliance_notes',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='overall_compliance_state',
        ),
    ]
