# Generated by Django 3.2.11 on 2022-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_merge_0003_auto_20220126_1004_0003_auto_20220127_1445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_accessible",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_deadline_not_complete",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_deadline_not_sufficient",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_missing_accessibility_issues",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_missing_mandatory_wording",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_needs_more_re_accessibility",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_needs_more_re_disproportionate",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_not_correct_format",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_not_specific_enough",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_out_of_date",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_prominent",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="accessibility_statement_template_update",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="report_next_change_statement",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="report_next_disproportionate_burden",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="report_next_no_statement",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="report_next_statement_matches",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="report_next_statement_not_right",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="not_found",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
    ]
