# Generated by Django 5.1.1 on 2024-09-30 09:31

from django.db import migrations


def populate_id_with_case(apps, schema_editor):  # pylint: disable=unused-argument
    Audit = apps.get_model("audits", "Audit")
    CheckResult = apps.get_model("audits", "CheckResult")
    for audit in Audit.objects.all():
        id_within_case = 0
        for check_result in CheckResult.objects.filter(audit=audit):
            id_within_case += 1
            check_result.id_within_case = id_within_case
            check_result.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0005_checkresult_id_within_case"),
    ]

    operations = [
        migrations.RunPython(populate_id_with_case, reverse_code=reverse_code),
    ]
