# Generated by Django 3.2.11 on 2022-02-04 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0005_auto_20220201_1529"),
        ("audits", "0005_auto_20220203_1546"),
    ]

    operations = []
