# Generated by Django 3.2.11 on 2022-02-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0006_merge_0005_auto_20220201_1529_0005_auto_20220203_1546"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audit",
            name="retest_of_audit",
        ),
        migrations.RemoveField(
            model_name="audit",
            name="type",
        ),
        migrations.AddField(
            model_name="audit",
            name="retest_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
