# Generated by Django 5.1.1 on 2024-10-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0006_populate_id_with_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_summary_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_wcag_summary_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
