# Generated by Django 4.0.2 on 2022-02-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_merge_0005_auto_20220201_1529_0005_auto_20220203_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='retest_of_audit',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='type',
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_access_requirements_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_access_requirements_state',
            field=models.CharField(choices=[('req-met', 'Meets requirements'), ('req-not-met', 'Does not meet requirements'), ('n/a', 'N/A'), ('other', 'Other (Please specify)')], default='req-not-met', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_compliance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_compliance_state',
            field=models.CharField(choices=[('present', 'Present and correct'), ('incorrect', 'Present but incorrect'), ('not-present', 'Not present'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_contact_information_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_contact_information_state',
            field=models.CharField(choices=[('present', 'Present'), ('incomplete', 'Present but missing detail'), ('not-present', 'Not present'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_content_not_in_scope_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_content_not_in_scope_state',
            field=models.CharField(choices=[('present', 'Present and correct'), ('incorrect', 'Present but incorrect'), ('not-present', 'Not present'), ('n/a', 'N/A'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_declaration_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_declaration_state',
            field=models.CharField(choices=[('present', 'Present and correct'), ('not-present', 'Not included'), ('other', 'Other')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_disproportionate_burden_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_disproportionate_burden_state',
            field=models.CharField(choices=[('no-claim', 'No claim'), ('assessment', 'Claim with assessment'), ('no-assessment', 'Claim with no assessment')], default='no-claim', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_enforcement_procedure_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_enforcement_procedure_state',
            field=models.CharField(choices=[('present', 'Present'), ('not-present', 'Not included'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_feedback_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_feedback_state',
            field=models.CharField(choices=[('present', 'Present'), ('incomplete', 'Present but missing detail'), ('not-present', 'Not present'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_metadata_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_method_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_method_state',
            field=models.CharField(choices=[('present', 'Present'), ('incomplete', 'Present but missing detail'), ('not-present', 'Not present'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_non_regulation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_non_regulation_state',
            field=models.CharField(choices=[('present', 'Present and correct'), ('incorrect', 'Present but incorrect'), ('not-present', 'Not present'), ('n/a', 'N/A'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_pages_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_preparation_date_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_preparation_date_state',
            field=models.CharField(choices=[('present', 'Present'), ('not-present', 'Not included'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_review_state',
            field=models.CharField(choices=[('present', 'Present and correct'), ('not-present', 'Not included'), ('n/a', 'N/A'), ('other', 'Other (Please specify)')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_scope_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_scope_state',
            field=models.CharField(choices=[('present', 'Present and correct'), ('not-present', 'Not included'), ('incomplete', 'Does not cover entire website'), ('other', 'Other')], default='not-present', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_statement_1_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_statement_2_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_statement_decision_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_retest_website_decision_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='retest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='retest_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='retest_state',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('not-fixed', 'Not fixed'), ('not-retested', 'Not retested')], default='not-retested', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='retest_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='retest_page_missing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
