# Generated by Django 3.2.11 on 2022-02-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0007_auto_20220217_0916"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_retest_metadata_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
