# Generated by Django 3.2.11 on 2022-02-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_add_post_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_retest_pages_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
