# Generated by Django 5.1.2 on 2024-10-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0007_audit_audit_retest_statement_summary_complete_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="screen_size",
            field=models.CharField(
                choices=[("13in", "13 inch"), ("14in", "14 inch"), ("15in", "15 inch")],
                default="13in",
                max_length=20,
            ),
        ),
    ]
