# Generated by Django 4.0.2 on 2022-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0007_add_12_week_retest"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_retest_metadata_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
