# Generated by Django 4.1a1 on 2022-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0008_audit_audit_retest_metadata_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="accessibility_statement_backup_url_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_accessibility_statement_backup_url_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
