# Generated by Django 5.1.3 on 2024-11-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0008_alter_audit_screen_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="archive_audit_retest_disproportionate_burden_state",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="no-claim",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="archive_disproportionate_burden_state",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="no-claim",
                max_length=20,
                verbose_name="Non-accessible Content - disproportionate burden",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="initial_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="twelve_week_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="retest",
            name="disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
    ]
