# Generated by Django 3.2.11 on 2022-02-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_audit_audit_retest_pages_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='retest_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='retest_state',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partially'), ('not-applicable', 'N/A')], default='not-applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='retest_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='retest_page_missing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
