# Generated by Django 3.2.11 on 2022-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_auto_20220218_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_retest_website_decision_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='retest_state',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partially'), ('not-applicable', 'N/A')], default='no', max_length=20),
        ),
    ]
