# Generated by Django 3.2.11 on 2022-02-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_auto_20220218_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_retest_statement_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
