# Generated by Django 5.1.4 on 2025-01-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0011_remove_audit_accessibility_statement_backup_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkresult",
            name="issue_identifier",
            field=models.CharField(max_length=20, default=""),
        ),
        migrations.AddField(
            model_name="retestcheckresult",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="retestcheckresult",
            name="issue_identifier",
            field=models.CharField(max_length=20, default=""),
        ),
        migrations.AddField(
            model_name="reteststatementcheckresult",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="reteststatementcheckresult",
            name="issue_identifier",
            field=models.CharField(max_length=20, default=""),
        ),
        migrations.AddField(
            model_name="statementcheck",
            name="issue_number",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="statementcheckresult",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="statementcheckresult",
            name="issue_identifier",
            field=models.CharField(max_length=20, default=""),
        ),
        migrations.AddIndex(
            model_name="checkresult",
            index=models.Index(
                fields=["issue_identifier"], name="audits_chec_issue_i_a8fd9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retestcheckresult",
            index=models.Index(
                fields=["issue_identifier"], name="audits_rete_issue_i_4df993_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reteststatementcheckresult",
            index=models.Index(
                fields=["issue_identifier"], name="audits_rete_issue_i_a854a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statementcheckresult",
            index=models.Index(
                fields=["issue_identifier"], name="audits_stat_issue_i_d20fe4_idx"
            ),
        ),
    ]
