# Generated by Django 4.1a1 on 2022-06-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0011_alter_audit_audit_retest_review_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="report_options_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
