# Generated by Django 5.1.4 on 2024-12-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0011_remove_audit_accessibility_statement_backup_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="updated_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
