# Generated by Django 4.1a1 on 2022-07-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0012_audit_report_options_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="accessibility_statement_eass_link",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
    ]
