# Generated by Django 4.1b1 on 2022-07-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0013_audit_accessibility_statement_eass_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="report_data_updated_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
