# Generated by Django 5.1.4 on 2024-12-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0013_populate_ids_within_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="updated_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="page",
            name="updated_location",
            field=models.TextField(blank=True, default=""),
        ),
    ]
