# Generated by Django 4.1 on 2022-09-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0014_audit_report_data_updated_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audit",
            old_name="report_data_updated_time",
            new_name="published_report_data_updated_time",
        ),
        migrations.AddField(
            model_name="audit",
            name="unpublished_report_data_updated_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
