# Generated by Django 4.1.1 on 2022-09-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "audits",
            "0015_rename_report_data_updated_time_audit_published_report_data_updated_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_form",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
    ]
