# Generated by Django 5.2.1 on 2025-06-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0017_populate_check_result_histories"),
        ("cases", "0013_basecase"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="base_case",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_basecase",
                to="cases.basecase",
            ),
        ),
        migrations.AddField(
            model_name="retest",
            name="base_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cases.basecase",
            ),
        ),
    ]
