# Generated by Django 5.2.1 on 2025-06-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0017_populate_check_result_histories"),
        ("cases", "0014_alter_basecase_options"),
        ("simplified", "0003_populate_simplified_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="simplified_case",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_simplifiedcase",
                to="simplified.simplifiedcase",
            ),
        ),
        migrations.AddField(
            model_name="retest",
            name="simplified_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retest_simplifiedcase",
                to="simplified.simplifiedcase",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="case",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_case",
                to="cases.case",
            ),
        ),
    ]
