# Generated by Django 5.2.1 on 2025-06-04 13:16

from django.db import migrations


def populate_base_case(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")
    Audit = apps.get_model("audits", "Audit")
    Retest = apps.get_model("audits", "Retest")
    for count, simplified_case in enumerate(
        SimplifiedCase.objects.all().order_by("id"), start=1
    ):
        print(
            f"{count}: Migrating Audit and Retests Case number {simplified_case.case_number}"
        )
        for audit in Audit.objects.filter(case_id=simplified_case.case_id):
            audit.base_case_id = simplified_case.basecase_ptr
            audit.save()
        for retest in Retest.objects.filter(case_id=simplified_case.case_id):
            retest.base_case_id = simplified_case.basecase_ptr
            retest.save()


def reverse_code(apps, schema_editor):
    Retest = apps.get_model("audits", "Retest")
    Retest.objects.all().update(base_case_id=None)
    Audit = apps.get_model("audits", "Audit")
    Audit.objects.all().update(base_case_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0018_audit_base_case_retest_base_case"),
        ("simplified", "0003_populate_simplified_cases"),
    ]

    operations = [
        migrations.RunPython(populate_base_case, reverse_code=reverse_code),
    ]
