# Generated by Django 4.1.2 on 2022-10-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0018_remove_audit_is_deleted_alter_audit_case"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="is_form",
            new_name="is_contact_page",
        ),
    ]
