# Generated by Django 5.2.3 on 2025-07-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0019_populate_simplified_case"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retest",
            options={"ordering": ["simplified_case_id", "-id_within_case"]},
        ),
        migrations.RemoveField(
            model_name="audit",
            name="case",
        ),
        migrations.RemoveField(
            model_name="retest",
            name="case",
        ),
    ]
