# Generated by Django 5.2.3 on 2025-07-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0020_alter_retest_options_remove_audit_case_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reteststatementcheckresult",
            name="type",
            field=models.CharField(
                choices=[
                    ("overview", "Statement overview"),
                    ("website", "Statement information"),
                    ("compliance", "Compliance status"),
                    ("non-accessible", "Non-accessible content"),
                    ("preparation", "Statement preparation"),
                    ("feedback", "Feedback and enforcement procedure"),
                    ("custom", "Custom statement issues"),
                    ("12-week", "New 12-week custom statement issues"),
                    ("disproportionate", "Disproportionate burden"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statementcheck",
            name="type",
            field=models.CharField(
                choices=[
                    ("overview", "Statement overview"),
                    ("website", "Statement information"),
                    ("compliance", "Compliance status"),
                    ("non-accessible", "Non-accessible content"),
                    ("preparation", "Statement preparation"),
                    ("feedback", "Feedback and enforcement procedure"),
                    ("custom", "Custom statement issues"),
                    ("12-week", "New 12-week custom statement issues"),
                    ("disproportionate", "Disproportionate burden"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statementcheckresult",
            name="type",
            field=models.CharField(
                choices=[
                    ("overview", "Statement overview"),
                    ("website", "Statement information"),
                    ("compliance", "Compliance status"),
                    ("non-accessible", "Non-accessible content"),
                    ("preparation", "Statement preparation"),
                    ("feedback", "Feedback and enforcement procedure"),
                    ("custom", "Custom statement issues"),
                    ("12-week", "New 12-week custom statement issues"),
                    ("disproportionate", "Disproportionate burden"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
    ]
