# Generated by Django 4.1.4 on 2023-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0021_page_retest_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="twelve_week_accessibility_statement_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
