# Generated by Django 4.1.4 on 2023-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0022_audit_twelve_week_accessibility_statement_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkresult",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
