# Generated by Django 4.1.4 on 2023-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0023_audit_updated_checkresult_updated_page_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="access_requirements_state",
            field=models.CharField(
                choices=[
                    ("req-met", "Meets requirements"),
                    ("req-not-met", "Does not meet requirements"),
                    ("n/a", "N/A"),
                    ("other", "Other (Please specify)"),
                ],
                default="req-not-met",
                max_length=20,
                verbose_name="Access Requirements",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="compliance_state",
            field=models.CharField(
                choices=[
                    ("present", "Present and correct"),
                    ("incorrect", "Present but incorrect"),
                    ("not-present", "Not present"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Compliance Status",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="contact_information_state",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("incomplete", "Present but missing detail"),
                    ("not-present", "Not present"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Contact Information",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="content_not_in_scope_state",
            field=models.CharField(
                choices=[
                    ("present", "Present and correct"),
                    ("incorrect", "Present but incorrect"),
                    ("not-present", "Not present"),
                    ("n/a", "N/A"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Non-accessible Content - the content is not within the scope of the applicable legislation",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="declaration_state",
            field=models.CharField(
                choices=[
                    ("present", "Present and correct"),
                    ("not-present", "Not included"),
                    ("other", "Other"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Declaration",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="disproportionate_burden_state",
            field=models.CharField(
                choices=[
                    ("no-claim", "No claim"),
                    ("assessment", "Claim with assessment"),
                    ("no-assessment", "Claim with no assessment"),
                ],
                default="no-claim",
                max_length=20,
                verbose_name="Non-accessible Content - disproportionate burden",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="enforcement_procedure_state",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("not-present", "Not included"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Enforcement Procedure",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="feedback_state",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("incomplete", "Present but missing detail"),
                    ("not-present", "Not present"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Feedback",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="method_state",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("incomplete", "Present but missing detail"),
                    ("not-present", "Not present"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Method",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="non_regulation_state",
            field=models.CharField(
                choices=[
                    ("present", "Present and correct"),
                    ("incorrect", "Present but incorrect"),
                    ("not-present", "Not present"),
                    ("n/a", "N/A"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Non-accessible Content - non compliance with regulations",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="preparation_date_state",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("not-present", "Not included"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Preparation Date",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="review_state",
            field=models.CharField(
                choices=[
                    ("present", "Present and correct"),
                    ("out-of-date", "Present but out of date"),
                    ("not-present", "Not included"),
                    ("n/a", "N/A"),
                    ("other", "Other (Please specify)"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Review",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="scope_state",
            field=models.CharField(
                choices=[
                    ("present", "Present and correct"),
                    ("not-present", "Not included"),
                    ("incomplete", "Does not cover entire website"),
                    ("other", "Other"),
                ],
                default="not-present",
                max_length=20,
                verbose_name="Scope",
            ),
        ),
    ]
