# Generated by Django 6.0.3 on 2026-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0023_move_statement_questions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statementpage",
            options={},
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_initial_statement_backup_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statementpage",
            name="added_stage",
            field=models.CharField(
                choices=[
                    ("any", "Any"),
                    ("initial", "Initial"),
                    ("12-week-retest", "12-week retest"),
                    ("retest", "Equality body retest"),
                ],
                default="any",
                max_length=20,
            ),
        ),
    ]
