# Generated by Django 6.0.3 on 2026-03-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0023_move_statement_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_initial_statement_backup_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
