# Generated by Django 6.0.3 on 2026-04-09 14:16

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0024_alter_statementpage_options_and_more"),
        ("simplified", "0012_populate_archived_case_identifiers"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "audit_round_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial test"),
                            ("12-week", "12-week retest"),
                            ("equality-body", "Equality body retest"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("round", models.IntegerField(blank=True, default=0)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("date_of_test", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("pages_complete_date", models.DateField(blank=True, null=True)),
                ("backup_complete_date", models.DateField(blank=True, null=True)),
                (
                    "statement_overview_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_website_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_compliance_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_non_accessible_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_preparation_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_feedback_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_disproportionate_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_custom_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "disproportionate_burden_claim",
                    models.CharField(
                        choices=[
                            ("no-assessment", "Claim with no assessment"),
                            ("assessment", "Claim with assessment"),
                            ("no-claim", "No claim"),
                            ("no-statement", "No statement"),
                            ("not-checked", "Not checked"),
                        ],
                        default="not-checked",
                        max_length=20,
                    ),
                ),
                (
                    "disproportionate_burden_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "disproportionate_burden_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                ("compliance_complete_date", models.DateField(blank=True, null=True)),
                ("summary_complete_date", models.DateField(blank=True, null=True)),
                (
                    "simplified_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simplified.simplifiedcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WcagAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "audit_round_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial test"),
                            ("12-week", "12-week retest"),
                            ("equality-body", "Equality body retest"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("round", models.IntegerField(blank=True, default=0)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("date_of_test", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("metadata_complete_date", models.DateField(blank=True, null=True)),
                ("pages_complete_date", models.DateField(blank=True, null=True)),
                ("comparison_complete_date", models.DateField(blank=True, null=True)),
                (
                    "compliance_decision_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                ("summary_complete_date", models.DateField(blank=True, null=True)),
                (
                    "simplified_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simplified.simplifiedcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WcagPageInitial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("extra", "Additional"),
                            ("home", "Home"),
                            ("contact", "Contact"),
                            ("statement", "Accessibility statement"),
                            ("coronavirus", "Coronavirus"),
                            ("pdf", "PDF"),
                            ("form", "Form"),
                        ],
                        default="extra",
                        max_length=20,
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("url", models.TextField(blank=True, default="")),
                ("location", models.TextField(blank=True, default="")),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("no_errors_date", models.DateField(blank=True, null=True)),
                (
                    "not_found",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "is_contact_page",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("first_retest_url", models.TextField(blank=True, default="")),
                ("first_retest_location", models.TextField(blank=True, default="")),
                (
                    "first_retest_page_missing_date",
                    models.DateField(blank=True, null=True),
                ),
                ("first_retest_notes", models.TextField(blank=True, default="")),
                (
                    "wcag_audit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagaudit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WcagCheckResultInitial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_identifier", models.CharField(default="", max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("axe", "Axe"), ("pdf", "PDF")],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                ("id_within_case", models.IntegerField(blank=True, default=0)),
                (
                    "check_result_state",
                    models.CharField(
                        choices=[
                            ("error", "Error found"),
                            ("no-error", "No issue"),
                            ("not-tested", "Not tested"),
                        ],
                        default="not-tested",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "first_retest_state",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("not-fixed", "Not fixed"),
                            ("not-retested", "Not retested"),
                        ],
                        default="not-retested",
                        max_length=20,
                    ),
                ),
                ("first_retest_notes", models.TextField(blank=True, default="")),
                (
                    "wcag_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagdefinition",
                    ),
                ),
                (
                    "wcag_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagpageinitial",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WcagPageRetest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("extra", "Additional"),
                            ("home", "Home"),
                            ("contact", "Contact"),
                            ("statement", "Accessibility statement"),
                            ("coronavirus", "Coronavirus"),
                            ("pdf", "PDF"),
                            ("form", "Form"),
                        ],
                        default="extra",
                        max_length=20,
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("url", models.TextField(blank=True, default="")),
                ("location", models.TextField(blank=True, default="")),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("no_errors_date", models.DateField(blank=True, null=True)),
                (
                    "not_found",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "is_contact_page",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("page_missing_date", models.DateField(blank=True, null=True)),
                (
                    "wcag_audit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagaudit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WcagCheckResultRetest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_identifier", models.CharField(default="", max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("axe", "Axe"), ("pdf", "PDF")],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "previous_retest_state",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("not-fixed", "Not fixed"),
                            ("not-retested", "Not retested"),
                        ],
                        default="not-retested",
                        max_length=20,
                    ),
                ),
                ("previous_notes", models.TextField(blank=True, default="")),
                (
                    "retest_state",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("not-fixed", "Not fixed"),
                            ("not-retested", "Not retested"),
                        ],
                        default="not-retested",
                        max_length=20,
                    ),
                ),
                ("retest_notes", models.TextField(blank=True, default="")),
                (
                    "wcag_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagdefinition",
                    ),
                ),
                (
                    "wcag_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagpageretest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
