# Generated by Django 4.1.7 on 2023-04-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0024_alter_audit_access_requirements_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("overview", "Statement overview"),
                            ("website", "Accessibility statement for [website.com]"),
                            ("compliance", "Compliance status"),
                            ("non-accessible", "Non accessible content overview"),
                            (
                                "preparation",
                                "Preparation of this accessibility statement",
                            ),
                            ("feedback", "Feedback and contact information"),
                            ("enforcement", "Enforcement procedure"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("label", models.TextField(blank=True, default="")),
                ("success_criteria", models.TextField(blank=True, default="")),
                ("report_text", models.TextField(blank=True, default="")),
                ("position", models.IntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="StatementCheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("overview", "Statement overview"),
                            ("website", "Accessibility statement for [website.com]"),
                            ("compliance", "Compliance status"),
                            ("non-accessible", "Non accessible content overview"),
                            (
                                "preparation",
                                "Preparation of this accessibility statement",
                            ),
                            ("feedback", "Feedback and contact information"),
                            ("enforcement", "Enforcement procedure"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "statement_check_result",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("not-tested", "Not tested"),
                        ],
                        default="not-tested",
                        max_length=10,
                    ),
                ),
                ("report_comment", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="audits.audit"
                    ),
                ),
                (
                    "statement_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.statementcheck",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
