# Generated by Django 4.1.7 on 2023-04-06 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0024_alter_audit_access_requirements_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audit",
            name="unpublished_report_data_updated_time",
        ),
    ]
