# Generated by Django 4.1.7 on 2023-04-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0024_alter_audit_access_requirements_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_comparison_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
