# Generated by Django 6.0.3 on 2026-04-27 13:39

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0024_alter_statementpage_options_and_more"),
        ("simplified", "0012_populate_archived_case_identifiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="statementcheckresult",
            old_name="retest_comment",
            new_name="first_retest_comment",
        ),
        migrations.RenameField(
            model_name="statementcheckresult",
            old_name="retest_state",
            new_name="first_retest_state",
        ),
        migrations.RemoveField(
            model_name="checkresult",
            name="id_within_case",
        ),
        migrations.RemoveField(
            model_name="retestcheckresult",
            name="id_within_case",
        ),
        migrations.RemoveField(
            model_name="statementcheckresult",
            name="id_within_case",
        ),
        migrations.CreateModel(
            name="AuditMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published_report_data_updated_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("updated", models.DateTimeField(blank=True, null=True)),
                (
                    "simplified_case",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditmetadata_simplifiedcase",
                        to="simplified.simplifiedcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatementAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "audit_round_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial test"),
                            ("12-week", "12-week retest"),
                            ("equality-body", "Equality body retest"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("round", models.IntegerField(blank=True, default=0)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("date_of_test", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("pages_complete_date", models.DateField(blank=True, null=True)),
                ("backup_complete_date", models.DateField(blank=True, null=True)),
                (
                    "statement_overview_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_website_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_compliance_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_non_accessible_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_preparation_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_feedback_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_disproportionate_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "statement_custom_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "disproportionate_burden_claim",
                    models.CharField(
                        choices=[
                            ("no-assessment", "Claim with no assessment"),
                            ("assessment", "Claim with assessment"),
                            ("no-claim", "No claim"),
                            ("no-statement", "No statement"),
                            ("not-checked", "Not checked"),
                        ],
                        default="not-checked",
                        max_length=20,
                    ),
                ),
                (
                    "disproportionate_burden_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "disproportionate_burden_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "compliance_state",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("not-compliant", "Not compliant or no statement"),
                            ("unknown", "Not assessed"),
                        ],
                        default="unknown",
                        max_length=200,
                    ),
                ),
                ("compliance_notes", models.TextField(blank=True, default="")),
                ("compliance_complete_date", models.DateField(blank=True, null=True)),
                ("summary_complete_date", models.DateField(blank=True, null=True)),
                (
                    "simplified_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simplified.simplifiedcase",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="reteststatementcheckresult",
            name="statement_audit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="audits.statementaudit",
            ),
        ),
        migrations.AddField(
            model_name="statementcheckresult",
            name="statement_audit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="audits.statementaudit",
            ),
        ),
        migrations.AddField(
            model_name="statementpage",
            name="statement_audit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="audits.statementaudit",
            ),
        ),
        migrations.CreateModel(
            name="WcagAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "audit_round_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial test"),
                            ("12-week", "12-week retest"),
                            ("equality-body", "Equality body retest"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                ("round", models.IntegerField(blank=True, default=0)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("date_of_test", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "screen_size",
                    models.CharField(
                        choices=[
                            ("13in", "13 inch"),
                            ("14in", "14 inch"),
                            ("15in", "15 inch"),
                        ],
                        default="13in",
                        max_length=20,
                    ),
                ),
                (
                    "exemptions_state",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("metadata_complete_date", models.DateField(blank=True, null=True)),
                ("pages_complete_date", models.DateField(blank=True, null=True)),
                ("comparison_complete_date", models.DateField(blank=True, null=True)),
                (
                    "compliance_state",
                    models.CharField(
                        choices=[
                            ("compliant", "Fully compliant"),
                            ("partially-compliant", "Partially compliant"),
                            ("not-known", "Not known"),
                        ],
                        default="not-known",
                        max_length=20,
                    ),
                ),
                ("compliance_notes", models.TextField(blank=True, default="")),
                (
                    "compliance_decision_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                ("summary_complete_date", models.DateField(blank=True, null=True)),
                (
                    "simplified_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="simplified.simplifiedcase",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WcagCheckResultInitial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_identifier", models.CharField(default="", max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("axe", "Axe"), ("pdf", "PDF")],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "check_result_state",
                    models.CharField(
                        choices=[
                            ("error", "Error found"),
                            ("no-error", "No issue"),
                            ("not-tested", "Not tested"),
                        ],
                        default="not-tested",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "wcag_audit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagaudit",
                    ),
                ),
                (
                    "wcag_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagdefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WcagCheckResultInitialNotesHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wcag_check_result_initial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagcheckresultinitial",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Check result notes histories",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="WcagPageInitial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("extra", "Additional"),
                            ("home", "Home"),
                            ("contact", "Contact"),
                            ("statement", "Accessibility statement"),
                            ("coronavirus", "Coronavirus"),
                            ("pdf", "PDF"),
                            ("form", "Form"),
                        ],
                        default="extra",
                        max_length=20,
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                ("url", models.TextField(blank=True, default="")),
                ("location", models.TextField(blank=True, default="")),
                (
                    "not_found",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "is_contact_page",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "wcag_audit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagaudit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wcagcheckresultinitial",
            name="wcag_page_initial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="audits.wcagpageinitial"
            ),
        ),
        migrations.CreateModel(
            name="WcagPageRetest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("url", models.TextField(blank=True, default="")),
                ("location", models.TextField(blank=True, default="")),
                ("no_errors_date", models.DateField(blank=True, null=True)),
                ("page_missing_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "wcag_audit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagaudit",
                    ),
                ),
                (
                    "wcag_page_initial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagpageinitial",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WcagCheckResultRetest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_identifier", models.CharField(default="", max_length=20)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("axe", "Axe"), ("pdf", "PDF")],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "retest_state",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("not-fixed", "Not fixed"),
                            ("not-retested", "Not retested"),
                        ],
                        default="not-retested",
                        max_length=20,
                    ),
                ),
                ("retest_notes", models.TextField(blank=True, default="")),
                (
                    "wcag_audit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagaudit",
                    ),
                ),
                (
                    "wcag_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagdefinition",
                    ),
                ),
                (
                    "wcag_page_retest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.wcagpageretest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
