# Generated by Django 4.1.7 on 2023-04-20 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0025_audit_audit_retest_statement_comparison_complete_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audit",
            name="unpublished_report_data_updated_time",
        ),
    ]
