# Generated by Django 6.0.3 on 2026-04-08 08:19

from django.db import migrations

FIRST_AUDIT_OF_2026_ID: int = 8816
INITIAL_ROUND_TYPE: str = "initial"
TWELVE_WEEK_ROUND_TYPE = "12-week"
EQUALITY_BODY_ROUND_TYPE = "equality-body"
INITIAL_ROUND: int = 0
TWELVE_WEEK_ROUND: int = 1


def populate_audit_rounds(apps, schema_editor):
    Audit = apps.get_model("audits", "Audit")
    WcagAudit = apps.get_model("audits", "WCAGAudit")
    StatementAudit = apps.get_model("audits", "StatementAudit")
    Page = apps.get_model("audits", "Page")
    CheckResult = apps.get_model("audits", "CheckResult")
    for audit in Audit.objects.filter(id__gte=FIRST_AUDIT_OF_2026_ID).order_by("id"):
        wcag_audit_initial = WcagAudit.objects.create(
            simplified_case=audit.simplified_case,
            audit_round_type=INITIAL_ROUND_TYPE,
            round=INITIAL_ROUND,
            updated=audit.updated,
            date_of_test=audit.date_of_test,
            metadata_complete_date=audit.audit_metadata_complete_date,
            pages_complete_date=audit.audit_pages_complete_date,
            compliance_decision_complete_date=audit.audit_website_decision_complete_date,
            summary_complete_date=audit.audit_wcag_summary_complete_date,
        )
        StatementAudit.objects.create(
            simplified_case=audit.simplified_case,
            audit_round_type=INITIAL_ROUND_TYPE,
            round=INITIAL_ROUND,
            updated=audit.updated,
            date_of_test=audit.date_of_test,
            pages_complete_date=audit.audit_statement_pages_complete_date,
            backup_complete_date=audit.audit_initial_statement_backup_complete_date,
            statement_overview_complete_date=audit.audit_statement_overview_complete_date,
            statement_website_complete_date=audit.audit_statement_website_complete_date,
            statement_compliance_complete_date=audit.audit_statement_compliance_complete_date,
            statement_non_accessible_complete_date=audit.audit_statement_non_accessible_complete_date,
            statement_preparation_complete_date=audit.audit_statement_preparation_complete_date,
            statement_feedback_complete_date=audit.audit_statement_feedback_complete_date,
            statement_disproportionate_complete_date=audit.audit_statement_disproportionate_complete_date,
            statement_custom_complete_date=audit.audit_statement_custom_complete_date,
            disproportionate_burden_claim=audit.initial_disproportionate_burden_claim,
            disproportionate_burden_notes=audit.initial_disproportionate_burden_notes,
            disproportionate_burden_complete_date=audit.initial_disproportionate_burden_complete_date,
            compliance_complete_date=audit.audit_statement_decision_complete_date,
            summary_complete_date=audit.audit_statement_summary_complete_date,
        )
        wcag_audit_1 = None
        if audit.retest_date:
            wcag_audit_1 = WcagAudit.objects.create(
                simplified_case=audit.simplified_case,
                audit_round_type=TWELVE_WEEK_ROUND_TYPE,
                round=TWELVE_WEEK_ROUND,
                updated=audit.updated,
                date_of_test=audit.retest_date,
                notes=audit.audit_retest_metadata_notes,
                metadata_complete_date=audit.audit_retest_metadata_complete_date,
                pages_complete_date=audit.audit_retest_pages_complete_date,
                compliance_decision_complete_date=audit.audit_retest_website_decision_complete_date,
                summary_complete_date=audit.audit_retest_wcag_summary_complete_date,
            )
            StatementAudit.objects.create(
                simplified_case=audit.simplified_case,
                audit_round_type=TWELVE_WEEK_ROUND_TYPE,
                round=TWELVE_WEEK_ROUND,
                updated=audit.updated,
                date_of_test=audit.retest_date,
                pages_complete_date=audit.audit_retest_statement_pages_complete_date,
                backup_complete_date=audit.audit_retest_statement_backup_complete_date,
                statement_overview_complete_date=audit.audit_retest_statement_overview_complete_date,
                statement_website_complete_date=audit.audit_retest_statement_website_complete_date,
                statement_compliance_complete_date=audit.audit_retest_statement_compliance_complete_date,
                statement_non_accessible_complete_date=audit.audit_retest_statement_non_accessible_complete_date,
                statement_preparation_complete_date=audit.audit_retest_statement_preparation_complete_date,
                statement_feedback_complete_date=audit.audit_retest_statement_feedback_complete_date,
                statement_disproportionate_complete_date=audit.audit_retest_statement_disproportionate_complete_date,
                statement_custom_complete_date=audit.audit_retest_statement_custom_complete_date,
                disproportionate_burden_claim=audit.twelve_week_disproportionate_burden_claim,
                disproportionate_burden_notes=audit.twelve_week_disproportionate_burden_notes,
                disproportionate_burden_complete_date=audit.twelve_week_disproportionate_burden_complete_date,
                compliance_complete_date=audit.audit_retest_statement_decision_complete_date,
                summary_complete_date=audit.audit_retest_statement_summary_complete_date,
            )

        for page in Page.objects.filter(audit=audit):
            page.wcag_audit = wcag_audit_initial
            page.save()
            if wcag_audit_1 is not None:
                url = page.updated_url if page.updated_url else page.url
                location = (
                    page.updated_location if page.updated_location else page.location
                )
                page_retest = Page.objects.create(
                    audit=audit,
                    wcag_audit=wcag_audit_1,
                    page_type=page.page_type,
                    name=page.name,
                    url=url,
                    location=location,
                    complete_date=page.retest_complete_date,
                    no_errors_date=page.no_errors_date,
                    not_found=page.not_found,
                    is_contact_page=page.is_contact_page,
                    retest_page_missing_date=page.retest_page_missing_date,
                    retest_notes=page.retest_notes,
                    updated=page.updated,
                )
                for check_result in CheckResult.objects.filter(page=page):
                    CheckResult.objects.create(
                        audit=check_result.audit,
                        page=page_retest,
                        id_within_case=check_result.id_within_case,
                        issue_identifier=check_result.issue_identifier,
                        is_deleted=check_result.is_deleted,
                        type=check_result.type,
                        wcag_definition=check_result.wcag_definition,
                        check_result_state=check_result.retest_state,
                        notes=check_result.retest_notes,
                        updated=check_result.updated,
                    )


def reverse_code(apps, schema_editor):
    WcagAudit = apps.get_model("audits", "WCAGAudit")
    StatementAudit = apps.get_model("audits", "StatementAudit")
    Page = apps.get_model("audits", "Page")
    CheckResult = apps.get_model("audits", "CheckResult")
    for wcag_audit in WcagAudit.objects.filter(audit_round_type=TWELVE_WEEK_ROUND_TYPE):
        twelve_week_pages = Page.objects.filter(wcag_audit=wcag_audit)
        for page in twelve_week_pages:
            CheckResult.objects.filter(page=page).delete()
        twelve_week_pages.delete()
    Page.objects.all().update(wcag_audit=None)
    wcag_audits = WcagAudit.objects.all()
    wcag_audits._raw_delete(wcag_audits.db)
    StatementAudit.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0025_statementaudit_wcagaudit_page_wcag_audit"),
    ]

    operations = [
        migrations.RunPython(populate_audit_rounds, reverse_code=reverse_code),
    ]
