# Generated by Django 6.0.3 on 2026-04-08 08:19

from datetime import datetime, timezone
from unittest.mock import Mock, patch

from django.db import migrations

INITIAL_ROUND_TYPE: str = "initial"
TWELVE_WEEK_ROUND_TYPE = "12-week"
EQUALITY_BODY_ROUND_TYPE = "equality-body"
INITIAL_ROUND_NUMBER: int = 0
TWELVE_WEEK_ROUND_NUMBER: int = 1


def populate_audit_rounds(apps, schema_editor):
    Audit = apps.get_model("audits", "Audit")
    AuditOverview = apps.get_model("audits", "AuditOverview")
    WcagAudit = apps.get_model("audits", "WCAGAudit")
    StatementAudit = apps.get_model("audits", "StatementAudit")
    Page = apps.get_model("audits", "Page")
    WcagPageInitial = apps.get_model("audits", "WcagPageInitial")
    WcagPageRetest = apps.get_model("audits", "WcagPageRetest")
    CheckResult = apps.get_model("audits", "CheckResult")
    CheckResultNotesHistory = apps.get_model("audits", "CheckResultNotesHistory")
    WcagCheckResultInitial = apps.get_model("audits", "WcagCheckResultInitial")
    WcagCheckResultInitialNotesHistory = apps.get_model(
        "audits", "WcagCheckResultInitialNotesHistory"
    )
    StatementPage = apps.get_model("audits", "StatementPage")
    StatementCheckResult = apps.get_model("audits", "StatementCheckResult")
    StatementCheckResultRound = apps.get_model("audits", "StatementCheckResultRound")
    Retest = apps.get_model("audits", "Retest")
    RetestPage = apps.get_model("audits", "RetestPage")
    WcagPageRetest = apps.get_model("audits", "WcagPageRetest")
    RetestCheckResult = apps.get_model("audits", "RetestCheckResult")
    CheckResultRetestNotesHistory = apps.get_model(
        "audits", "CheckResultRetestNotesHistory"
    )
    WcagCheckResultRetest = apps.get_model("audits", "WcagCheckResultRetest")
    WcagCheckResultRetestNotesHistory = apps.get_model(
        "audits", "WcagCheckResultRetestNotesHistory"
    )
    RetestStatementCheckResult = apps.get_model("audits", "RetestStatementCheckResult")
    for audit in Audit.objects.all().order_by("id"):
        audit_overview = AuditOverview.objects.create(
            simplified_case=audit.simplified_case,
            published_report_data_updated_time=audit.published_report_data_updated_time,
            updated=audit.updated,
        )
        notes: str = (
            f"Exemptions note:\n\n{audit.exemptions_notes.strip()}"
            if audit.exemptions_notes
            else ""
        )
        wcag_audit_initial = WcagAudit.objects.create(
            simplified_case=audit.simplified_case,
            audit_round_type=INITIAL_ROUND_TYPE,
            round_number=INITIAL_ROUND_NUMBER,
            updated=audit.updated,
            date_of_test=audit.date_of_test,
            screen_size=audit.screen_size,
            exemptions_state=audit.exemptions_state,
            notes=notes,
            metadata_complete_date=audit.audit_metadata_complete_date,
            pages_complete_date=audit.audit_pages_complete_date,
            compliance_state=audit.simplified_case.compliance.website_compliance_state_initial,
            compliance_notes=audit.simplified_case.compliance.website_compliance_notes_initial,
            compliance_decision_complete_date=audit.audit_website_decision_complete_date,
            summary_complete_date=audit.audit_wcag_summary_complete_date,
        )
        statement_audit_initial = StatementAudit.objects.create(
            simplified_case=audit.simplified_case,
            audit_round_type=INITIAL_ROUND_TYPE,
            round_number=INITIAL_ROUND_NUMBER,
            updated=audit.updated,
            date_of_test=audit.date_of_test,
            pages_complete_date=audit.audit_statement_pages_complete_date,
            backup_complete_date=audit.audit_initial_statement_backup_complete_date,
            statement_extra_report_text=audit.statement_extra_report_text,
            statement_overview_complete_date=audit.audit_statement_overview_complete_date,
            statement_website_complete_date=audit.audit_statement_website_complete_date,
            statement_compliance_complete_date=audit.audit_statement_compliance_complete_date,
            statement_non_accessible_complete_date=audit.audit_statement_non_accessible_complete_date,
            statement_preparation_complete_date=audit.audit_statement_preparation_complete_date,
            statement_feedback_complete_date=audit.audit_statement_feedback_complete_date,
            statement_disproportionate_complete_date=audit.audit_statement_disproportionate_complete_date,
            statement_custom_complete_date=audit.audit_statement_custom_complete_date,
            disproportionate_burden_claim=audit.initial_disproportionate_burden_claim,
            disproportionate_burden_notes=audit.initial_disproportionate_burden_notes,
            disproportionate_burden_complete_date=audit.initial_disproportionate_burden_complete_date,
            compliance_state=audit.simplified_case.compliance.statement_compliance_state_initial,
            compliance_notes=audit.simplified_case.compliance.statement_compliance_notes_initial,
            compliance_complete_date=audit.audit_statement_decision_complete_date,
            summary_complete_date=audit.audit_statement_summary_complete_date,
        )
        wcag_audit_12_week = None
        if audit.retest_date:
            wcag_audit_12_week = WcagAudit.objects.create(
                simplified_case=audit.simplified_case,
                audit_round_type=TWELVE_WEEK_ROUND_TYPE,
                round_number=TWELVE_WEEK_ROUND_NUMBER,
                updated=audit.updated,
                date_of_test=audit.retest_date,
                notes=audit.audit_retest_metadata_notes,
                metadata_complete_date=audit.audit_retest_metadata_complete_date,
                pages_complete_date=audit.audit_retest_pages_complete_date,
                compliance_state=audit.simplified_case.compliance.website_compliance_state_12_week,
                compliance_notes=audit.simplified_case.compliance.website_compliance_notes_12_week,
                compliance_decision_complete_date=audit.audit_retest_website_decision_complete_date,
                summary_complete_date=audit.audit_retest_wcag_summary_complete_date,
            )
            statement_audit_12_week = StatementAudit.objects.create(
                simplified_case=audit.simplified_case,
                audit_round_type=TWELVE_WEEK_ROUND_TYPE,
                round_number=TWELVE_WEEK_ROUND_NUMBER,
                updated=audit.updated,
                date_of_test=audit.retest_date,
                pages_complete_date=audit.audit_retest_statement_pages_complete_date,
                backup_complete_date=audit.audit_retest_statement_backup_complete_date,
                statement_overview_complete_date=audit.audit_retest_statement_overview_complete_date,
                statement_website_complete_date=audit.audit_retest_statement_website_complete_date,
                statement_compliance_complete_date=audit.audit_retest_statement_compliance_complete_date,
                statement_non_accessible_complete_date=audit.audit_retest_statement_non_accessible_complete_date,
                statement_preparation_complete_date=audit.audit_retest_statement_preparation_complete_date,
                statement_feedback_complete_date=audit.audit_retest_statement_feedback_complete_date,
                statement_disproportionate_complete_date=audit.audit_retest_statement_disproportionate_complete_date,
                statement_custom_complete_date=audit.audit_retest_statement_custom_complete_date,
                disproportionate_burden_claim=audit.twelve_week_disproportionate_burden_claim,
                disproportionate_burden_notes=audit.twelve_week_disproportionate_burden_notes,
                disproportionate_burden_complete_date=audit.twelve_week_disproportionate_burden_complete_date,
                compliance_state=audit.simplified_case.compliance.statement_compliance_state_12_week,
                compliance_notes=audit.simplified_case.compliance.statement_compliance_notes_12_week,
                compliance_complete_date=audit.audit_retest_statement_decision_complete_date,
                summary_complete_date=audit.audit_retest_statement_summary_complete_date,
            )

        wcag_page_initials_by_page = {}
        wcag_check_result_initials_by_page_and_wcag = {}
        for page in Page.objects.filter(audit=audit):
            wcag_page_initial = WcagPageInitial.objects.create(
                wcag_audit=wcag_audit_initial,
                is_deleted=page.is_deleted,
                page_type=page.page_type,
                name=page.name,
                url=page.url,
                location=page.location,
                not_found=page.not_found,
                is_contact_page=page.is_contact_page,
                no_errors_date=page.no_errors_date,
                complete_date=page.complete_date,
                updated=page.updated,
            )
            wcag_page_initials_by_page[page.id] = wcag_page_initial
            wcag_page_retest = None
            if wcag_audit_12_week is not None:
                url = page.updated_url if page.updated_url else page.url
                location = (
                    page.updated_location if page.updated_location else page.location
                )
                notes = page.retest_notes if page.retest_notes else ""
                if url or location or notes:
                    wcag_page_retest = WcagPageRetest.objects.create(
                        wcag_audit=wcag_audit_12_week,
                        wcag_page_initial=wcag_page_initial,
                        is_deleted=page.is_deleted,
                        url=url,
                        location=location,
                        notes=notes,
                        complete_date=page.complete_date,
                        no_errors_date=page.no_errors_date,
                        page_missing_date=page.retest_page_missing_date,
                        updated=page.updated,
                    )
            for check_result in CheckResult.objects.filter(page=page):
                wcag_check_result_initial = WcagCheckResultInitial.objects.create(
                    wcag_audit=wcag_audit_initial,
                    wcag_page_initial=wcag_page_initial,
                    issue_identifier=check_result.issue_identifier,
                    is_deleted=check_result.is_deleted,
                    type=check_result.type,
                    wcag_definition=check_result.wcag_definition,
                    check_result_state=check_result.check_result_state,
                    notes=check_result.notes,
                    updated=check_result.updated,
                )
                wcag_check_result_initials_by_page_and_wcag[
                    f"{page.id}-{check_result.wcag_definition.id}"
                ] = wcag_check_result_initial
                if wcag_audit_12_week is not None and wcag_page_retest is not None:
                    # if check_result.retest_state != "not-retested" or check_result.retest_notes != "":
                    wcag_check_result_retest = WcagCheckResultRetest.objects.create(
                        wcag_audit=wcag_audit_12_week,
                        wcag_page_retest=wcag_page_retest,
                        wcag_check_result_initial=wcag_check_result_initial,
                        wcag_definition=check_result.wcag_definition,
                        is_deleted=check_result.is_deleted,
                        retest_state=check_result.retest_state,
                        notes=check_result.retest_notes,
                        updated=check_result.updated,
                    )
                else:
                    wcag_check_result_retest = None
                for (
                    check_result_notes_history
                ) in CheckResultNotesHistory.objects.filter(check_result=check_result):
                    with patch(
                        "django.utils.timezone.now",
                        Mock(return_value=check_result_notes_history.created),
                    ):
                        WcagCheckResultInitialNotesHistory.objects.create(
                            wcag_check_result_initial=wcag_check_result_initial,
                            notes=check_result_notes_history.notes,
                            created_by=check_result_notes_history.created_by,
                        )
                for (
                    check_result_retest_notes_history
                ) in CheckResultRetestNotesHistory.objects.filter(
                    check_result=check_result
                ):
                    with patch(
                        "django.utils.timezone.now",
                        Mock(return_value=check_result_retest_notes_history.created),
                    ):
                        WcagCheckResultRetestNotesHistory.objects.create(
                            wcag_check_result_retest=wcag_check_result_retest,
                            retest_state=check_result_retest_notes_history.retest_state,
                            notes=check_result_retest_notes_history.retest_notes,
                            created_by=check_result_retest_notes_history.created_by,
                        )

        statement_check_results_initial_by_statement_check = {}
        for statement_check_result in StatementCheckResult.objects.filter(audit=audit):
            statement_check_result.statement_audit = statement_audit_initial
            statement_check_result.save()
            statement_check_result_initial = StatementCheckResultRound.objects.create(
                statement_audit=statement_audit_initial,
                statement_check=statement_check_result.statement_check,
                issue_identifier=statement_check_result.issue_identifier,
                type=statement_check_result.type,
                check_result_state=statement_check_result.check_result_state,
                public_comment=statement_check_result.report_comment,
                auditor_information=statement_check_result.auditor_notes,
                is_deleted=statement_check_result.is_deleted,
            )
            statement_check_results_initial_by_statement_check[
                statement_check_result.statement_check
            ] = statement_check_result_initial
            if statement_audit_12_week is not None:
                StatementCheckResultRound.objects.create(
                    statement_audit=statement_audit_12_week,
                    statement_check_result_initial=statement_check_result_initial,
                    statement_check=statement_check_result.statement_check,
                    type="retest-custom",
                    issue_identifier=statement_check_result.issue_identifier,
                    check_result_state=statement_check_result.retest_state,
                    public_comment=statement_check_result.retest_comment,
                    auditor_information=statement_check_result.auditor_notes,
                    is_deleted=statement_check_result.is_deleted,
                )

        for retest in Retest.objects.filter(
            simplified_case=audit.simplified_case
        ).order_by("id"):
            round_number: int = WcagAudit.objects.filter(
                simplified_case=retest.simplified_case
            ).count()
            updated: datetime = datetime(
                retest.date_of_retest.year,
                retest.date_of_retest.month,
                retest.date_of_retest.day,
                tzinfo=timezone.utc,
            )
            wcag_audit_retest = WcagAudit.objects.create(
                simplified_case=retest.simplified_case,
                audit_round_type=EQUALITY_BODY_ROUND_TYPE,
                round_number=round_number,
                updated=updated,
                date_of_test=retest.date_of_retest,
                notes=retest.retest_notes,
                metadata_complete_date=retest.complete_date,
                compliance_state=retest.retest_compliance_state,
                compliance_notes=retest.compliance_notes,
                compliance_decision_complete_date=retest.compliance_complete_date,
                summary_complete_date=retest.comparison_complete_date,
            )
            round_number: int = StatementAudit.objects.filter(
                simplified_case=retest.simplified_case
            ).count()
            statement_audit_retest = StatementAudit.objects.create(
                simplified_case=retest.simplified_case,
                audit_round_type=EQUALITY_BODY_ROUND_TYPE,
                round_number=round_number,
                updated=updated,
                date_of_test=retest.date_of_retest,
                notes=retest.retest_notes,
                pages_complete_date=retest.statement_pages_complete_date,
                backup_complete_date=retest.statement_backup_complete_date,
                statement_overview_complete_date=retest.statement_overview_complete_date,
                statement_website_complete_date=retest.statement_website_complete_date,
                statement_compliance_complete_date=retest.statement_compliance_complete_date,
                statement_non_accessible_complete_date=retest.statement_non_accessible_complete_date,
                statement_preparation_complete_date=retest.statement_preparation_complete_date,
                statement_feedback_complete_date=retest.statement_feedback_complete_date,
                statement_disproportionate_complete_date=retest.statement_disproportionate_complete_date,
                statement_custom_complete_date=retest.statement_custom_complete_date,
                disproportionate_burden_claim=retest.disproportionate_burden_claim,
                disproportionate_burden_notes=retest.disproportionate_burden_notes,
                disproportionate_burden_complete_date=retest.disproportionate_burden_complete_date,
                compliance_state=retest.statement_compliance_state,
                compliance_notes=retest.statement_compliance_notes,
                compliance_complete_date=retest.statement_decision_complete_date,
                summary_complete_date=retest.statement_results_complete_date,
            )

            for retest_page in RetestPage.objects.filter(retest=retest).order_by("id"):
                url: str = (
                    retest_page.page.updated_url
                    if retest_page.page.updated_url
                    else retest_page.page.url
                )
                location: str = (
                    retest_page.page.updated_location
                    if retest_page.page.updated_location
                    else retest_page.page.location
                )
                wcag_page_initial = wcag_page_initials_by_page[retest_page.page_id]
                wcag_page_retest = WcagPageRetest.objects.create(
                    wcag_audit=wcag_audit_retest,
                    wcag_page_initial=wcag_page_initial,
                    url=url,
                    location=location,
                    complete_date=retest_page.complete_date,
                    notes=retest_page.additional_issues_notes,
                    page_missing_date=retest_page.missing_date,
                )

                for retest_check_result in RetestCheckResult.objects.filter(
                    retest_page=retest_page
                ).order_by("id"):
                    WcagCheckResultRetest.objects.create(
                        wcag_audit=wcag_audit_retest,
                        wcag_page_retest=wcag_page_retest,
                        wcag_check_result_initial=wcag_check_result_initials_by_page_and_wcag[
                            f"{retest_check_result.retest_page.page.id}-{retest_check_result.check_result.wcag_definition.id}"
                        ],
                        wcag_definition=retest_check_result.check_result.wcag_definition,
                        retest_state=retest_check_result.retest_state,
                        notes=retest_check_result.retest_notes,
                        is_deleted=retest_check_result.is_deleted,
                    )

            for (
                retest_statement_check_result
            ) in RetestStatementCheckResult.objects.filter(retest=retest).order_by(
                "id"
            ):
                StatementCheckResultRound.objects.create(
                    statement_audit=statement_audit_retest,
                    statement_check_result_initial=statement_check_results_initial_by_statement_check.get(
                        retest_statement_check_result.statement_check
                    ),
                    statement_check=retest_statement_check_result.statement_check,
                    type="retest-custom",
                    issue_identifier=retest_statement_check_result.issue_identifier,
                    check_result_state=retest_statement_check_result.check_result_state,
                    public_comment=retest_statement_check_result.comment,
                    is_deleted=retest_statement_check_result.is_deleted,
                )

        for statement_page in StatementPage.objects.filter(audit=audit):
            statement_page.simplified_case = statement_audit_initial.simplified_case
            statement_page.audit_overview = audit_overview
            statement_page.save()


def reverse_code(apps, schema_editor):
    AuditOverview = apps.get_model("audits", "AuditOverview")
    WcagAudit = apps.get_model("audits", "WCAGAudit")
    StatementAudit = apps.get_model("audits", "StatementAudit")
    StatementPage = apps.get_model("audits", "StatementPage")
    StatementCheckResultRound = apps.get_model("audits", "StatementCheckResultRound")
    WcagPageInitial = apps.get_model("audits", "WcagPageInitial")
    WcagPageRetest = apps.get_model("audits", "WcagPageRetest")
    WcagCheckResultInitial = apps.get_model("audits", "WcagCheckResultInitial")
    WcagCheckResultInitialNotesHistory = apps.get_model(
        "audits", "WcagCheckResultInitialNotesHistory"
    )
    WcagCheckResultRetestNotesHistory = apps.get_model(
        "audits", "WcagCheckResultRetestNotesHistory"
    )
    WcagCheckResultRetest = apps.get_model("audits", "WcagCheckResultRetest")
    WcagCheckResultInitialNotesHistory.objects.all().delete()
    WcagCheckResultRetestNotesHistory.objects.all().delete()
    WcagCheckResultRetest.objects.all().delete()
    WcagCheckResultInitial.objects.all().delete()
    WcagPageRetest.objects.all().delete()
    WcagPageInitial.objects.all().delete()
    WcagAudit.objects.all().delete()
    StatementCheckResultRound.objects.all().update(statement_check_result_initial=None)
    StatementCheckResultRound.objects.all().delete()
    StatementPage.objects.all().update(audit_overview=None)
    StatementAudit.objects.all().delete()
    AuditOverview.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "audits",
            "0025_statementpage_simplified_case_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_audit_rounds, reverse_code=reverse_code),
    ]
