# Generated by Django 4.1.7 on 2023-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0026_populate_statement_checks"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_statement_compliance_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_statement_enforcement_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_statement_feedback_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_statement_non_accessible_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_statement_other_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_statement_overview_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_statement_preparation_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_statement_website_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
