# Generated by Django 6.0.7 on 2026-08-18 15:07

from django.db import migrations
from django.utils import timezone

S2558_INITIAL_STATEMENT_AUDIT_ID: int = 14010


def create_statement_checks(apps, schema_editor):
    StatementAudit = apps.get_model("audits", "StatementAudit")
    StatementCheck = apps.get_model("audits", "StatementCheck")
    StatementCheckResult = apps.get_model("audits", "StatementCheckResult")
    statement_audit = StatementAudit.objects.filter(
        id=S2558_INITIAL_STATEMENT_AUDIT_ID
    ).first()
    if statement_audit is not None:
        case_number: int = statement_audit.simplified_case.case_number
        for statement_check in (
            StatementCheck.objects.all()
            .exclude(date_start__gt=statement_audit.date_of_test)
            .exclude(date_end__lt=statement_audit.date_of_test)
        ):
            issue_number: int = statement_check.issue_number
            issue_identifier = f"{case_number}-S-{issue_number}"
            StatementCheckResult.objects.create(
                statement_audit_id=S2558_INITIAL_STATEMENT_AUDIT_ID,
                type=statement_check.type,
                statement_check_id=statement_check.id,
                issue_identifier=issue_identifier,
                updated=timezone.now(),
            )


def reverse_code(apps, schema_editor):
    StatementCheckResult = apps.get_model("audits", "StatementCheckResult")
    StatementCheckResult.objects.filter(
        statement_audit_id=S2558_INITIAL_STATEMENT_AUDIT_ID
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0026_populate_audit_rounds"),
    ]

    operations = [
        migrations.RunPython(create_statement_checks, reverse_code=reverse_code),
    ]
