# Generated by Django 4.1.7 on 2023-04-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0027_populate_statement_checks"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_compliance_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_enforcement_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_feedback_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_non_accessible_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_other_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_overview_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_preparation_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="audit_retest_statement_website_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statementcheckresult",
            name="retest_check_result",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("not-tested", "Not tested")],
                default="not-tested",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="statementcheckresult",
            name="retest_comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
