# Generated by Django 4.1.7 on 2023-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "audits",
            "0027_audit_accessibility_statement_deadline_not_complete_wording_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="accessibility_statement_report_text_wording",
            field=models.TextField(blank=True, default=""),
        ),
    ]
