# Generated by Django 6.1.1 on 2026-09-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0028_remove_bad_retest_results"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statementcheckresult",
            name="audit",
        ),
        migrations.RemoveField(
            model_name="statementpage",
            name="audit",
        ),
        migrations.RemoveField(
            model_name="statementpage",
            name="simplified_case",
        ),
        migrations.AlterField(
            model_name="statementcheckresult",
            name="statement_audit",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="audits.statementaudit",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="statementpage",
            name="audit_overview",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="audits.auditoverview",
            ),
            preserve_default=False,
        ),
    ]
