# Generated by Django 4.1.7 on 2023-06-22 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0030_populate_statement_checks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statementcheckresult",
            options={"ordering": ["statement_check__position", "id"]},
        ),
    ]
