# Generated by Django 4.2.4 on 2023-10-20 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0068_remove_case_report_methodology"),
        (
            "audits",
            "0032_rename_access_requirements_notes_audit_archive_access_requirements_notes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Retest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("id_within_case", models.IntegerField(blank=True, default=1)),
                ("date_of_retest", models.DateField(default=datetime.date.today)),
                ("retest_notes", models.TextField(blank=True, default="")),
                (
                    "retest_compliance_state",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("partially-compliant", "Partially compliant"),
                            ("not-known", "Not known"),
                        ],
                        default="not-known",
                        max_length=20,
                    ),
                ),
                ("compliance_notes", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("complete_date", models.DateField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cases.case"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RetestPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("missing_date", models.DateField(blank=True, null=True)),
                ("complete_date", models.DateField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="audits.page"
                    ),
                ),
                (
                    "retest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="audits.retest"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RetestCheckResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "retest_state",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("not-fixed", "Not fixed"),
                            ("not-retested", "Not retested"),
                        ],
                        default="not-retested",
                        max_length=20,
                    ),
                ),
                ("retest_notes", models.TextField(blank=True, default="")),
                ("updated", models.DateTimeField(blank=True, null=True)),
                (
                    "check_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.checkresult",
                    ),
                ),
                (
                    "retest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="audits.retest"
                    ),
                ),
                (
                    "retest_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="audits.retestpage",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
