# Generated by Django 4.2.4 on 2023-10-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0033_retest_retestpage_retestcheckresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="retest",
            name="comparison_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
