# Generated by Django 4.2.4 on 2023-11-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0033_retest_alter_audit_screen_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="statement_extra_report_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
