# Generated by Django 4.2.8 on 2023-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0034_audit_statement_extra_report_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statementcheck",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="statementcheck",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statementcheck",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wcagdefinition",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wcagdefinition",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
