# Generated by Django 4.2.4 on 2023-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0034_retest_comparison_complete_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retest",
            options={"ordering": ["case_id", "-id_within_case"]},
        ),
        migrations.AlterField(
            model_name="audit",
            name="screen_size",
            field=models.CharField(
                choices=[("15in", "15 inch"), ("14in", "14 inch"), ("13in", "13 inch")],
                default="15in",
                max_length=20,
            ),
        ),
    ]
