# Generated by Django 4.2.4 on 2023-11-01 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0034_retest_comparison_complete_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retest",
            options={"ordering": ["case_id", "-id_within_case"]},
        ),
    ]
