# Generated by Django 4.2.8 on 2024-01-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0037_remove_statementcheck_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retestpage",
            name="additional_issues_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
