# Generated by Django 4.2.8 on 2024-01-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0039_wcagdefinition_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="initial_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="initial_disproportionate_burden_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="initial_disproportionate_burden_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="audit",
            name="twelve_week_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="twelve_week_disproportionate_burden_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="twelve_week_disproportionate_burden_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
