# Generated by Django 5.0.4 on 2024-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "audits",
            "0043_alter_audit_archive_audit_retest_disproportionate_burden_state_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="retest",
            name="statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("unknown", "Not assessed or no statement"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
    ]
