"""
URLS for cases
"""

from django.contrib.auth.decorators import login_required
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import (
    CaseCloseUpdateView,
    CaseRecommendationUpdateView,
    CaseSearchView,
    CaseZendeskTicketsDetailView,
    ContactCreateView,
    ContactInformationRequestUpdateView,
    ContactUpdateView,
    CorrespondenceReportAcknowledgedUpdateView,
    CorrespondenceReportSentUpdateView,
    CorrespondenceTwelveWeekDeadlineUpdateView,
    CorrespondenceTwelveWeekReceivedUpdateView,
    CorrespondenceTwelveWeekRequestUpdateView,
    EnforcementBodyMetadataUpdateView,
    FinalReportUpdateView,
    InitialTestAndroidDetailsUpdateView,
    InitialTestAndroidOutcomeUpdateView,
    InitialTestAuditorUpdateView,
    InitialTestiOSDetailsUpdateView,
    InitialTestiOSOutcomeUpdateView,
    ManageContactDetailsUpdateView,
    MobileCaseCreateView,
    MobileCaseDetailView,
    MobileCaseHistoryDetailView,
    MobileCaseMetadataUpdateView,
    MobileCaseNoteCreateView,
    MobileCaseNoteUpdateView,
    MobileCaseStatusUpdateView,
    QAApprovalUpdateView,
    QAAuditorUpdateView,
    QACommentsUpdateView,
    ReportReadyForQAUpdateView,
    RetestAndroidComplianceDecisionsUpdateView,
    RetestAndroidResultUpdateView,
    RetestiOSComplianceDecisionsUpdateView,
    RetestiOSResultUpdateView,
    StatementEnforcementUpdateView,
    UnresponsivePSBUpdateView,
    ZendeskTicketConfirmDeleteUpdateView,
    ZendeskTicketCreateView,
    ZendeskTicketUpdateView,
    export_equality_body_cases,
    export_feedback_survey_cases,
    export_mobile_cases,
    mark_qa_comments_as_read,
)

app_name: str = "mobile"
urlpatterns: list[URLPattern] = [
    path(
        "create/",
        login_required(MobileCaseCreateView.as_view()),
        name="case-create",
    ),
    path(
        "export-as-csv/", login_required(export_mobile_cases), name="case-export-list"
    ),
    path(
        "export-feedback-survey-cases-csv/",
        login_required(export_feedback_survey_cases),
        name="export-feedback-survey-cases",
    ),
    path(
        "export-equality-body-cases-csv/",
        login_required(export_equality_body_cases),
        name="export-equality-body-cases",
    ),
    path(
        "<int:pk>/case-detail/",
        login_required(MobileCaseDetailView.as_view()),
        name="case-detail",
    ),
    path(
        "<int:pk>/case-view-and-search/",
        login_required(CaseSearchView.as_view()),
        name="case-view-and-search",
    ),
    path(
        "<int:pk>/case-metadata/",
        login_required(MobileCaseMetadataUpdateView.as_view()),
        name="edit-case-metadata",
    ),
    path(
        "<int:pk>/case-status/",
        login_required(MobileCaseStatusUpdateView.as_view()),
        name="edit-case-status",
    ),
    path(
        "<int:case_id>/create-case-note/",
        login_required(MobileCaseNoteCreateView.as_view()),
        name="create-case-note",
    ),
    path(
        "notes/<int:pk>/edit-case-note/",
        login_required(MobileCaseNoteUpdateView.as_view()),
        name="edit-case-note",
    ),
    path(
        "<int:pk>/manage-contact-details/",
        login_required(ManageContactDetailsUpdateView.as_view()),
        name="manage-contact-details",
    ),
    path(
        "<int:case_id>/edit-contact-create/",
        login_required(ContactCreateView.as_view()),
        name="edit-contact-create",
    ),
    path(
        "<int:pk>/edit-contact-update/",
        login_required(ContactUpdateView.as_view()),
        name="edit-contact-update",
    ),
    path(
        "<int:pk>/edit-request-contact-details/",
        login_required(ContactInformationRequestUpdateView.as_view()),
        name="edit-request-contact-details",
    ),
    path(
        "<int:pk>/edit-initial-test-auditor/",
        login_required(InitialTestAuditorUpdateView.as_view()),
        name="edit-initial-test-auditor",
    ),
    path(
        "<int:pk>/edit-initial-test-ios-details/",
        login_required(InitialTestiOSDetailsUpdateView.as_view()),
        name="edit-initial-test-ios-details",
    ),
    path(
        "<int:pk>/edit-initial-test-ios-outcome/",
        login_required(InitialTestiOSOutcomeUpdateView.as_view()),
        name="edit-initial-test-ios-outcome",
    ),
    path(
        "<int:pk>/edit-initial-test-android-details/",
        login_required(InitialTestAndroidDetailsUpdateView.as_view()),
        name="edit-initial-test-android-details",
    ),
    path(
        "<int:pk>/edit-initial-test-android-outcome/",
        login_required(InitialTestAndroidOutcomeUpdateView.as_view()),
        name="edit-initial-test-android-outcome",
    ),
    path(
        "<int:pk>/edit-report-ready-for-qa/",
        login_required(ReportReadyForQAUpdateView.as_view()),
        name="edit-report-ready-for-qa",
    ),
    path(
        "<int:pk>/edit-qa-auditor/",
        login_required(QAAuditorUpdateView.as_view()),
        name="edit-qa-auditor",
    ),
    path(
        "<int:pk>/edit-qa-comments/",
        login_required(QACommentsUpdateView.as_view()),
        name="edit-qa-comments",
    ),
    path(
        "<int:pk>/mark-qa-comments-as-read/",
        login_required(mark_qa_comments_as_read),
        name="mark-qa-comments-as-read",
    ),
    path(
        "<int:pk>/edit-qa-approval/",
        login_required(QAApprovalUpdateView.as_view()),
        name="edit-qa-approval",
    ),
    path(
        "<int:pk>/edit-final-report/",
        login_required(FinalReportUpdateView.as_view()),
        name="edit-final-report",
    ),
    path(
        "<int:pk>/edit-report-sent/",
        login_required(CorrespondenceReportSentUpdateView.as_view()),
        name="edit-report-sent",
    ),
    path(
        "<int:pk>/edit-report-acknowledged/",
        login_required(CorrespondenceReportAcknowledgedUpdateView.as_view()),
        name="edit-report-acknowledged",
    ),
    path(
        "<int:pk>/edit-12-week-deadline/",
        login_required(CorrespondenceTwelveWeekDeadlineUpdateView.as_view()),
        name="edit-12-week-deadline",
    ),
    path(
        "<int:pk>/edit-12-week-request-update/",
        login_required(CorrespondenceTwelveWeekRequestUpdateView.as_view()),
        name="edit-12-week-request-update",
    ),
    path(
        "<int:pk>/edit-12-week-received/",
        login_required(CorrespondenceTwelveWeekReceivedUpdateView.as_view()),
        name="edit-12-week-received",
    ),
    path(
        "<int:pk>/edit-retest-ios-result/",
        login_required(RetestiOSResultUpdateView.as_view()),
        name="edit-retest-ios-result",
    ),
    path(
        "<int:pk>/edit-retest-ios-compliance-decisions/",
        login_required(RetestiOSComplianceDecisionsUpdateView.as_view()),
        name="edit-retest-ios-compliance-decisions",
    ),
    path(
        "<int:pk>/edit-retest-android-result/",
        login_required(RetestAndroidResultUpdateView.as_view()),
        name="edit-retest-android-result",
    ),
    path(
        "<int:pk>/edit-retest-android-compliance-decisions/",
        login_required(RetestAndroidComplianceDecisionsUpdateView.as_view()),
        name="edit-retest-android-compliance-decisions",
    ),
    path(
        "<int:pk>/edit-case-recommendation/",
        login_required(CaseRecommendationUpdateView.as_view()),
        name="edit-case-recommendation",
    ),
    path(
        "<int:pk>/edit-case-close/",
        login_required(CaseCloseUpdateView.as_view()),
        name="edit-case-close",
    ),
    path(
        "<int:pk>/edit-statement-enforcement/",
        login_required(StatementEnforcementUpdateView.as_view()),
        name="edit-statement-enforcement",
    ),
    path(
        "<int:pk>/edit-equality-body-metadata/",
        login_required(EnforcementBodyMetadataUpdateView.as_view()),
        name="edit-equality-body-metadata",
    ),
    path(
        "<int:pk>/zendesk-tickets/",
        login_required(CaseZendeskTicketsDetailView.as_view()),
        name="zendesk-tickets",
    ),
    path(
        "<int:case_id>/create-zendesk-ticket/",
        login_required(ZendeskTicketCreateView.as_view()),
        name="create-zendesk-ticket",
    ),
    path(
        "<int:pk>/update-zendesk-ticket/",
        login_required(ZendeskTicketUpdateView.as_view()),
        name="update-zendesk-ticket",
    ),
    path(
        "<int:pk>/confirm-delete-zendesk-ticket/",
        login_required(ZendeskTicketConfirmDeleteUpdateView.as_view()),
        name="confirm-delete-zendesk-ticket",
    ),
    path(
        "<int:pk>/edit-unresponsive-psb/",
        login_required(UnresponsivePSBUpdateView.as_view()),
        name="edit-unresponsive-psb",
    ),
    path(
        "<int:pk>/history/",
        login_required(MobileCaseHistoryDetailView.as_view()),
        name="case-history",
    ),
]
