Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.

Resources:
  reportstorageBucket:
    Metadata:
      'aws:copilot:description': 'An Amazon S3 bucket, report-storage, for storing and retrieving objects'
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  reportstorageBucketPolicy:
    Metadata:
      'aws:copilot:description': 'A bucket policy to deny unencrypted access to the bucket and its contents'
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ForceHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: 
              - !Sub ${ reportstorageBucket.Arn}/*
              - !Sub ${ reportstorageBucket.Arn}
            Condition: 
              Bool:
                "aws:SecureTransport": false
      Bucket: !Ref reportstorageBucket

Outputs:
  reportstorageName:
    Description: "The name of a user-defined bucket."
    Value: !Ref reportstorageBucket
    Export:
      Name: !Sub ${App}-${Env}-reportstorageBucketName
  reportstorageBucketARN:
    Description: "The ARN of the report-storage bucket."
    Value: !GetAtt reportstorageBucket.Arn
    Export:
      Name: !Sub ${App}-${Env}-reportstorageBucketARN