version: "3.7"
services:
    db:
        image: postgres:12.2
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5433:5433"
        command: -p 5433

    web:
        image: "django_amp_two:latest"
        command: >
            bash -c "
            sleep 5;
            psql postgres://admin:secret@db:5433/postgres -c \"create database accessibility_monitoring_app;\";
            psql postgres://admin:secret@db:5433/postgres -c \"create database a11ymon;\";
            export PGPASSWORD='secret'; pg_restore --no-privileges --no-owner -h db -p 5433 -U admin -d a11ymon -1 ./data/s3_files/pubsecweb_210216.pgadmin-backup;
            psql -h db -p 5433 -U admin -d a11ymon -c \"ALTER SCHEMA a11ymon_mini RENAME TO a11ymon\";
            psql -Atx postgres://admin:secret@db:5433/a11ymon -c \"\COPY pubsecweb.nuts_conversion FROM './data/s3_files/Local_Authority_District_(December_2018)_to_NUTS3_to_NUTS2_to_NUTS1_(January_2018)_Lookup_in_United_Kingdom.csv' DELIMITER ',' CSV HEADER;\";
            python3 manage.py migrate query_local_website_registry --database=pubsecweb_db;
            python3 manage.py migrate;
            python3 manage.py loaddata ./data/s3_files/20210604_auth_data.json;
            python3 manage.py runserver 0.0.0.0:8001;
            "
        ports:
            - "8001:8001"
        depends_on:
            - db
        environment:
            - PGPASSWORD=secret
            - VCAP_SERVICES={'postgres':[{'credentials':{'uri':'postgres://admin:secret@db:5433/accessibility_monitoring_app'},'name':'monitoring-platform-default-db'},{'credentials':{'uri':'postgres://admin:secret@db:5433/a11ymon'},'name':'a11ymon-postgres'}]}
            - ALLOWED_HOSTS='* localhost 0.0.0.0 0.0.0.0:8001'
            - SECRET_KEY='123456789'
            - DEBUG=TRUE
        links:
            - "db:db"

