# Generated by Django 5.0.7 on 2024-08-02 09:15

from django.db import migrations


def tidy_event_values(apps, schema_editor):  # pylint: disable=unused-argument
    Event = apps.get_model("common", "Event")
    for event in Event.objects.all():
        event.value = event.diff
        event.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_populate_email_templates"),
    ]

    operations = [
        migrations.RunPython(tidy_event_values, reverse_code=reverse_code),
    ]
