# Generated by Django 5.0.7 on 2024-08-02 09:15

import json

from django.db import migrations


def diff(old_fields, new_fields):
    """Return differences between old and new values of fields"""
    if old_fields == "":
        return new_fields
    diff = {}
    for key in new_fields:
        if key in old_fields:
            if old_fields[key] != new_fields[key]:
                diff[key] = f"{old_fields[key]} -> {new_fields[key]}"
        else:
            diff[key] = f"-> {new_fields[key]}"
    for key in old_fields:
        if key not in new_fields:
            diff[key] = f"{old_fields[key]} ->"
    return diff


def tidy_event_values(apps, schema_editor):  # pylint: disable=unused-argument
    Event = apps.get_model("common", "Event")
    for event in Event.objects.all():
        value_dict = json.loads(event.value)
        if "old" in value_dict:
            old_fields = json.loads(value_dict["old"])[0]["fields"]
        else:
            old_fields = ""
        new_fields = json.loads(value_dict.get("new", ""))[0]["fields"]
        event.value = diff(old_fields, new_fields)
        event.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_populate_email_templates"),
    ]

    operations = [
        migrations.RunPython(tidy_event_values, reverse_code=reverse_code),
    ]
