# Generated by Django 3.2.4 on 2021-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_issuereport_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='trello_ticket',
            field=models.CharField(default='', max_length=200),
        ),
    ]
