# Generated by Django 5.1.5 on 2025-01-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_store_only_event_diffs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issuereport",
            old_name="description",
            new_name="issue_description",
        ),
        migrations.AddField(
            model_name="issuereport",
            name="goal_description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
