# Generated by Django 5.1.8 on 2025-04-08 12:48

from datetime import datetime, timezone

from django.db import migrations


def reset_case_updated(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    lowest_unix_datetime: datetime = datetime(1970, 1, 1, tzinfo=timezone.utc)
    Case.objects.all().update(updated=lowest_unix_datetime)


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        ("common", "0004_rename_description_issuereport_issue_description_and_more"),
    ]

    operations = [
        migrations.RunPython(reset_case_updated, reverse_code=reverse_code),
    ]
