# Generated by Django 5.1.8 on 2025-04-08 06:52

from django.db import migrations
from django.utils.text import slugify


def populate_template_name(apps, schema_editor):  # pylint: disable=unused-argument
    EmailTemplate = apps.get_model("common", "EmailTemplate")
    for email_template in EmailTemplate.objects.all():
        email_template.template_name = slugify(email_template.name)
        email_template.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    EmailTemplate = apps.get_model("common", "EmailTemplate")
    for email_template in EmailTemplate.objects.all():
        email_template.template_name = ""
        email_template.save()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_remove_emailtemplate_slug_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_template_name, reverse_code=reverse_code),
    ]
