# Generated by Django 3.2.8 on 2021-10-22 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

INSERT_SQL = """
INSERT INTO common_platform (id, active_qa_auditor_id) VALUES (1, NULL)
;
"""


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0006_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("model_update", "Model update"),
                    ("model_create", "Model create"),
                ],
                default="model_update",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_qa_auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_active_qa_auditor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunSQL(INSERT_SQL, reverse_sql=""),
    ]
