# Generated by Django 3.2.8 on 2021-10-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('model_update', 'Model update'), ('model_create', 'Model create')], default='model_update', max_length=100),
        ),
    ]
