# Generated by Django 4.1a1 on 2022-07-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_auto_20220127_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="report_viewer_accessibility_statement",
            field=models.TextField(blank=True, default=""),
        ),
    ]
