# Generated by Django 5.2.3 on 2025-08-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_delete_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frequentlyusedlink",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="frequentlyusedlink",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("simplified", "Simplified"),
                    ("detailed", "Detailed"),
                    ("mobile", "Mobile"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="frequentlyusedlink",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
