# Generated by Django 5.2.3 on 2025-08-20 08:57

from django.db import migrations

SIMPLIFIED_LINK_IDS: list[int] = [
    35,  # Equality body requests
    36,  # Accessibility statements
    68,  # More information about monitoring
    101,  # Simplified testing questions
]


def set_frequently_used_links_case_type(
    apps, schema_editor
):  # pylint: disable=unused-argument
    FrequentlyUsedLink = apps.get_model("common", "FrequentlyUsedLink")
    for frequently_used_link in FrequentlyUsedLink.objects.filter(
        id__in=SIMPLIFIED_LINK_IDS
    ):
        frequently_used_link.case_type = "simplified"
        frequently_used_link.save()

    position: int = 0
    for frequently_used_link in FrequentlyUsedLink.objects.all().order_by("id"):
        position += 10
        frequently_used_link.position = position
        frequently_used_link.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_frequentlyusedlink_case_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_frequently_used_links_case_type, reverse_code=reverse_code
        ),
    ]
