# Generated by Django 5.2.8 on 2025-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_set_freq_link_case_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("simplified", "Simplified"),
                    ("det-mob", "Detailed and mobile"),
                ],
                default="simplified",
                max_length=10,
            ),
        ),
    ]
