# Generated by Django 4.1b1 on 2022-07-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0010_changetoplatform"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="platform_accessibility_statement",
            field=models.TextField(
                blank=True,
                default="# Accessibility statement\n\nPlaceholder for platform.",
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="platform_privacy_notice",
            field=models.TextField(
                blank=True, default="# Privacy notice\n\nPlaceholder for platform."
            ),
        ),
    ]
