# Generated by Django 5.2.8 on 2025-12-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_set_freq_link_case_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="is_detailed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="is_mobile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="is_simplified",
            field=models.BooleanField(default=False),
        ),
    ]
