# Generated by Django 5.2.8 on 2025-12-17 08:06

from django.db import migrations

CREATED_BY_USER_ID: int = 2
EMAIL_TEMPLATE_NAMES: list[dict[str, str]] = [
    {
        "name": "1. Initial contact - request for info",
        "template_name": "d1-initial-contact-request-info",
    },
    {
        "name": "2. Initial contact - no contact details",
        "template_name": "d2-initial-contact-no-details",
    },
    {
        "name": "3. Initial contact - Chaser",
        "template_name": "d3-initial-contact-chaser",
    },
]


def populate_email_templates(apps, schema_editor):  # pylint: disable=unused-argument
    User = apps.get_model("auth", "User")
    user = User.objects.filter(id=CREATED_BY_USER_ID).first()
    if user is not None:  # Not in testing environment
        EmailTemplate = apps.get_model("common", "EmailTemplate")
        for email_template in EmailTemplate.objects.all():
            email_template.is_simplified = True
            email_template.save()
        for email_template_name in EMAIL_TEMPLATE_NAMES:
            EmailTemplate.objects.create(
                name=email_template_name["name"],
                template_name=email_template_name["template_name"],
                is_detailed=True,
                is_mobile=True,
                created_by=user,
                updated_by=user,
            )


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    EmailTemplate = apps.get_model("common", "EmailTemplate")
    for email_template in EmailTemplate.objects.all().exclude(is_simplified=True):
        email_template.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_emailtemplate_is_detailed_emailtemplate_is_mobile_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_email_templates, reverse_code=reverse_code),
    ]
