# Generated by Django 4.1 on 2022-08-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_platform_platform_accessibility_statement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="markdown_cheatsheet",
            field=models.TextField(blank=True, default=""),
        ),
    ]
