# Generated by Django 5.2.9 on 2025-12-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_populate_email_templates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"ordering": ["position"]},
        ),
    ]
