# Generated by Django 4.1 on 2022-09-27 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("common", "0013_platform_more_information_about_monitoring"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCacheUniqueHash",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("fingerprint_hash", models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
