# Generated by Django 5.2.9 on 2025-12-31 11:10

from unittest.mock import Mock, patch

from django.db import migrations


def port_non_case_event_history(apps, schema_editor):  # pylint: disable=unused-argument
    SimplifiedEventHistory = apps.get_model("simplified", "SimplifiedEventHistory")
    EventHistory = apps.get_model("common", "EventHistory")
    for simplified_event_history in SimplifiedEventHistory.objects.filter(
        simplified_case_id=None
    ):
        with patch(
            "django.utils.timezone.now",
            Mock(return_value=simplified_event_history.created),
        ):
            EventHistory.objects.create(
                content_type=simplified_event_history.content_type,
                object_id=simplified_event_history.object_id,
                # parent=simplified_event_history.parent,
                event_type=simplified_event_history.event_type,
                difference=simplified_event_history.difference,
                created_by_id=simplified_event_history.created_by_id,
                is_deleted=simplified_event_history.is_deleted,
            )
            simplified_event_history.delete()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    SimplifiedEventHistory = apps.get_model("simplified", "SimplifiedEventHistory")
    EventHistory = apps.get_model("common", "EventHistory")
    for event_history in EventHistory.objects.all():
        with patch(
            "django.utils.timezone.now",
            Mock(return_value=event_history.created),
        ):
            SimplifiedEventHistory.objects.create(
                content_type=event_history.content_type,
                object_id=event_history.object_id,
                # parent=event_history.parent,
                event_type=event_history.event_type,
                difference=event_history.difference,
                created_by_id=event_history.created_by_id,
                is_deleted=event_history.is_deleted,
            )
            event_history.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_alter_emailtemplate_options_eventhistory"),
    ]

    operations = [
        migrations.RunPython(port_non_case_event_history, reverse_code=reverse_code),
    ]
