# Generated by Django 4.1.4 on 2023-03-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_usercacheuniquehash"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrequentlyUsedLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(blank=True, default="")),
                ("url", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
    ]
