# Generated by Django 4.1.10 on 2023-07-26 07:35
import os

from django.db import connection, migrations

VERSION_SQL: str = """
DELETE FROM public.common_changetoplatform;
INSERT INTO public.common_changetoplatform VALUES (1, 'Monday 11 July 2022', '* Added placeholder [accessibility statement](https://accessibility-monitoring-report-viewer-test.london.cloudapps.digital/reports/accessibility-statement) and [privacy notice](https://accessibility-monitoring-report-viewer-test.london.cloudapps.digital/reports/privacy-notice) pages to Report viewer. The contents can be edited in Django [admin](https://accessibility-monitoring-platform-test.london.cloudapps.digital/admin/common/platform/1/change/).
(Trello cards [#773](https://trello.com/c/MXIxantK/773-add-accessibility-statement-to-report-viewer) and [#774](https://trello.com/c/4bwQsP5q/774-add-privacy-notice-to-report-viewer))
* Allow up to 20 failed login attempts before locking the user’s platform account.
[#794](https://trello.com/c/Mcm5uGnz/794-increase-number-of-failed-logins-to-20)
* Increase Django session timeout to 6-days. This ought to limit the number of times the user is prompted to log in.
[#797](https://trello.com/c/OY1QZcxW/797-extend-platform-session-timeout-to-6-days)
* Add [version history](https://accessibility-monitoring-platform-test.london.cloudapps.digital/common/platform-versions/) page to platform.
[#796](https://trello.com/c/3WtP53Nu/796-add-platform-version-history-in-settings-and-banner-in-dashboard)', '2022-07-11 12:30:45.252416+00');
INSERT INTO public.common_changetoplatform VALUES (2, 'Tuesday 12 July 2022', '* Move `<noscript>` tag from `<body>` to `<head>` of published [report](https://accessibility-monitoring-report-viewer-test.london.cloudapps.digital/reports/a6e4a473-c676-48b5-9a1b-314461022544)s.
[#804](https://trello.com/c/w4cThtnH/804-move-noscript-tag-from-body-to-header-in-report-viewer)', '2022-07-12 15:29:55.097758+00');
INSERT INTO public.common_changetoplatform VALUES (12, 'Wednesday 3 August 2022', '* Removed inline styling from report viewer.
[#864](https://trello.com/c/ea4BcKvA/864-remove-inline-styling-from-report-viewer)
* Added security.txt.
[#862](https://trello.com/c/ahr5wy6Z/862-add-securitytxt)
* Added new HTTP headers.
[#843](https://trello.com/c/qYTjyoyi/843-add-content-security-policy-and-permissions-policy-to-headers)
* Added unit tests for status requirements.
[#785](https://trello.com/c/Xr9oFrU9/785-write-unit-tests-for-status-requirements)
* Dashboard shows correct metrics and added unit tests.
[#858](https://trello.com/c/3EKnPiFX/858-fix-active-cases-metric-on-dashboard)', '2022-08-08 09:58:13.488122+00');
INSERT INTO public.common_changetoplatform VALUES (3, 'Wednesday 13 July 2022', '* Change suspend case to deactivate [case](https://accessibility-monitoring-platform-test.london.cloudapps.digital/cases/498/view/).
[#725](https://trello.com/c/jrCpQwaB/725-change-suspend-case-to-mark-case-as-inactive)
* Show 12-week *Enforcement Procedure* value in its field ([example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/audits/1/edit-audit-retest-statement-1/)).
[#807](https://trello.com/c/ywS8fpAm/807-enforcement-procedure-in-as-retest-assessment-to-default-to-not-included)', '2022-07-13 12:53:12.699171+00');
INSERT INTO public.common_changetoplatform VALUES (21, 'Thursday 25 August 2022', '* Capitalise Axe on report-text page.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/1/edit-audit-report-text/))
[#897](https://trello.com/c/Zk7NwdLc/897-axe-in-report-text)
* Show print button in report when Javascript enabled.
[#890](https://trello.com/c/QxFgGIIt/890-print-button-shows-when-javascript-disabled)
* Remove global variable.
[#836](https://trello.com/c/IuSKtzd0/836-remove-global)
* Simplify SCSS (styling) file structure.
[#881](https://trello.com/c/jZJ88gBF/881-refactor-scss)
* Put "Issue found by Deque Axe" in `WCAGDefinition` boilerplate.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-publisher/))
[#895](https://trello.com/c/u68fYtxE/895-put-found-by-deque-axe-in-boilerplate)
* Add `js-enabled` class to `<body>` tag to enable dashboard accordion.
[#903](https://trello.com/c/y1WwetTV/903-dashboard-needs-js-enabled-class-in-body)', '2022-08-25 10:55:49.559421+00');
INSERT INTO public.common_changetoplatform VALUES (4, 'Thursday 14 July 2022', '* Add “issue” as hidden prefix to row numbers for screen readers. [Example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/1/report-publisher/)
[#756](https://trello.com/c/R27GhUAb/756-update-table-designs)
* Have separate issue tables for each page in [report](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/1/report-publisher/#report-section-149).
[#756](https://trello.com/c/R27GhUAb/756-update-table-designs)
* Stop images being wider than the window, e.g. logo at 400% zoom. [Example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/1/report-publisher/)
[#805](https://trello.com/c/Psh1wIN4/805-resize-images-in-report-viewer-when-page-dimensions-change)', '2022-07-14 08:23:32.279779+00');
INSERT INTO public.common_changetoplatform VALUES (19, 'Wednesday 17 August 2022', '* Upgrade Django to version 4.1 and add found by Deque Axe to report text.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/1/edit-audit-report-text/))
[#871](https://trello.com/c/0qY81umI/871-update-django-to-41) and
[#891](https://trello.com/c/WXpkbXYA/891-add-found-by-deque-axe-to-report-text)
* Use StandardJS formatting.
[#865](https://trello.com/c/aT5w7RzY/865-update-js-with-standard-js-style-guide)
* Map .gov.uk domains from platform to viewer.
[#889](https://trello.com/c/30NMisfr/889-add-govuk-domains-to-links-to-published-reports)
* Remove delete and restore test from UI.
[#877](https://trello.com/c/ed2wKcxS/877-remove-delete-test-functionality-from-platform)
* Add field to record URL of previous case.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/498/edit-case-details/))
[#868](https://trello.com/c/TqSrFAYt/868-add-a-way-to-ref-repeat-cases-to-existing-cases-design-attached)', '2022-08-17 11:30:50.203901+00');
INSERT INTO public.common_changetoplatform VALUES (23, 'Thursday 1 September 2022', '* Stop using a specific version of the `python_buildpack`.
[#902](https://trello.com/c/eeA0tYIc/902-revert-pythonbuildpack-version-pinning)
* Remove domain names from source code.
[#898](https://trello.com/c/2PZPuhwf/898-remove-domain-names-from-source-code)', '2022-09-01 12:26:48.302721+00');
INSERT INTO public.common_changetoplatform VALUES (24, 'Friday 2 September 2022', '* Upgrade GOV.UK Frontend to version 4.3.1.
[#909](https://trello.com/c/ldeE1GhQ/909-upgrade-to-govuk-frontend-v431)
* Make report viewer root redirect secure.
([reports-test.accessibility-monitoring.service.gov.uk](https://reports-test.accessibility-monitoring.service.gov.uk))
[#867](https://trello.com/c/QSLWQmUH/867-fix-insecure-redirect-in-report-viewer)', '2022-09-02 11:53:18.279445+00');
INSERT INTO public.common_changetoplatform VALUES (25, 'Monday 5 September 2022', '* Replace `pipenv` with `pip` and `pip-compile`.
[#907](https://trello.com/c/wOC8Mwp7/907-stop-using-pipenv)', '2022-09-05 12:49:38.335182+00');
INSERT INTO public.common_changetoplatform VALUES (26, 'Wednesday 7 September 2022', '* Upgrade Django to version 4.1.1.
[#914](https://trello.com/c/jnziVory/914-upgrade-django-to-411)
* Warn when report not found in S3.
[#912](https://trello.com/c/pHHAY4Bk/912-raise-log-warning-if-the-s3-bucket-fails-to-retrieve-report)', '2022-09-07 10:40:45.385984+00');
INSERT INTO public.common_changetoplatform VALUES (27, 'Thursday 8 September 2022', '* Make issues tables header ids and cell headers attribute values consistent.
[#916](https://trello.com/c/dUJ1LD6u/916-check-fix-accessibility-issue-in-reports)', '2022-09-08 12:50:03.716622+00');
INSERT INTO public.common_changetoplatform VALUES (56, 'Thursday 1 December 2022', '* Add report metrics page.
([Report metrics](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-report/))
[#1034](https://trello.com/c/nMAtrj0t/1034-add-report-metrics)', '2022-12-01 08:53:06.825371+00');
INSERT INTO public.common_changetoplatform VALUES (57, 'Friday 2 December 2022', '* Remove testing spreadsheet logic.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/1/view/))
[#1040](https://trello.com/c/9Vbczd4M/1040-remove-testing-spreadsheet-specific-logic)', '2022-12-02 13:30:06.626879+00');
INSERT INTO public.common_changetoplatform VALUES (5, 'Friday 15 July 2022', '* Give tables in report unique ids. [Example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/1/report-publisher/#report-section-212)
[#814](https://trello.com/c/U9flh1ra/814-ensure-different-ids-for-each-table-in-the-report)
* Add [accessibility statement](https://accessibility-monitoring-platform-test.london.cloudapps.digital/common/accessibility-statement) and [privacy notice](https://accessibility-monitoring-platform-test.london.cloudapps.digital/common/privacy-notice) to platform.
[#802](https://trello.com/c/kodgxTLY/802-add-accessibility-statement-and-privacy-notice-to-platform)
* Hide platform report when report methodology is ODT templates.
[Example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/cases/500/view/#report-details)
[#803](https://trello.com/c/4tOTcAeb/803-case-view-is-showing-report-details-for-platform-mode-when-its-set-to-odt-templates)
* Repopulate base template using data cleanup migration script.
([admin](https://accessibility-monitoring-platform-test.london.cloudapps.digital/admin/reports/basetemplate/))
[#756](https://trello.com/c/R27GhUAb/756-update-table-designs)
* Add caption tags to tables in [reports](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/1/report-publisher/#report-section-211).
[#811](https://trello.com/c/5NfwSppD/811-correctly-nest-captions-inside-report-table)
* Make row number column wider when it contains multi-digit numbers (otherwise the number wraps in mobile view).
[#810](https://trello.com/c/Q0EZDfsz/810-row-id-spills-over-two-paragraphs-in-mobile-view)', '2022-07-15 12:37:40.345745+00');
INSERT INTO public.common_changetoplatform VALUES (7, 'Friday 21 July 2022', '* Hide table captions in reports.
([example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/1/report-publisher/#report-section-235))
[#826](https://trello.com/c/WUZ0eU5W/826-table-caption-styled-as-h3-in-reports)
* Add [UI to edit WCAG errors](https://accessibility-monitoring-platform-test.london.cloudapps.digital/audits/wcag-definition-list).
[#789](https://trello.com/c/ErxLN2Fo/789-add-ui-for-editing-wcag-definitions-design-attached)
* Use `gov.uk` report viewer domains.
([example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/cases/498/view/#report-details))
[#829](https://trello.com/c/fKYGy2KA/829-move-report-viewer-url-to-our-domain)
* Restructure text on [all issues](https://accessibility-monitoring-platform-test.london.cloudapps.digital/audits/all-issues/) page.
[#831](https://trello.com/c/QD2C9LPz/831-remove-description-from-link-label-on-all-issues-page)', '2022-07-22 12:00:45.555428+00');
INSERT INTO public.common_changetoplatform VALUES (9, 'Tuesday 26 July 2022', '* Warn when data has changed since report was published.
([example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/cases/498/view/))
[#769](https://trello.com/c/LKpuGThz/769-add-a-banner-to-advise-auditors-to-refresh-and-republish-the-report-after-the-case-or-test-data-changes-update-design-to-show-da)
* Add retest disproportionate burden fields to the Equalities body CSV
([example csv](https://accessibility-monitoring-platform-test.london.cloudapps.digital/cases/export-as-ehrc-csv/))
[#837](https://trello.com/c/82clN8m1/837-add-the-db-decision-from-the-accessibility-statement-assessment-to-the-eb-csv-export)', '2022-07-26 13:15:44.126003+00');
INSERT INTO public.common_changetoplatform VALUES (8, 'Monday 25 July 2022', '* Update layout of WCAG error boilerplate cells in report.
([example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/1/report-publisher/#report-section-236))
[#835](https://trello.com/c/PHwJYG5y/835-update-wcag-error-boilerplate-layout)
* Hide WCAG definition report boilerplate after first time.
([example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/1/report-publisher/#report-section-275))
[#822](https://trello.com/c/XdP2vISd/822-remove-repeated-wcag-report-boilerplate-in-the-report)', '2022-07-25 14:42:23.870916+00');
INSERT INTO public.common_changetoplatform VALUES (6, 'Tuesday 19 July 2022', '* Remove *related content* from printed reports.
([Example published report](https://accessibility-monitoring-report-viewer-test.london.cloudapps.digital/reports/84d4b570-d78b-45ae-8c79-85dc72c7aece))
[#823](https://trello.com/c/yM3L26m7/823-remove-related-content-from-printed-report)
* Remove most of the footer from printed reports.
[#824](https://trello.com/c/RGCNXTGF/824-remove-footer-but-keep-crown-copyright-in-printed-version-of-the-report)
* Use Helvetica in printed reports.
[#818](https://trello.com/c/NnrrJWCP/818-pdf-export-should-use-helvetica-instead-of-transport-font)
* Add page break at start of each section in printed reports.
[#819](https://trello.com/c/a1Jrwv05/819-insert-page-breaks-for-sections-headers)', '2022-07-19 09:16:18.901757+00');
INSERT INTO public.common_changetoplatform VALUES (13, 'Thursday 4 August 2022', '* Added proxy to official security.txt.
[#866](https://trello.com/c/Q2i220Cf/866-update-securitytxt-with-official-txt-file)', '2022-08-08 10:00:03.072623+00');
INSERT INTO public.common_changetoplatform VALUES (10, 'Wednesday 27 July 2022', '* Capitalise Deque Axe; Hide description of manual tests.
([example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/reports/3/report-publisher/#report-section-318))
[#833](https://trello.com/c/jlXhP8Ys/833-report-issues-detected-by-axe-design-needed)', '2022-07-27 14:19:04.480104+00');
INSERT INTO public.common_changetoplatform VALUES (11, 'Tuesday 2 August 2022', '* Added links to audit and report details if they dont exist .
[#816](https://trello.com/c/vEo5qXOC/816-update-case-summary-for-when-report-doesnt-exist-yet-design-attached)
* Updated footer in the report viewer.
[#817](https://trello.com/c/U1mMmyxr/817-update-footer-in-the-report-viewer-design-attached)
* Add report feedback form.
[#771](https://trello.com/c/N9eiOxtz/771-add-feedback-form-to-report-viewer-design-attached)
* Add report metrics to the platform.
[#772](https://trello.com/c/Utli73Re/772-add-report-viewing-metrics-to-platform-design-attached)', '2022-08-08 09:52:54.025368+00');
INSERT INTO public.common_changetoplatform VALUES (14, 'Monday 8 August 2022', '* Add unit tests for Javascript.
[#801](https://trello.com/c/xqUJFhty/801-unit-tests-for-javascript-functions)', '2022-08-08 10:03:08.351594+00');
INSERT INTO public.common_changetoplatform VALUES (15, 'Tuesday 9 August 2022', '* Remove date column from equalities body CSV.
[#844](https://trello.com/c/Qzu1lL02/844-remove-date-col-from-eb-csv)', '2022-08-09 12:56:44.124899+00');
INSERT INTO public.common_changetoplatform VALUES (16, 'Wednesday 10 August 2022', '* Upgrade GDS Design System to version 4.3.0
[#876](https://trello.com/c/rRXSx41w/876-update-to-gds-design-system-version-430)
* Add empty version of 12-week correspondence page when no contact from PSB.
([example](https://accessibility-monitoring-platform-test.london.cloudapps.digital/cases/498/edit-twelve-week-correspondence/))
[#847](https://trello.com/c/zQ3ZsnZ0/847-create-void-page-on-12-week-correspondence-which-suggests-moving-to-the-next-page-design-attached)', '2022-08-10 10:13:41.014243+00');
INSERT INTO public.common_changetoplatform VALUES (17, 'Monday 15 August 2022', '* Remove inline styles.
[#863](https://trello.com/c/2IRWLvB3/863-remove-all-inline-styling)
* Replace command `pipenv lock -r` with `pipenv requirements` in devops.
[#882](https://trello.com/c/kAJl5GKu/882-fix-devops-scripts-following-changes-to-pipenv)
* Fix smoke test.
[#882](https://trello.com/c/kAJl5GKu/882-fix-devops-scripts-following-changes-to-pipenv)', '2022-08-15 15:02:09.333829+00');
INSERT INTO public.common_changetoplatform VALUES (18, 'Tuesday 16 August 2022', '* Fix dynamic open link.
[#879](https://trello.com/c/UHlEikGx/879-open-link-button-borked-by-new-security-standard)', '2022-08-16 12:20:14.792516+00');
INSERT INTO public.common_changetoplatform VALUES (20, 'Thursday 18 August 2022', '* Fix non-production watermarks.
[#892](https://trello.com/c/zVqxwmPV/892-fix-non-production-watermarks)', '2022-08-18 12:13:01.890408+00');
INSERT INTO public.common_changetoplatform VALUES (22, 'Friday 26 August 2022', '* Add Markdown cheatsheet [page](https://platform-test.accessibility-monitoring.service.gov.uk/common/markdown-cheatsheet).
[#757](https://trello.com/c/ymWEU3Df/757-markdown-training-cheatsheet-in-page)', '2022-08-26 09:54:10.524603+00');
INSERT INTO public.common_changetoplatform VALUES (28, 'Tuesday 13 September 2022', '* Fixed bullet point bug in report viewer.
[#920](https://trello.com/c/Jt8YIq9D/920-bullet-points-missing-in-report-issues)
* Add More information about monitoring page.
([more info](https://reports-test.accessibility-monitoring.service.gov.uk/reports/more-information))
[#918](https://trello.com/c/xqYUBDWT/918-add-an-extra-page-like-acc-statement-privacy-notice-for-more-information)', '2022-09-13 10:26:40.363196+00');
INSERT INTO public.common_changetoplatform VALUES (30, 'Wednesday 21 September 2022', '* Default testing and report methodologies to platform.
[#933](https://trello.com/c/8nCBEX6k/933-default-methodologies-to-platform)
* Notify users when unpublished report is out of date.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/512/view/))
[#925](https://trello.com/c/zklOVlsm/925-warn-users-when-report-out-of-date)', '2022-09-21 12:16:51.861615+00');
INSERT INTO public.common_changetoplatform VALUES (29, 'Friday 16 September 2022', '* Save test results only when changed.
[#926](https://trello.com/c/Bd1kXYcF/926-only-update-checkresult-if-a-change-has-been-made)
* Make report header full width.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-publisher/))
[#928](https://trello.com/c/uQoUPdrs/928-go-full-width-for-the-report-title)
* Show last updated time for unpublished reports.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/7/report-publisher/))
[#924](https://trello.com/c/wPvXqFcB/924-date-is-missing-in-report-preview-when-the-report-hasnt-been-published)
* Label `<nav>` tags in report uniquely for screen readers.
([example](https://reports-test.accessibility-monitoring.service.gov.uk/reports/d57938ee-1f53-47d9-914d-103a09a68b13))
[#917](https://trello.com/c/3rMoPlV8/917-add-role-to-nav-bar-element-in-report-viewer)
* Re-enable issue report link in `test` platform.
[#927](https://trello.com/c/7u7ljW3S/927-report-issue-disabled-on-test)
* Treat notes fields'' content as markdown.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-qa-process/#comments))
[#921](https://trello.com/c/o5Ej0ZMO/921-run-note-fields-through-markdown)
* Add website accessibility statement to *Frequently used links*.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-contact-details/))
[#873](https://trello.com/c/iEuk6cLf/873-add-link-to-the-websites-accessibility-statement-in-frequently-used-links)
* Change correspondence overdue period from 5 days to 7.
[#874](https://trello.com/c/IhTM41a6/874-report-correspondence-has-five-working-days-in-the-chaser-currently-it-is-five-cal-days)', '2022-09-16 12:05:42.543259+00');
INSERT INTO public.common_changetoplatform VALUES (31, 'Monday 26 September 2022', '* Add Contact page is a form checkbox.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-pages/))
[#875](https://trello.com/c/jqfcjO56/875-contact-page-is-a-form-field-in-the-audit-pages-page-design-attached)
* Link to report publisher from case search results.
[#932](https://trello.com/c/MULp9Vx8/932-change-view-report-link-in-search-results-to-redirect-to-the-report-publisher-page-and-not-the-edit-report-page)
* Warn user to edit report issues in test UI.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/sections/478/edit-section/))
[#923](https://trello.com/c/1XXUILnP/923-direct-users-to-test-ui-when-they-edit-the-errors-in-the-report-publisher-design-attached)
* Change OTP token email subject line.
[#935](https://trello.com/c/oxMMzIZp/935-otp-token-email)
* Return to origin page after report reset.
[#936](https://trello.com/c/3Y6q8Qmz/936-reset-report-button-should-return-to-page-it-was-submitted-on)', '2022-09-26 11:31:03.692751+00');
INSERT INTO public.common_changetoplatform VALUES (35, 'Monday 10 October 2022', '* Fix report publisher breadcrumbs.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-confirm-publish/))
[#953](https://trello.com/c/RbMB95Fi/953-fix-report-publisher-breadcrumb)
* Fix sublist structures.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/detail/))
[#954](https://trello.com/c/MFk76aSb/954-fix-sublist-structures)', '2022-10-11 07:15:44.251207+00');
INSERT INTO public.common_changetoplatform VALUES (33, 'Thursday 29 September 2022', '* Use breadcrumb-style labels for links to pages.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/512/edit-report-correspondence/))
[#946](https://trello.com/c/gAcKZrm4/946-make-link-labels-consistent)
* Update code to satisfy Pylance static type checking.
[#947](https://trello.com/c/aDrtWAlo/947-pylance-complaints)
* Put PDF page at end of lists in report and UI.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/25/edit-audit-pages/))
[#950](https://trello.com/c/MSWWlFJj/950-move-pdf-in-testing-pages-to-the-bottom-of-the-list)', '2022-09-29 10:27:25.542272+00');
INSERT INTO public.common_changetoplatform VALUES (32, 'Tuesday 27 September 2022', '* Correct breadcrumbs in report UI.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/sections/563/edit-section/))
[#939](https://trello.com/c/FW5oNSY1/939-fix-edit-report-breadcrumbs)
* Remove *experimental* banner from Dashboard.
[#942](https://trello.com/c/B0KFtWt4/942-remove-experimental-banner-from-dashboard)
* Link to report publisher not report detail page.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/512/edit-qa-process/))
[#938](https://trello.com/c/c7qsjgOk/938-link-to-report-publisher)', '2022-09-27 10:09:18.879795+00');
INSERT INTO public.common_changetoplatform VALUES (37, 'Wednesday 12 October 2022', '* Use report from case in viewer.
[#967](https://trello.com/c/TLufM2sU/967-remove-duplicate-reports-from-report-model)
* Make the two search fields on the Search page unique.
[#958](https://trello.com/c/n3Y6o4cm/958-wcag-two-search-fields-on-search-page)
* Hide report text page when report methodology is platform.
[#965](https://trello.com/c/dm59mRp6/965-remove-report-test-if-reports-are-set-to-platform)
* Prevent creation of more than one report or test per case.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/detail/))
[#969](https://trello.com/c/eAxJTkP5/969-prevent-creation-of-duplicate-reports)', '2022-10-12 08:43:20.904534+00');
INSERT INTO public.common_changetoplatform VALUES (34, 'Friday 30 September 2022', '* Hide print button and feedback form in report print preview.
[#951](https://trello.com/c/LruddT7d/951-remove-report-a-problem-from-pdf-report)
* Remove page breaks from report print previews.
([example](https://reports-test.accessibility-monitoring.service.gov.uk/reports/7eab80f4-f49b-40c9-9631-d3eecd08c039))
[#948](https://trello.com/c/3TLxfBnG/948-fix-page-breaks-for-pdf-reports)', '2022-09-30 11:52:53.967471+00');
INSERT INTO public.common_changetoplatform VALUES (36, 'Tuesday 11 October 2022', '* Make IDs in accordions unique.
[#960](https://trello.com/c/x1zMy0LY/960-wcag-unique-ids-in-accordion)
* Rejig columns in equality body CSV export.
[#842](https://trello.com/c/DstyxvbL/842-equality-bodies-csv-change-export-order-names)
* Check URL exists before rendering link.
[#961](https://trello.com/c/YiBSKLQb/961-wcag-dont-render-empty-links)', '2022-10-11 12:25:22.285861+00');
INSERT INTO public.common_changetoplatform VALUES (38, 'Thursday 13 October 2022', '* Redirect to case on save and exit from testing UI
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-summary/))
[#964](https://trello.com/c/akZ4y8ZN/964-change-save-and-exit-in-the-final-step-of-the-testing-ui-to-link-to-testing-details-instead-of-the-testing-overview)
* Hide search icons from the accessibility API.
[#957](https://trello.com/c/Azu8Z2ww/957-wcag-buttons-must-have-discernible-text)', '2022-10-13 14:27:20.124518+00');
INSERT INTO public.common_changetoplatform VALUES (55, 'Wednesday 30 November 2022', '* Remove testing and report methodologies from UI.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-case-details/))
[#1031](https://trello.com/c/PhhXUIUe/1031-remove-choice-of-methodologies)', '2022-11-30 12:12:56.370628+00');
INSERT INTO public.common_changetoplatform VALUES (39, 'Monday 17 October 2022', '* Make relationships between Cases and tests and reports 1-to-1.
[#968](https://trello.com/c/NCxq5e8G/968-stop-multiple-tests-and-reports-being-created-when-page-is-opened-in-multiple-tabs)
* Add platform metrics overview page.
([Platform metrics](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-overview/))
[#972](https://trello.com/c/9smXUI3z/972-make-a-skeleton-app-of-the-platform-metrics-page)', '2022-10-17 11:14:52.01418+00');
INSERT INTO public.common_changetoplatform VALUES (43, 'Monday 24 October 2022', '* Add WCAG definition filter input field label.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-page-checks/))
[#988](https://trello.com/c/8LKxtsxM/988-give-wcag-filter-a-label-design-attached)
* Refine email template based on user feedback.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/twelve-week-correspondence-email/))
[#1001](https://trello.com/c/UED7mgvL/1001-refine-12-week-email-template)
* Add labels to edit report UI.
[(example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/sections/606/edit-section/))
[#990](https://trello.com/c/KKzPO6Qc/990-give-edit-report-text-areas-a-label-design-attached)
* Add published report url to equalities bodies export CSV.
[#1000](https://trello.com/c/nbVmwuth/1000-add-published-report-to-equalities-body-export)', '2022-10-24 12:32:10.935474+00');
INSERT INTO public.common_changetoplatform VALUES (44, 'Tuesday 25 October 2022', '* Add links to contact and statement pages to contact UI.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-contact-details/))
[#984](https://trello.com/c/PciPxGwm/984-add-link-to-contact-page-and-statement-in-the-platforms-contact-page-design-attached)
* Add cypress smoke tests.
[#997](https://trello.com/c/e45igAAD/997-create-new-smoke-tests-with-cypress)', '2022-10-25 12:27:25.369761+00');
INSERT INTO public.common_changetoplatform VALUES (46, 'Friday 28 October 2022', '* Add notes about missing mandatory text to UI and report.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-report-options/))
[#1010](https://trello.com/c/cWZA9DTF/1010-add-mandatory-wording-comment-box-in-report-options-design-attached)
* Add *Add contact* fields to Accessibility statement Pt. 1.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-statement-one/))
[#1012](https://trello.com/c/78KZlE4i/1012-add-contacts-field-in-statement-assessment)
* Add notes field to retest pages UI.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-retest-page-checks/))
[#1006](https://trello.com/c/twKWjU74/1006-add-notes-field-to-retest-design-attached)', '2022-10-28 11:57:57.664731+00');
INSERT INTO public.common_changetoplatform VALUES (40, 'Tuesday 18 October', '* Make prototype and test platform watermarks more visible.
[#977](https://trello.com/c/M5Ke5Waa/977-make-watermarks-accessible)
* Add complaint filter to cases search page.
([search page](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#962](https://trello.com/c/g0Hzgr8i/962-add-is-complaint-to-advance-search-design-attached)
* Add `500.html` page for errors.
[#970](https://trello.com/c/p0uQYUO9/970-create-500-page-for-the-report-viewer)
* Add *Status requirements* to right column on Testing and Retesting UI.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-page-checks/))
[#966](https://trello.com/c/t9Qg5jQv/966-add-status-requirements-to-testing-ui-design-attached)', '2022-10-18 07:37:29.332106+00');
INSERT INTO public.common_changetoplatform VALUES (41, 'Wednesday 19 October 2022', '*  Add testing and retesting disproportionate burden data to CSV.
[#994](https://trello.com/c/LqILlnbC/994-restore-retest-disproportionate-burden-to-csv)', '2022-10-20 07:32:10.90167+00');
INSERT INTO public.common_changetoplatform VALUES (42, 'Thursday 20 October 2022', '* Add email template for 12-week report correspondence.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/twelve-week-correspondence-email/))
[#963](https://trello.com/c/DkID8ei5/963-add-three-column-table-for-email-templates-at-12-week-correspondence-design-attached)
* Change checkboxes to have only one label.
[#959](https://trello.com/c/IjVnykf3/959-wcag-checkboxes-with-multiple-labels-design-needed)', '2022-10-20 13:34:05.1374+00');
INSERT INTO public.common_changetoplatform VALUES (45, 'Wednesday 26 October 2022', '* Change *is form* to *is on contact page*.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-pages/))
[#1008](https://trello.com/c/S5QfG9Fz/1008-move-contact-page-is-a-form-to-under-forms-in-test-pages)
* Add button to link to test UI from report publisher.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-publisher/))
[#986](https://trello.com/c/lJh9hS3K/986-add-edit-test-link-to-report-generator)', '2022-10-26 09:48:17.804535+00');
INSERT INTO public.common_changetoplatform VALUES (49, 'Thursday 3 November 2022', '* Add `axe-core` to integration tests.
[#1015](https://trello.com/c/0MxdEBCy/1015-add-axe-accessibility-test-to-ci-cd-pipeline-and-local-env)', '2022-11-03 09:12:40.783069+00');
INSERT INTO public.common_changetoplatform VALUES (50, 'Friday 4 November 2022', '* Add staging tests to deploy to production.
[#996](https://trello.com/c/vVTG9lnc/996-create-new-staging-tests-with-cypress-discuss-whats-needed)', '2022-11-04 11:12:00.962422+00');
INSERT INTO public.common_changetoplatform VALUES (47, 'Monday 31 October 2022', '* Add status workflow page to case.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/status-workflow/))
[#1005](https://trello.com/c/kzKzpDgO/1005-add-guidance-on-how-to-reverse-status-on-a-case-design-attached)
* Hide link to accessibility statement if none exists.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-statement-one/))
[#985](https://trello.com/c/ajwNqVkz/985-add-text-next-to-link-for-statement-saying-there-is-no-statement-in-test-ui)', '2022-10-31 12:13:03.894528+00');
INSERT INTO public.common_changetoplatform VALUES (48, 'Tuesday 1 November 2022', '* Show WCAG definition type in UI.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-page-checks/))
[#1013](https://trello.com/c/cJFFPali/1013-add-wcag-test-type-to-label-in-test-ui-design-attached)', '2022-11-01 12:13:51.958366+00');
INSERT INTO public.common_changetoplatform VALUES (51, 'Tuesday 15 November 2022', '* Add case metrics page.
([link](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-case/))
[#1016](https://trello.com/c/vXPrrvK2/1016-add-platform-insights-with-visualisations)', '2022-11-15 15:36:07.110924+00');
INSERT INTO public.common_changetoplatform VALUES (52, 'Wednesday 23 November 2022', '* Upgrade GDS design system to v4.4.0.
[#1023](https://trello.com/c/Jn2s0kKA/1023-upgrade-gds-design-system-to-v440)
* Add affects status help text to QA auditor field.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-qa-process/))
[#1022](https://trello.com/c/nOpQKt52/1022-add-this-is-required-for-status-help-text-to-qa-auditor-on-the-qa-page)
* Show page retest notes on comparison page.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-retest-pages/))
[#1020](https://github.com/alphagov/accessibility-monitoring-platform/pull/147)', '2022-11-23 12:48:15.301605+00');
INSERT INTO public.common_changetoplatform VALUES (53, 'Thursday 24 November 2022', '* Hide accessibility statement details when no such page.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/26/edit-audit-statement-one/))
[#1021](https://trello.com/c/nNSjSgB3/1021-hide-statement-assessment-form-if-statement-doesnt-exist-design-attached)
* Add policy metrics page.
([policy metrics](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-policy/))
[#1016](https://trello.com/c/vXPrrvK2/1016-add-platform-insights-with-visualisations)', '2022-11-24 05:02:43.648312+00');
INSERT INTO public.common_changetoplatform VALUES (54, 'Monday 28 November 2022', '* Add line labels to charts.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-policy/))
[#1024](https://trello.com/c/zAlvcb5c/1024-add-labels-to-charts)', '2022-11-28 08:53:04.118676+00');
INSERT INTO public.common_changetoplatform VALUES (67, 'Wednesday 4 January 2023', '* Add feedback survey export.
([search page](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#1063](https://trello.com/c/kO2AwHBt/1063-add-export-feedback-survey-export)', '2023-01-04 08:34:36.272845+00');
INSERT INTO public.common_changetoplatform VALUES (72, 'Friday 20 January 2023', '* Fix codeblocks in `showdownjs` markdown previews.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-page-checks/))
[#1078](https://trello.com/c/0fT5gtLg/1078-code-blocks-wrong-in-previews)
* Add filter on Case event done_by to Django admin.
[#1077](https://trello.com/c/5KTBvTpS/1077-add-email-filter-to-user-events-in-admin)', '2023-01-20 10:40:43.489813+00');
INSERT INTO public.common_changetoplatform VALUES (58, 'Monday 5 December 2022', '* Add more information about monitoring page to platform.
([more information page](https://platform-test.accessibility-monitoring.service.gov.uk/common/more-information/))
[#1041](https://trello.com/c/2XswqpUI/1041-show-more-information-about-monitoring-text)
* Filter cases by members of new *Historic auditor* user group.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/?auditor=8))
[#1039](https://trello.com/c/kKtKx9lD/1039-how-to-manage-taking-jess-or-any-other-auditors-off-the-system)
* Remove Case deletion.
[#1038](https://trello.com/c/fSUku1xg/1038-remove-delete-case-status)', '2022-12-05 12:37:41.209805+00');
INSERT INTO public.common_changetoplatform VALUES (59, 'Tuesday 6 December 2022', '* Use GDS Transport font inside of SVG charts.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-policy/))
[#1043](https://trello.com/c/FlHtZ48p/1043-use-gds-transport-font-inside-svg-charts)', '2022-12-06 11:54:16.201678+00');
INSERT INTO public.common_changetoplatform VALUES (60, 'Wednesday 7 December 2022', '* Upgrade Django to 4.1.4; Upgrade other python package dependencies.
[#1047](https://trello.com/c/IqP1Zr0n/1047-upgrade-django-to-414)
* Make cases with testing spreadsheets readonly.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/1/view/))
[#1040](https://trello.com/c/9Vbczd4M/1040-remove-testing-spreadsheet-specific-logic)', '2022-12-07 10:55:37.122237+00');
INSERT INTO public.common_changetoplatform VALUES (61, 'Thursday 9 December 2022', '* Add open and closed case filter to Django admin.
([page](https://platform-test.accessibility-monitoring.service.gov.uk/admin/cases/case/))
[#1048](https://trello.com/c/Rx91IUMW/1048-add-meta-status-case-filters)', '2022-12-09 11:27:14.590788+00');
INSERT INTO public.common_changetoplatform VALUES (62, 'Tuesday 13 December 2022', '* Update metrics pages based on feedback from Chris.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-case/))
[#1050](https://trello.com/c/2Q6uMSar/1050-changes-to-metrics)', '2022-12-13 12:36:13.291659+00');
INSERT INTO public.common_changetoplatform VALUES (68, 'Thursday 5 January 2023', '* Add comma-delimiting to number for cases on search page.
([search case](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#1066](https://trello.com/c/1oNa4D5O/1066-comma-delimit-number-of-cases)
* Update policy metrics chart headers.
([policy metrics](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-policy/))
[#1067](https://trello.com/c/M6SwB5V0/1067-policy-metrics-headers)
* Show link to test results only when URL is present.
([example](https://platform.accessibility-monitoring.service.gov.uk/cases/644/view/#test-results))
[#1068](https://trello.com/c/C4V0u1ux/1068-missing-link-to-spreadsheet-test-results)', '2023-01-05 08:17:33.565084+00');
INSERT INTO public.common_changetoplatform VALUES (63, 'Friday 16 December 2022', '* Add Case event history.
([admin](https://platform-test.accessibility-monitoring.service.gov.uk/admin/cases/caseevent/))
[#1044](https://trello.com/c/XzJ2Hr0u/1044-add-auditor-completion-history)
* Change case export CSV column names to match UI labels.
([Search page](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#1049](https://trello.com/c/Fq9HALxo/1049-unify-naming-for-columns-in-the-spreadsheet-with-the-labels-in-the-forms)', '2022-12-16 15:47:47.102032+00');
INSERT INTO public.common_changetoplatform VALUES (64, 'Monday 19 December 2022', '* Make metrics pages more accessible.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-policy/))
[#1051](https://trello.com/c/UpkOBigf/1051-work-with-specialists-to-check-the-accessibility-of-the-metrics-pages-and-fix-where-necessary)
* Update GDS Design System to version 4.4.1.
[#1058](https://trello.com/c/YNilxsmM/1058-update-to-gds-design-system-version-441)', '2022-12-19 09:12:57.618715+00');
INSERT INTO public.common_changetoplatform VALUES (65, 'Wednesday 28 December 2022', '* Make migration more memory efficient.
[#1064](https://trello.com/c/51Oo92gZ/1064-case-event-history-deploy)', '2022-12-28 14:53:16.486907+00');
INSERT INTO public.common_changetoplatform VALUES (66, 'Tuesday 3 January 2023', '* Fix smoke test.
[#1064](https://trello.com/c/51Oo92gZ/1064-fix-case-event-history-deploy)', '2023-01-03 13:14:14.726159+00');
INSERT INTO public.common_changetoplatform VALUES (69, 'Wednesday 11 January 2023', '* Hide link to 12-week retest when spreadsheet testing.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/1/view/))
[#1071](https://trello.com/c/zK3oB7Mi/1071-spreadsheet-testing-case-showing-platform-ui-in-contents)', '2023-01-11 10:33:52.278702+00');
INSERT INTO public.common_changetoplatform VALUES (70, 'Monday 16 January 2023', '* Fix filtering of ''Not retested'' checks.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-retest-page-checks/))
[#1072](https://trello.com/c/OadZfpBt/1072-not-retested-filter-doesnt-work)', '2023-01-16 12:50:06.034121+00');
INSERT INTO public.common_changetoplatform VALUES (71, 'Wednesday 18 January 2023', '* Remove signature from 12-week email template.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/twelve-week-correspondence-email/))
[#1076](https://trello.com/c/ZpdnQn6U/1076-remove-12-week-signature)', '2023-01-18 15:44:13.846064+00');
INSERT INTO public.common_changetoplatform VALUES (73, 'Wednesday 25 January 2023', '* Autoescape (HTML) text entered by users.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-page-checks/))
[#1091](https://trello.com/c/mgzv5bSy/1081-autoescape-html)', '2023-01-25 14:39:25.159319+00');
INSERT INTO public.common_changetoplatform VALUES (74, 'Friday 27 January 2023', '* Remind user if page marked as missing on retest.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-retest-pages/))
[#1079](https://trello.com/c/x3lfoq5Y/1079-add-page-missing-label-to-12-week-retest-overview-page-design-attached)
* Upgrade `npm` packages.
[#1059](https://trello.com/c/DcYFLlq1/1059-update-npm-packages)', '2023-01-27 13:01:18.173238+00');
INSERT INTO public.common_changetoplatform VALUES (75, 'Wednesday 1 February 2023', '* Allow user to enter previous case url on create.
[#1085](https://trello.com/c/ufwkEyEy/1085-add-repeat-case-field-to-create-case-form-design-attached)
* Swap initial compliance website and statement reminders.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-retest-website-decision/))
[#1086](https://trello.com/c/VvQRWJoJ/1086-swap-initial-compliance-and-initial-statement-decision-design-attached)', '2023-02-01 11:54:07.803197+00');
INSERT INTO public.common_changetoplatform VALUES (76, 'Thursday 2 February 2023', '* Make filter UI smaller.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-page-checks/))
[#1089](https://trello.com/c/s7Qb3sQI/1089-make-filter-options-in-test-ui-smaller-design-attached)', '2023-02-02 15:23:04.227171+00');
INSERT INTO public.common_changetoplatform VALUES (77, 'Friday 3 February 2023', '* Add option to populate notes with summary text.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-case-close/))
[#1080](https://trello.com/c/VEPJDelr/1080-add-option-to-copy-text-from-summary-of-progress-made-from-public-sector-body-to-enforcement-recommendation-notes-design-attache)
* Show error to user when Case has changed.
[#1099](https://trello.com/c/mPtvlLI0/1099-bug-with-save-and-continue-in-retest)', '2023-02-03 08:38:37.944717+00');
INSERT INTO public.common_changetoplatform VALUES (86, 'Tuesday 14 March 2023', '* Add links to complete case to status workflow
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/status-workflow/))
[#1160](https://trello.com/c/xEz9sECk/1160-add-links-to-complete-case)
* Add outstanding issues page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/500/outstanding-issues/?view=Page%20view))
[#1114](https://trello.com/c/GmGxC9pe/1114-make-it-easier-to-view-which-issues-are-remaining-and-add-a-table-template-design-attached)
* Add case overview
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/500/view/))
[#1134](https://trello.com/c/KV5thjeL/1134-review-case-overview-page-and-add-additional-information-from-the-test-and-report-applications-design-attached)', '2023-03-14 14:13:34.617785+00');
INSERT INTO public.common_changetoplatform VALUES (78, 'Tuesday 14 February 2023', '* Label errors as error when there is only one.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/pages/110/edit-audit-page-checks/))
[#1116](https://trello.com/c/57xHlXef/1116-change-errors-to-error-on-testing-pages-when-there-is-one-error)
* Sort unique visits by most recent occurrence first.
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-metrics-view/?showing=unique-visitors))
[#1098](https://trello.com/c/WFGg8Wqq/1098-list-of-unique-visits-is-not-ordered-by-time)', '2023-02-14 13:05:59.332172+00');
INSERT INTO public.common_changetoplatform VALUES (79, 'Wednesday 15 February 2023', '* Fix display of case error on audit pages.
[#1113](https://trello.com/c/xLKimVvl/1113-fields-repeated-when-showing-version-error)
* Upgrade GDS Design System to version 4.5.0.
[#1110](https://trello.com/c/6DDTKaVA/1110-update-to-gds-design-system-version-450)', '2023-02-15 13:20:42.6397+00');
INSERT INTO public.common_changetoplatform VALUES (80, 'Tuesday 21 February 2023', '* Allow user to add link to statement at 12-week retest
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/26/edit-audit-retest-statement-1/))
[#1117](https://trello.com/c/VJ7g6l0k/1117-create-user-journey-to-add-and-test-the-statement-at-the-12-week-retest-if-a-statement-did-not-exist-before-design-attached)', '2023-02-21 16:34:00.925164+00');
INSERT INTO public.common_changetoplatform VALUES (81, 'Wednesday 22 February 2023', '* Recalculate proportion of accessibility statements which are compliant
([policy metrics](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-policy/))
[#1128](https://trello.com/c/5MTjzUlp/1128-troubleshoot-and-fix-visualisations-for-proportion-of-websites-which-are-acceptable-and-proportion-of-accessibility-statements-w)
* Add cases filter on enforcement body
([cases](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#1103](https://trello.com/c/ffYewD5Q/1103-add-ecni-ehrc-filter-to-advanced-search)', '2023-02-22 08:29:17.244813+00');
INSERT INTO public.common_changetoplatform VALUES (83, 'Thursday 2 March 2023', '* Hide links to report files when platform reporting used
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/498/view/#qa-process)).
[#1137](https://trello.com/c/Q04zBUf9/1137-remove-link-to-odt-report-and-link-to-final-pdf-report-in-case-overview)
* Remove report visits log section from Edit report page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/1/edit-report/#report-metadata))
[#1136](https://trello.com/c/k25B7JyW/1136-remove-report-visits-log-subsection-from-edit-report)
* Show reminders to current Case auditors
([reminders](https://platform-test.accessibility-monitoring.service.gov.uk/reminders/reminder-list/))
[#1106](https://trello.com/c/PNHczmXR/1106-investigate-whether-reminders-carry-over-when-cases-transfer-to-a-new-auditor)', '2023-03-02 14:27:46.440437+00');
INSERT INTO public.common_changetoplatform VALUES (82, 'Tuesday 28 February 2023', '* Rejig QA comments
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-qa-process/?discussion=open#qa-discussion))
[#1083](https://trello.com/c/MZfxmR3b/1083-redesign-qa-process-design-attached)
* Add field to store URL to EHRC-requested retest results document
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-enforcement-body-correspondence/))
[#1129](https://trello.com/c/SPvfI1pj/1129-add-retest-doc-field-in-edit-enforcement-body-correspondence-design-attached)', '2023-02-28 14:00:53.217464+00');
INSERT INTO public.common_changetoplatform VALUES (87, 'Friday 17 March 2023', '* Add filter on test start date to cases search
([search](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#1118](https://trello.com/c/nv418QTx/1118-add-test-start-date-to-date-filter-in-advanced-search)
* Show frequently used links on contents and steps in case, test and retest UI
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/view/))
[#1134](https://trello.com/c/KV5thjeL/1134-review-case-overview-page-and-add-additional-information-from-the-test-and-report-applications-design-attached)
* Save QA process form when Add comment button is pressed
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-qa-process/))
[#1142](https://trello.com/c/ZjDAsNG5/1142-make-sure-add-comment-in-qa-page-saves-the-page)', '2023-03-17 15:23:19.106223+00');
INSERT INTO public.common_changetoplatform VALUES (85, 'Tuesday 7 March 2023', '* Swap columns on Case search page
([search](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#1138](https://trello.com/c/uB9hzsEp/1138-update-case-search-page-design-attached)', '2023-03-07 11:23:37.033702+00');
INSERT INTO public.common_changetoplatform VALUES (84, 'Friday 3 March 2023', '* Include previous case number in CSV exports
[#1084](https://trello.com/c/7JKMX7op/1084-add-repeat-case-data-to-ehrc-export-needs-more-info)', '2023-03-03 13:00:09.771914+00');
INSERT INTO public.common_changetoplatform VALUES (88, 'Wednesday 22 March 2023', '* Add Enforcement recommendation notes to Export to feedback survey CSV
([search](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#1165](https://trello.com/c/hvL5g908/1165-add-column-to-csv)', '2023-03-22 16:16:44.200829+00');
INSERT INTO public.common_changetoplatform VALUES (116, 'Tuesday 20 June 2023', '* Change button labels on Report publisher page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-publisher/))
[#1245](https://trello.com/c/9kkArby4/1245-redesign-headline-buttons-in-report-publisher-design-attached)
* Add date equality body finished with case
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-enforcement-body-correspondence/))
[#1246](https://trello.com/c/bpgPsAUX/1246-add-date-field-for-when-eb-finish-with-a-case-design-attached)', '2023-06-20 07:36:53.849516+00');
INSERT INTO public.common_changetoplatform VALUES (98, 'Friday 21 April 2023', '* Add case contact notes
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-contact-details/))
[#1174](https://trello.com/c/mO4YBD9m/1174-add-generic-notes-field-for-contact-details-design-attached)', '2023-04-21 10:53:44.923802+00');
INSERT INTO public.common_changetoplatform VALUES (89, 'Thursday 23 March 2023', '* Add edit links to reminders list
[#1145](https://trello.com/c/mBfgWxoV/1145-add-an-edit-option-in-reminders-list-design-attached)
* Show fields to create two extra pages if none exist
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/26/edit-audit-pages/))
[#1140](https://trello.com/c/qr6j1PFY/1140-have-two-pages-compulsory-on-the-add-pages-page-design-attached)
* Add page to edit custom frequently used links
([edit frequently used links](https://platform-test.accessibility-monitoring.service.gov.uk/common/edit-frequently-used-links/))
[#1139](https://trello.com/c/gNwV5SBc/1139-make-a-list-of-editable-external-links-for-users-design-attached)
* Populate date fields with future dates
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reminders/10/edit-reminder/))
[#1107](https://trello.com/c/dhTO1vhG/1107-add-javascript-widget-to-reminders-to-autopopulate-date-design-attached)
* Fix displaying numbers of visitors on **Edit report** page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/edit-report/#report-metadata))
[#1155](https://trello.com/c/GMFdeDht/1155-views-and-unique-visitors-is-missing-in-report-editor)', '2023-03-23 08:13:59.279356+00');
INSERT INTO public.common_changetoplatform VALUES (90, 'Friday 24 March 2023', '* Change **View case** to accordion
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/view/#test-results))
[#1134](https://trello.com/c/KV5thjeL/1134-review-case-overview-page-and-add-additional-information-from-the-test-and-report-applications-design-attached)', '2023-03-24 08:31:28.056684+00');
INSERT INTO public.common_changetoplatform VALUES (91, 'Monday 27 March 2023', '* Restructure testing UI to use accordion
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/detail/))
[#1147](https://trello.com/c/SR4xqkKa/1147-update-test-overview-page-with-new-design-design-attached)', '2023-03-27 07:40:39.36299+00');
INSERT INTO public.common_changetoplatform VALUES (92, 'Wednesday 29 March 2023', '* Restructure View 12-week retest page to use accordion
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/audit-retest-detail/))
[#1156](https://trello.com/c/qNnEUhus/1156-update-retest-overview-page-with-new-design-design-attached)
* Add percentages to outstanding issues page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/outstanding-issues/?view=Page%20view))
[#1167](https://trello.com/c/pYabsO8w/1167-add-percentages-to-case-overview-page-design-attached)', '2023-03-28 15:00:40.836727+00');
INSERT INTO public.common_changetoplatform VALUES (93, 'Monday 3 April 2023', '* Move 12-week statement backup field to compliance page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-retest-statement-decision/))
[#1100](https://trello.com/c/Vn95pWV8/1100-move-link-to-12-week-saved-accessibility-statement-only-if-not-compliant-field-to-statement-compliance-decision-page)', '2023-04-03 14:21:29.498356+00');
INSERT INTO public.common_changetoplatform VALUES (94, 'Tuesday 11 April 2023', '* Reformat using upgraded `black` Python code reformatter.
[#1175](https://trello.com/c/gT9nY5vi/1175-black-has-been-updated)', '2023-04-11 10:41:48.907512+00');
INSERT INTO public.common_changetoplatform VALUES (95, 'Wednesday 12 April 2023', '* Add search within case
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/view/))
[#1164](https://trello.com/c/QgYwyrYh/1164-create-search-function-in-case-overview-design-attached)', '2023-04-12 11:01:35.988912+00');
INSERT INTO public.common_changetoplatform VALUES (96, 'Tuesday 18 April 2023', '* Add 12-week retest statement comparison
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-retest-statement-comparison/))
[#1101](https://trello.com/c/U5qUG8l7/1101-create-comparison-page-for-12-week-statement-design-attached)', '2023-04-18 13:36:32.791963+00');
INSERT INTO public.common_changetoplatform VALUES (97, 'Thursday 20 April 2023', '* Add advanced search filter on case updated date
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/?date_type=audit_case__date_of_test&date_start_0=1&date_start_1=1&date_start_2=2023&date_end_0=20&date_end_1=4&date_end_2=2023))
[#1178](https://trello.com/c/drw5erMu/1178-add-case-updated-date-field-to-advanced-search)', '2023-04-20 07:07:17.508681+00');
INSERT INTO public.common_changetoplatform VALUES (99, 'Thursday 11 May 2023', '* Remove edit and reset report
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-publisher/))
[#1148](https://trello.com/c/i82Sk9OP/1148-update-report-overview-page-and-remove-refresh-report-functionality-design-attached)
* Change label to ''For enforcement consideration''
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-case-close/))
[#1201](https://trello.com/c/ItdWznM2/1201-for-enforcement-consideration)', '2023-05-11 07:14:28.159848+00');
INSERT INTO public.common_changetoplatform VALUES (100, 'Friday 12 May 2023', '* Allow users to edit missed or insufficient deadlines on statement in report
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-report-options/))
[#1202](https://trello.com/c/Kg6JvwxC/1202-report-statement-dates)
* Use report issues tables in email template
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/twelve-week-correspondence-email/))
[#1203](https://trello.com/c/8ILumIhN/1203-show-issues-in-email-template)', '2023-05-12 08:46:51.669979+00');
INSERT INTO public.common_changetoplatform VALUES (101, 'Monday 15 May 2023', '* Move contact detail notes to bottom of page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-contact-details/))
[#1205](https://trello.com/c/tleBnjSL/1205-move-contact-notes-field)
* Enable open link widget on retest statement decision page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-retest-statement-decision/))
[#1204](https://trello.com/c/nQj9aE7u/1204-open-link-disabled)
* Redesign QA process page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-qa-process/))
[#1194](https://trello.com/c/1SKMKaeP/1194-update-qa-page-with-new-design-design-attached)', '2023-05-15 10:01:26.898908+00');
INSERT INTO public.common_changetoplatform VALUES (102, 'Tuesday 16 May 2023', '* Include on-call QA on comment notifications
[#1198](https://trello.com/c/0fJjnynI/1198-send-comment-notification-to-the-qa-auditor-on-call)
* Update QA section of home page
([home](https://platform-test.accessibility-monitoring.service.gov.uk/))
[#1195](https://trello.com/c/LKo50vwy/1195-update-qa-section-in-dashboard-design-attached)
* Make topmenu items bold when content exists
[#1195](https://trello.com/c/WixBjeYK/1196-update-how-notifications-work-in-header-design-attached)', '2023-05-16 09:58:53.971676+00');
INSERT INTO public.common_changetoplatform VALUES (109, 'Tuesday 30 May 2023', '* Add issues count and published report to details
(examples
[testing](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-test-results/),
[report](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-report-details/) &
[retest](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-twelve-week-retest/))
[#1222](https://trello.com/c/MW4jZmPA/1222-review-testing-details-report-details-and-retest-details-page-in-test-design-attached)
* Replace document with report in report copy
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-publisher/#report-introduction))
[#1229](https://trello.com/c/plyBJjNF/1229-change-document-to-report)', '2023-05-30 08:47:55.657387+00');
INSERT INTO public.common_changetoplatform VALUES (103, 'Wednesday 17 May 2023', '* Sort pages to end with PDFs followed by statement
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/detail/))
[#1192](https://trello.com/c/IfLdqbhA/1192-put-accessibility-statement-test-at-the-bottom-of-the-test-pages)
* Add links to **View test** and **12-week retest** to *Frequently used links*
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/view/))
[#1179](https://trello.com/c/vgESbVYe/1179-add-link-to-12-retest-in-outstanding-issues-needs-design)
* Allow users to add extra text to the statement section of report
([Report options](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-report-options/),
[Report publisher](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-publisher/))
[#1208](https://trello.com/c/J4QATAVi/1208-extra-statement-text)
* Remove pages missing on retest from outstanding issues
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/outstanding-issues/))
[#1190](https://trello.com/c/S3GtmYg1/1190-removed-pages-should-be-removed-from-the-final-stats-in-outstanding-issues-page)', '2023-05-17 06:54:58.949845+00');
INSERT INTO public.common_changetoplatform VALUES (111, 'Friday 2 June 2023', '* Add field for 7 day no contact email sent
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-report-correspondence/))
[#1082](https://trello.com/c/AlM6A750/1082-add-seven-day-no-contact-details-email-sent-field-in-initial-correspondence)
* Move survey sent field
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-enforcement-body-correspondence/))
[#1232](https://trello.com/c/NFlN3Jho/1232-move-feedback-survey-sent-field)
* Add outstanding issues email
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/outstanding-issues/?view=Page%20view))
[#1221](https://trello.com/c/nnNUM2qt/1221-add-unfixed-issues-email-template-to-outstanding-issues-design-attached)
* Remove automatic update of QA auditor on report approval
[#1226](https://trello.com/c/RkPYLMZB/1226-remove-auto-assign-qa-auditor-when-report-is-approved)', '2023-06-02 07:13:45.683965+00');
INSERT INTO public.common_changetoplatform VALUES (104, 'Thursday 18 May 2023', '* Show results of retest on **Outstanding issues** page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/outstanding-issues/?view=Page%20view))
[#1180](https://trello.com/c/2XvEq0t9/1180-add-12-week-retest-info-to-outstanding-issues)
* Show on-call QA on home page regardless
([home](https://platform-test.accessibility-monitoring.service.gov.uk/))
[#1209](https://trello.com/c/DtGTnEL4/1209-show-on-call-qa)
* Upgrade GDS Design System to 4.6.0
[#1189](https://trello.com/c/AIrOijyC/1189-upgrade-gds-design-system-to-460)', '2023-05-18 07:37:15.047816+00');
INSERT INTO public.common_changetoplatform VALUES (105, 'Tuesday 23 May 2023', '* Remove report links from QA section of View case page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/view/#report-details))
[#1172](https://trello.com/c/Zmp8yqAb/1172-review-how-qa-case-overview-page-represents-links-to-the-report)', '2023-05-23 13:48:44.46942+00');
INSERT INTO public.common_changetoplatform VALUES (106, 'Wednesday 24 May 2023', '* Remove CSV export from View case page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/view/))
[#1219](https://trello.com/c/OkFNCF95/1219-remove-export-to-csv-button-at-case-level)', '2023-05-24 10:30:52.138864+00');
INSERT INTO public.common_changetoplatform VALUES (107, 'Thursday 25 May 2023', '* Remove `read_notification` templatetag
[#1225](https://trello.com/c/TuevVpdf/1225-remove-read-notification-template-tag)', '2023-05-25 10:42:19.097655+00');
INSERT INTO public.common_changetoplatform VALUES (110, 'Thursday 1 June 2023', '* Add extra line of help text to field
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-twelve-week-correspondence/))
[#1073](https://trello.com/c/bJnH0QIA/1073-add-help-text-to-12-week-update-requested-image-attached)
* Add field to record if a feedback survey has been sent
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-case-details/))
[#1144](https://trello.com/c/H9AnU7N4/1144-add-option-for-tracking-which-cases-have-had-feedback-sent-design-attached)
* Add more prominent link to published report
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/3/report-publisher/))
[#1207](https://trello.com/c/LqIPAW5l/1207-add-link-to-published-report-in-the-top-row-of-links-design-attached)', '2023-06-01 07:11:20.97695+00');
INSERT INTO public.common_changetoplatform VALUES (108, 'Friday 26 May 2023', '* Restore preferred contact UI
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-contact-details/))
[#1227](https://trello.com/c/yVNSJmJ0/1227-re-add-preferred-contact-field-design-attached)
* Show outstanding issues in case overview
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/view/))
[#1220](https://trello.com/c/fVeCqNH1/1220-add-website-and-statement-issues-to-case-overview-section-design-attached)', '2023-05-26 09:19:09.680816+00');
INSERT INTO public.common_changetoplatform VALUES (112, 'Monday 5 June 2023', '* Move links to edit derived dates to be inline with page flow
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-report-correspondence/))
[#1087](https://trello.com/c/wsyWhnfv/1087-combine-correspondence-due-dates-into-one-page)', '2023-06-05 10:15:22.968942+00');
INSERT INTO public.common_changetoplatform VALUES (113, 'Tuesday 6 June 2023', '* Add unresponsive column to equality body CSV
[#1102](https://trello.com/c/VPLY31KN/1102-add-psb-is-unrepsonsive-column-in-eb-csv-export)
* Simplify initial website compliance decision choices
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-website-decision/))
[#534](https://github.com/alphagov/accessibility-monitoring-platform/pull/297)', '2023-06-06 10:57:09.272854+00');
INSERT INTO public.common_changetoplatform VALUES (114, 'Thursday 8 June 2023', '* Redirect to closing case when PSB is unresponsive
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/edit-no-psb-response/))
[#1119](https://trello.com/c/KQydfqYl/1119-skip-to-closing-the-case-when-psb-dont-respond-and-update-status-logic)', '2023-06-08 13:24:43.98393+00');
INSERT INTO public.common_changetoplatform VALUES (115, 'Friday 16 June 2023', '* Add banner to report warning of outage 10-14 July 2023
([example](https://reports-test.accessibility-monitoring.service.gov.uk/reports/5e57995b-9935-4ad6-a831-5882cef64706))
[#1235](https://trello.com/c/F0wbcWqO/1235-add-banner-to-warn-public-orgs-about-the-site-going-down-during-cloud-migration-design-attached)', '2023-06-16 07:13:16.796171+00');
INSERT INTO public.common_changetoplatform VALUES (117, 'Wednesday 21 June 2023', '* Add link to email template to **12-week pages comparison** page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/20/edit-audit-retest-pages/))
[#1259](https://trello.com/c/vLjYOsuw/1259-add-link-to-email-template)
* Add another link to the latest HTML report
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/509/view/))
[#1247](https://trello.com/c/LVldHokh/1247-make-it-easier-to-get-to-the-published-report-design-attached)', '2023-06-21 07:11:24.748482+00');
INSERT INTO public.common_changetoplatform VALUES (125, 'Thursday 6 July 2023', '* Remove number of ODT from report metrics
([report metrics](https://platform-test.accessibility-monitoring.service.gov.uk/common/metrics-report/))
[#1275](https://trello.com/c/n3XbOFTI/1275-remove-odt-report-metrics)', '2023-07-06 15:34:09.649799+00');
INSERT INTO public.common_changetoplatform VALUES (118, 'Thursday 22 June 2023', '* Add position field to statement checks to control display order
[#1263](https://trello.com/c/PYFBRjQU/1263-add-position-to-statement-checks-to-control-their-order-in-the-ui)
* Add boilerplate to *What to do next* section of report
[#1262](https://trello.com/c/9JBmQjGb/1262-add-boilerplate-to-what-to-do-next)
* Build prototype of new statement test process
[#1177](https://trello.com/c/vdgxa61U/1177-prototype-statement-test)
* Outstanding statement issues
[#1252](https://trello.com/c/9LtdE49H/1252-outstanding-statement-issues)
* Calculate case status with new statement process
[#1254](https://trello.com/c/E4FXbgys/1254-calculate-case-status-with-new-statement-process)
* Add custom issues to UI
[#1249](https://trello.com/c/ippEXh9c/1249-create-ui-to-add-custom-rows-to-the-statement-table-design-attached)
* Update overview page with new statement process
[#1212](https://trello.com/c/qGHLzn9q/1212-implement-case-overview-page-with-the-new-statement-assessment-process-design-attached)
* Update statement outstanding issues
[#1213](https://trello.com/c/XKCO7XtV/1213-implement-outstanding-issues-pages-with-new-statement-assessment-process-design-attached)
* Add new statement checks to email template
[#1216](https://trello.com/c/urEECfOh/1216-add-statement-issues-to-email-template-design-attached)
* Show new statement results in summary and report
[#1210](https://trello.com/c/Locokgxz/1210-finalise-statement-assessment-design-for-published-report-design-attached)', '2023-06-22 10:00:47.792359+00');
INSERT INTO public.common_changetoplatform VALUES (119, 'Friday 23 June 2023', '* Use `get_absolute_url` methods; Refactor breadcrumbs; Update Django admin.
[#1264](https://trello.com/c/AnihwcB9/1264-add-absolute-urls)', '2023-06-23 14:32:59.389144+00');
INSERT INTO public.common_changetoplatform VALUES (127, 'Tuesday 18 July 2023', '* Fix spelling of "statment"
[#1298](https://trello.com/c/lgsv4g09/1289-misspelled-statment)', '2023-07-18 12:08:58.425673+00');
INSERT INTO public.common_changetoplatform VALUES (120, 'Monday 26 June 2023', '* Add percentage of issues fixed to CSV exports
[#1268](https://trello.com/c/AN2sxnvo/1268-add-issues-percentage-to-csvs)
* Show/hide links to Report options/Statement overview in Report publisher
([example](https://platform-test.accessibility-monitoring.service.gov.uk/reports/14/report-publisher/))
[#1265](https://trello.com/c/3uYh2vVB/1265-report-options-still-in-report-wrapper)', '2023-06-26 07:56:41.227685+00');
INSERT INTO public.common_changetoplatform VALUES (121, 'Tuesday 27 June 2023', '* Show only unfixed statement content check results on Outstanding issues page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/522/outstanding-issues/?view=Page%20view))
[#1269](https://trello.com/c/MesXBm51/1269-show-no-and-not-tested-outstanding-issues)', '2023-06-27 07:21:06.456599+00');
INSERT INTO public.common_changetoplatform VALUES (122, 'Wednesday 28 June 2023', '* Fix pagination in Statement and WCAG issues lists
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/statement-check-list/))
[#1270](https://trello.com/c/VuW13gmn/1270-broken-pagination)', '2023-06-28 13:49:09.411367+00');
INSERT INTO public.common_changetoplatform VALUES (123, 'Friday 30 June 2023', '* Split contents of Outstanding issues page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/cases/522/outstanding-issues/?view=Page%20view))
[#1271](https://trello.com/c/VWVg6RnH/1271-split-outstanding-issues)', '2023-06-30 10:53:15.842483+00');
INSERT INTO public.common_changetoplatform VALUES (124, 'Monday 3 July 2023', '* Sort cases by default into unassigned first
([search](https://platform-test.accessibility-monitoring.service.gov.uk/cases/))
[#1272](https://trello.com/c/88lEt6FQ/1272-sort-unassigned-cases-first-by-default)
* Update Django to version 4.1.10
[#1273](https://trello.com/c/YR1ImxEy/1273-upgrade-django-to-4110)', '2023-07-03 07:18:51.417974+00');
INSERT INTO public.common_changetoplatform VALUES (128, 'Friday 21 July 2023', '* Add status page to report viewer
([PaaS](https://accessibility-monitoring-report-viewer-test.london.cloudapps.digital/reports/status),
[AWS](https://reports-test.accessibility-monitoring.service.gov.uk/reports/ststus))
[#1291](https://trello.com/c/x4ON0XNy/1291-add-status-page-to-report-viewer)', '2023-07-21 15:56:39.790378+00');
INSERT INTO public.common_changetoplatform VALUES (126, 'Friday 7 July 2023', '* Remove **Report text** page
([example](https://platform-test.accessibility-monitoring.service.gov.uk/audits/7/detail/#audit-report-text))
[#1276](https://trello.com/c/fKlAFzeU/1276-remove-report-text-page)
* Update Django-axes configuration
[#1274](https://trello.com/c/mSVxj0lk/1274-review-usage-of-django-axes)
* Upgrade python package `django-two-factor-auth`
[#1171](https://trello.com/c/Pxzbushr/1171-investigate-why-django-two-factor-auth-wont-pass-unit-tests)
* Remove `Contact.notes` field
[#1188](https://trello.com/c/GOxtZ925/1188-delete-contactnotes)
* Update report viewer outage warning
([example](https://reports-test.accessibility-monitoring.service.gov.uk/reports/1466a08f-b18d-4e7b-bfb3-d4d75275c878))
[#1278](https://trello.com/c/AKsaViPL/1278-update-report-viewer-outage-warning)', '2023-07-07 11:37:40.350457+00');
INSERT INTO public.common_changetoplatform VALUES (129, 'Tuesday 25 July 2023', '* Upgrade Django to version 4.2.2.
[#1238](https://trello.com/c/ghAr6uJF/1238-upgrade-django-to-422)
* Upgrade GDS design system to 4.7.0.
[#1277](https://trello.com/c/Pm03I2lR/1277-upgrade-gds-design-system-to-470)', '2023-07-25 15:56:39.790378+00');

"""
ISSUE_SQL: str = """
DELETE FROM public.common_issuereport;
INSERT INTO public.common_issuereport VALUES (7, '/cases/116/edit-report-correspondence/', 'Edit case | Report correspondence', 'Wording:
12 week update

Should be:
12 week deadline', '2021-08-27 12:39:20.355211+00', 3, true, 'done', '294');
INSERT INTO public.common_issuereport VALUES (8, '/cases/116/edit-twelve-week-correspondence/', 'Edit case | 12 week correspondence', 'wording:
12 week update

Should read
12 week deadline', '2021-08-27 12:40:01.307839+00', 3, true, '', '294');
INSERT INTO public.common_issuereport VALUES (16, '/cases/116/edit-enforcement-body-correspondence/', 'Edit case | Equality body correspondence', 'on this page we would like a place to add

Enforement body interested in case', '2021-08-27 13:05:58.749051+00', 3, true, '', 'https://trello.com/c/cHPeADlW/298-new-field-edit-case-equality-body-correspondence-would-like-a-place-to-add-enforcement-body-interested-in-the-case');
INSERT INTO public.common_issuereport VALUES (9, '/cases/116/edit-twelve-week-correspondence/', 'Edit case | 12 week correspondence', 'Remove under Mark this page as completed

this wording:
12 week correspondence completed?', '2021-08-27 12:41:55.396021+00', 3, true, 'changed wording mark as complete', '303');
INSERT INTO public.common_issuereport VALUES (10, '/cases/116/edit-final-decision/', 'Edit case | Final decision', 'need to review link to test results:

Retested website?
The retest form can be found in the test results

Might need link to report or to new template or to the folder? discuss with auditors', '2021-08-27 12:47:42.110347+00', 3, true, 'https://trello.com/c/UCC2uHRm/295-need-review-hold-edit-case-final-decision-link-to-test-doc', 'https://trello.com/c/UCC2uHRm/295-need-review-hold-edit-case-final-decision-link-to-test-doc');
INSERT INTO public.common_issuereport VALUES (11, '/cases/116/edit-final-decision/', 'Edit case | Final decision', 'Further requirement:

We need a link to saved statement if not compliant at time of testing
- future solution, save screeshot', '2021-08-27 12:54:08.108671+00', 3, true, '', 'https://trello.com/c/4Sacrymi/301-new-features-field-for-accessibility-statement-screenshot');
INSERT INTO public.common_issuereport VALUES (12, '/cases/116/edit-final-decision/', 'Edit case | Final decision', 'Further requirement:

final statement decision  > No > need to prompt you to save it', '2021-08-27 12:55:09.682831+00', 3, true, 'no action', '');
INSERT INTO public.common_issuereport VALUES (13, '/cases/116/edit-final-decision/', 'Edit case | Final decision', 'remove radio button (not needed)

Partially compliant', '2021-08-27 12:56:25.738213+00', 3, true, 'done', '');
INSERT INTO public.common_issuereport VALUES (14, '/cases/116/edit-final-decision/', 'Edit case | Final decision', 'Final accessibility statement decision
Compliant
Partially compliant
Not compliant
Missing accessibility statement
Not known


Wording and radio button need to change yo
no further action
other
N/a or none not started', '2021-08-27 12:59:37.959238+00', 3, true, '', '331');
INSERT INTO public.common_issuereport VALUES (15, '/cases/116/edit-final-decision/', 'Edit case | Final decision', 'wording need to be reviewed (ask auditors):
The case requires no further action', '2021-08-27 13:02:02.907816+00', 3, true, '', 'https://trello.com/c/lrOBXkeA/333-update-final-compliance-decision-to-enforcement-recommendation');
INSERT INTO public.common_issuereport VALUES (17, '/cases/116/edit-test-results/', 'Edit case | Testing details', 'remove the radio button

Partially compliant', '2021-08-27 13:31:49.228523+00', 3, true, 'done', '');
INSERT INTO public.common_issuereport VALUES (18, '/cases/116/edit-final-decision/', 'Edit case | Final decision', 'add hint text in grey under:
Final accessibility statement notes

Hint text
If non compliant also add link to copy of non compliant accessibility statement', '2021-08-27 15:01:30.515412+00', 3, true, 'help text 304', 'https://trello.com/c/4Sacrymi/301-new-features-field-for-accessibility-statement-screenshot');
INSERT INTO public.common_issuereport VALUES (19, '/cases/105/edit-test-results/', 'Edit case | Testing details', '(Think Kelly also raised this)

The compliance statuses relate to 12 weeks ones that we discussed in the google chat, not test ones. Should be changed back', '2021-09-02 09:42:45.053502+00', 10, true, 'done with meeting review', '');
INSERT INTO public.common_issuereport VALUES (20, '/cases/105/edit-test-results/', 'Edit case | Testing details', 'If the statement is compliant, and the website is compliant we don''t write a report or send any correspondence.

As a future improvement could we look at scenarios so the workflow is smarter e.g. if both of those were marked as compliant, the rest of the workflow is greyed out and you move straight to closing it

We''d need to carefully think of all the scenarios to get it right though', '2021-09-02 09:49:42.975131+00', 10, true, '', 'https://trello.com/c/4OUBAaGs/342-new-feature-nice-to-have-website-fully-compliant-move-to-final-state');
INSERT INTO public.common_issuereport VALUES (21, '/', 'Your cases', 'What does ''In probation period'' mean? We don''t use that language', '2021-09-02 11:27:19.216936+00', 10, true, 'https://trello.com/c/ZBNBK8Wc/337-review-with-auditors-at-the-end-of-the-day', '');
INSERT INTO public.common_issuereport VALUES (22, '/cases/479/edit-final-decision/', 'Edit case | Final decision', 'I have a query about the wording of the last question: "Case completed and needs to be sent to EHRC or ECNI?" Yes or No

I read it as a two part question:
- Is the case completed?
- Does it need to be sent to EHRC/ECNI?


I would like it to be put to the auditors to see if they find it ambiguous', '2021-09-13 13:19:25.795505+00', 10, true, 'The sentence has been reviewed by Kevin, We will leave it for a while and see if needs review in the future', '');
INSERT INTO public.common_issuereport VALUES (23, '/', 'All cases', 'Looking at the accessibility of the cases table (specifically in View all cases > Report sent), it looks pretty good to me, but at 400% zoom, the table does not reflow very well as per https://www.w3.org/WAI/WCAG21/Understanding/reflow.html , because the new icons overlap the 2nd column.

The ideal situation would be for the table to responsively flex at high zoom levels, presenting each cell on top of each other rather than squashing it up in one row... however the Design System examples do not currently do this (sad face).

However the minimum requirement is that content is visible at 400% zoom without horizontal scrolling. Whole tables are exempt from this (so it would be OK to scroll right to see more cells), but individual cells still need to be readable at 400% zoom.

Hope that makes sense but happy to discuss! Andrew', '2021-09-27 11:59:09.943844+00', 17, true, 'Fix for the ! (exclamation mark) 413
responsiveness need to talk to Chris 05.10 talked to Chris. It''s not priority to have platform responsive', '413');
INSERT INTO public.common_issuereport VALUES (24, '/cases/243/edit-report-details/', 'Northern Ireland Housing Executive | Edit case | Report details', 'On the new comments field, if there''s one comment, the heading shows "1 comments" - can it show "comment" if there''s just one?', '2021-09-27 12:07:44.622682+00', 17, true, '', '414');
INSERT INTO public.common_issuereport VALUES (25, '/cases/243/edit-report-details/', 'Northern Ireland Housing Executive | Edit case | Report details', 'It looks like the comment anchors aren''t in sync if comments have been edited or deleted. For example, the link under the first comment on the Northern Ireland Housing Executive is https://accessibility-monitoring-platform-test.london.cloudapps.digital/cases/243/edit-report-details/#comments7 . However, possibly because I have added, edited and removed some comments, the first comment''s heading currently has id comment1. It looks like a really nice feature though so please keep it! Thanks, Andrew', '2021-09-27 12:15:50.401243+00', 17, true, '', '415');
INSERT INTO public.common_issuereport VALUES (26, '/cases/487/edit-report-details/', 'Django | Edit case | Report details', 'I''m a little unclear what ''link this comment'' does. Is it a copy link to clipboard? I personally don''t think I''d use this as I''d just copy the URL from the address bar.', '2021-09-29 09:16:47.770449+00', 12, true, '', '416');
INSERT INTO public.common_issuereport VALUES (28, '/cases/486/edit-test-results/', 'New council that shows statuses | Edit case | Testing details', 'Is it possible to get from an ''edit'' page back to the view case overview page?', '2021-09-29 09:32:34.194438+00', 12, true, 'added to the frequently used links', '416');
INSERT INTO public.common_issuereport VALUES (29, '/cases/213/edit-report-details/', 'Secret Intelligence Service | Edit case | Report details', 'can the edit and remove comment button become links instead of buttons ?', '2021-09-30 14:36:15.277312+00', 3, true, 'close as feedback only from me. will raise again if auditors feel the same', '');
INSERT INTO public.common_issuereport VALUES (30, '/cases/364/edit-report-details/', 'Engineering Construction Industry Training Board | Edit case | Report details', 'Reviewing this with Auditors:
notification look good but would be helpful to have the comment in the email - not descriptive or informative enough

one email per comment is fine tho', '2021-10-04 15:28:45.619131+00', 3, true, '', '423');
INSERT INTO public.common_issuereport VALUES (31, '/', 'All cases', 'I can''t see it as I don''t have cases, but auditors felt the naming "step progress" wasn''t clear. Any reason why it''s not called "Next step"?', '2021-10-05 07:25:08.637553+00', 3, true, 'checking with auditor again', '');
INSERT INTO public.common_issuereport VALUES (32, '/', 'Your cases', 'Same can''t see as no cases:

under status "Report sent" the next step is "sent 4 week chaser" for example.

under status Report acknowledged waiting for 12 week deadline the next step is called the same or similar and it''s confusing', '2021-10-05 07:27:48.892849+00', 3, true, 'checking with auditor again', '');
INSERT INTO public.common_issuereport VALUES (33, '/cases/235/edit-twelve-week-correspondence/', 'British Film Institute | Edit case | 12 week correspondence', 'there is something about the order on the right hand side that doesn''t seem right. maybe a spacing between the frequent link and status? maybe the status at the top as currently under page fold?', '2021-10-05 07:36:36.116998+00', 3, true, '', '425');
INSERT INTO public.common_issuereport VALUES (35, '/cases/493/edit-test-results/', 'perfect site organisation | Edit case | Testing details', 'if I mark both as compliant - I don''t know what to do. How can the auditor know that she/he has to go to final decision and mark as Do not sent to EHRC.

What was the reason for not automating?', '2021-10-18 15:22:56.022493+00', 3, true, 'See https://accessibility-monitoring-platform-test.london.cloudapps.digital/admin/common/issuereport/34/change/', '');
INSERT INTO public.common_issuereport VALUES (36, '/cases/308/view/', 'The Wallace Collection | View case', 'On the dashboard I''ve started seeing some extra fields this afternoon (25 Oct). For example on the Wallace Collection there are several fields with None on the left hand side and 3 on the right hand side. They''re not in the way particularly but I wondered if they were meant to be hidden? It also happens with the Northern Ireland Housing Executive and the number 14.', '2021-10-25 13:23:32.700548+00', 17, true, 'That was me. I forgot to exclude the new version field in the forms from the View case page where the form fields are used to build the output. Fixed in #457.', '');
INSERT INTO public.common_issuereport VALUES (37, '/cases/220/edit-no-psb-response/', 'The Investigatory Powers Tribunal | Edit case | Public sector body is unresponsive', 'Can we prioritise getting a notes field here that also appears in the export for EHRC so that we have context on why these cases are marked as ''ready to send'' but don''t have any data in them?', '2021-10-27 11:04:45.27568+00', 10, true, '', '465');
INSERT INTO public.common_issuereport VALUES (34, '/cases/493/edit-final-decision/', 'perfect site organisation | Edit case | Final decision', 'the help text says
The case can be marked as completed with no further action.

but you can;''t mark as complete.', '2021-10-18 15:16:50.233913+00', 3, true, 'This was about the following warning text on the Final decision page (when website and statement are both compliant):

The public sector body website is compliant and has no issues with the accessibility statement. The case can be marked as completed with no further action.', '');
INSERT INTO public.common_issuereport VALUES (27, '/cases/487/edit-report-details/', 'Django | Edit case | Report details', 'I don''t think we need the "QA notes" text box if we have discussion section now? Personally I would just put any comments as a discussion.', '2021-09-29 09:29:54.138583+00', 12, true, 'taking to the auditor review

9-11 changing QA process. will review again', '');
INSERT INTO public.common_issuereport VALUES (39, '/audits/pages/63/edit-audit-page-checks/', 'Butterfield Council | Testing Butterfield Council', 'AH: I''m trying to use the ''search WCAG error'' functionality but when I type anything in and press Enter, for example ''keyboard'', it just disappears again and no filter appears to have been applied. Am I doing it wrong?', '2022-01-28 13:51:53.180907+00', 17, true, 'Paul talked to Andrew - this is resolved', '539');
INSERT INTO public.common_issuereport VALUES (40, '/audits/11/edit-audit-statement-two/', 'Butterfield Council | Accessibility statement Pt. 2', 'AH: Not a bug but a change request: can the whole text underneath "Example of method" please be replaced with:

Indicate the method used to evaluate the site''s accessibility, such as a self-assessment or third-party certification.

This is something we agreed among the detailed testers yesterday, as we realised that we were being too strict enforcing this part of the statement. Please let me know when updated so that I can update the team.', '2022-01-28 13:59:05.537286+00', 17, true, '', '540');
INSERT INTO public.common_issuereport VALUES (38, '/audits/5/edit-audit-report-options/', 'Arts Council of Northern Ireland | Report options', 'What plans are there to make this page ''smart''? The options depend on what you marked as wrong in the test and could potentially all be mapped to previous questions with a little rejig

e.g.
If you marked it failed the requirement to be on the home page or in the footer then you need the wording that says so.
Similarly, the platform already knows if you found errors or not so why do you have to mark that?
If you marked there was a disproportionate burden in the statement section then you (most likely) need the disproportionate burden wording.

Obviously we would need to be able to amend or add free text but for the majority of reports it would save a lot time.

I''d hoped it would be more automated. As it stands, you have to remember what you put on a previous page in order to choose the right options and it seems messy having to flip back and forth to remember.', '2022-01-27 14:40:41.090931+00', 10, false, 'Leave for now - will address in the future', '');
INSERT INTO public.common_issuereport VALUES (41, '/cases/492/edit-final-statement/', 'Derby City Council Test new case | Final accessibility statement compliance decision', 'Trying to play with the statuses to figure out why disproportionate burden changes anything and its gone to ''Unknown'' and not sure why', '2022-02-24 17:22:14.321765+00', 8, true, 'possible bug', '578');
INSERT INTO public.common_issuereport VALUES (42, '/cases/242/edit-enforcement-body-correspondence/', 'Committee on Climate Change | Equality body correspondence', 'What does the case updated field mean - that we need to send it to EHRC or when the PSB gets in touch? Makes more sense to be on the same page as the summary?', '2022-03-01 10:23:10.109741+00', 8, true, '', '579');
INSERT INTO public.common_issuereport VALUES (43, '/audits/all-issues/', 'All Issues page', 'The following issue description has two consecutive full stops:

WCAG 2.4.4 Link Purpose (In Context) and WCAG 4.1.2 Name, Role, Value: Links must have discernible text.. Issue found using Deque Axe.', '2022-07-29 10:08:47.046397+00', 17, true, 'Fixed using the new https://accessibility-monitoring-platform-test.london.cloudapps.digital/audits/wcag-definition-list

Demoed the fix in a standup on 29 July 2022.', '');
INSERT INTO public.common_issuereport VALUES (44, '/cases/509/view/', 'All WCAG definitions | View case', 'Nesha has said:

I kept missing that the axe error automatically uploads underneath as you search in the search bar and I think this is because the search check boxes, together with the headers etc take up too much space. I only noticed once I asked Keeley if it was possible to search. We discussed this briefly with Katherine and agreed it would be helpful if this was a bit smaller.', '2023-01-19 11:22:08.159008+00', 2, true, '', 'https://trello.com/c/s7Qb3sQI/1089-make-filter-options-in-test-ui-smaller');
"""


def populate_versions_and_issues(
    apps, schema_editor
):  # pylint: disable=unused-argument
    """Populate changetoplatform and issuereport tables on test platform"""
    amp_viewer_domain: str = os.getenv("AMP_VIEWER_DOMAIN", "")
    if amp_viewer_domain == "reports-test.accessibility-monitoring.service.gov.uk":
        cursor = connection.cursor()
        cursor.execute(VERSION_SQL)
        cursor.execute(ISSUE_SQL)


def nop(apps, schema_editor):  # pylint: disable=unused-argument
    """Do nothing"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_frequentlyusedlink"),
    ]

    operations = [migrations.RunPython(populate_versions_and_issues, reverse_code=nop)]
