# Generated by Django 6.0.1 on 2026-02-23 14:29

from django.db import migrations


def populate_email_templates(apps, schema_editor):  # pylint: disable=unused-argument
    EmailTemplate = apps.get_model("common", "EmailTemplate")
    email_template_d3 = EmailTemplate.objects.filter(
        template_name="d3-initial-contact-chaser"
    ).first()
    if email_template_d3 is None:
        return  # In test environment
    EmailTemplate.objects.create(
        name="3a. Initial contact - First chaser",
        template_name="d3a-initial-contact-chaser",
        is_detailed=True,
        is_mobile=True,
        created_by=email_template_d3.created_by,
        updated_by=email_template_d3.updated_by,
        position=250,
    )
    EmailTemplate.objects.create(
        name="3b. Initial contact - Follow up chaser",
        template_name="d3b-initial-contact-chaser",
        is_detailed=True,
        is_mobile=True,
        created_by=email_template_d3.created_by,
        updated_by=email_template_d3.updated_by,
        position=255,
    )
    email_template_d3.is_deleted = True
    email_template_d3.save()

    email_template_d8 = EmailTemplate.objects.get(
        template_name="d8-12-week-7-day-chaser"
    )
    EmailTemplate.objects.create(
        name="8a. 12 weeks - 7 day chaser - First chaser",
        template_name="d8a-12-week-7-day-chaser",
        is_detailed=True,
        is_mobile=True,
        created_by=email_template_d8.created_by,
        updated_by=email_template_d8.updated_by,
        position=300,
    )
    EmailTemplate.objects.create(
        name="8b. 12 weeks - 7 day chaser - Follow up chaser",
        template_name="d8b-12-week-7-day-chaser",
        is_detailed=True,
        is_mobile=True,
        created_by=email_template_d8.created_by,
        updated_by=email_template_d8.updated_by,
        position=305,
    )
    email_template_d8.is_deleted = True
    email_template_d8.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    EmailTemplate = apps.get_model("common", "EmailTemplate")
    email_template_d3 = EmailTemplate.objects.filter(
        template_name="d3-initial-contact-chaser"
    ).first()
    if email_template_d3 is None:
        return  # In test environment
    email_template_d3.is_deleted = False
    email_template_d3.save()
    EmailTemplate.objects.get(template_name="d3a-initial-contact-chaser").delete()
    EmailTemplate.objects.get(template_name="d3b-initial-contact-chaser").delete()
    email_template_d8 = EmailTemplate.objects.get(
        template_name="d8-12-week-7-day-chaser"
    )
    email_template_d8.is_deleted = False
    email_template_d8.save()
    EmailTemplate.objects.get(template_name="d8a-12-week-7-day-chaser").delete()
    EmailTemplate.objects.get(template_name="d8b-12-week-7-day-chaser").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_port_non_case_events"),
    ]

    operations = [
        migrations.RunPython(populate_email_templates, reverse_code=reverse_code),
    ]
