# Generated by Django 6.1.1 on 2026-10-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_add_update_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="changetoplatform",
            name="date_of_change",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="changetoplatform",
            name="version",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="changetoplatform",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
