# Generated by Django 4.2.4 on 2023-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0016_populate_test_versions_issues"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(blank=True, default="")),
                ("url", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name="issuereport",
            options={"ordering": ["-id"]},
        ),
    ]
