# Generated by Django 4.2.4 on 2023-11-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_footerlink_alter_issuereport_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
