# Generated by Django 4.2.4 on 2023-11-15 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0018_subcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={"ordering": ["name"], "verbose_name_plural": "Sub categories"},
        ),
    ]
