# Generated by Django 5.0.4 on 2024-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0019_alter_subcategory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuereport",
            options={"ordering": ["-issue_number"]},
        ),
        migrations.AddField(
            model_name="issuereport",
            name="issue_number",
            field=models.IntegerField(default=1),
        ),
    ]
