# Generated by Django 5.0.4 on 2024-04-17 08:16

from django.db import migrations


def populate_issue_numbers(apps, schema_editor):  # pylint: disable=unused-argument
    IssueReport = apps.get_model("common", "IssueReport")
    for issue_report in IssueReport.objects.all():
        issue_report.issue_number = issue_report.id
        issue_report.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_alter_issuereport_options_issuereport_issue_number"),
    ]

    operations = [
        migrations.RunPython(populate_issue_numbers, reverse_code=reverse_code),
    ]
