# Generated by Django 5.0.4 on 2024-04-19 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0021_populate_issue_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="Default")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("complex", "Complex"),
                        ],
                        default="simple",
                        max_length=20,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("12-week-request", "12-week update request"),
                            ("outstanding-issues", "Outstanding issues"),
                            ("equality-body-retest", "Equality body retest"),
                        ],
                        default="default",
                        max_length=50,
                    ),
                ),
                ("template", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
