# Generated by Django 4.2.8 on 2024-01-05 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# accessibility_monitoring_platform.apps.comments.migrations.0007_comment_history_events


class Migration(migrations.Migration):
    replaces = [
        ("comments", "0001_initial"),
        ("comments", "0002_rename_endpoint_comments_path"),
        ("comments", "0003_auto_20220127_1444"),
        ("comments", "0004_rename_comments_comment_and_more"),
        ("comments", "0005_alter_comment_path"),
        ("comments", "0006_alter_comment_options_remove_comment_page_and_more"),
        ("comments", "0007_comment_history_events"),
        ("comments", "0008_delete_commenthistory"),
        ("comments", "0009_rename_updated_date_comment_updated"),
    ]

    initial = True

    dependencies = [
        ("cases", "0011_remove_case_is_website_compliant_final"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("cases", "0022_auto_20220127_1444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0037_remove_contact_first_name_remove_contact_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("before", models.TextField()),
                ("after", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comment",
                        to="comments.comments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment history",
                "verbose_name_plural": "Comment histories",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comment_case",
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poster_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_date"],
            },
        ),
        # migrations.RunPython(
        #     code=accessibility_monitoring_platform.apps.comments.migrations.0007_comment_history_events.convert_comment_history,
        #     reverse_code=accessibility_monitoring_platform.apps.comments.migrations.0007_comment_history_events.delete_comment_events,
        # ),
        migrations.DeleteModel(
            name="CommentHistory",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="updated_date",
            new_name="updated",
        ),
    ]
