# Generated by Django 4.1a1 on 2022-06-27 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0037_remove_contact_first_name_remove_contact_last_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0003_auto_20220127_1444"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.RenameModel(
            old_name="CommentsHistory",
            new_name="CommentHistory",
        ),
        migrations.AlterModelOptions(
            name="commenthistory",
            options={
                "verbose_name": "Comment history",
                "verbose_name_plural": "Comment histories",
            },
        ),
    ]
