# Generated by Django 5.2.3 on 2025-08-21 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_alter_basecase_status"),
        ("comments", "0004_remove_comment_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="base_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comment_basecase",
                to="cases.basecase",
            ),
        ),
    ]
