# Generated by Django 5.2.3 on 2025-08-21 13:01

from django.db import migrations


def populate_base_case(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")
    Comment = apps.get_model("comments", "Comment")
    for count, simplified_case in enumerate(
        SimplifiedCase.objects.all().order_by("id"), start=1
    ):
        print(f"{count}: Migrating Comments Case number {simplified_case.case_number}")
        for comment in Comment.objects.filter(simplified_case_id=simplified_case.id):
            comment.base_case_id = simplified_case.basecase_ptr
            comment.save()


def reverse_code(apps, schema_editor):
    Comment = apps.get_model("comments", "Comment")
    Comment.objects.all().update(base_case_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_comment_base_case"),
        ("simplified", "0003_populate_simplified_cases"),
    ]

    operations = [
        migrations.RunPython(populate_base_case, reverse_code=reverse_code),
    ]
