# Generated by Django 5.2.3 on 2025-08-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0006_populate_base_case"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="simplified_case",
        ),
    ]
