# Generated by Django 4.1.4 on 2023-03-13 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0008_delete_commenthistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="updated_date",
            new_name="updated",
        ),
    ]
