# Generated by Django 4.1.4 on 2023-03-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0008_delete_commenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
