# Generated by Django 5.0.3 on 2024-03-15 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0088_case_equality_body_notes"),
        ("comments", "0009_rename_updated_date_comment_updated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="type",
            field=models.CharField(
                choices=[("qa", "QA"), ("export", "Equality body export")],
                default="qa",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("qa-comment", "QA comment"),
                            ("report-approved", "Report approved"),
                            ("reminder", "Reminder"),
                        ],
                        default="qa-comment",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(default="")),
                ("read", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cases.case"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comments.comment",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
