# Generated by Django 5.0.3 on 2024-03-15 14:22

from django.db import migrations


def populate_alerts(apps, schema_editor):  # pylint: disable=unused-argument
    Alert = apps.get_model("comments", "Alert")
    Notification = apps.get_model("notifications", "Notification")
    Reminder = apps.get_model("reminders", "Reminder")
    for notification in Notification.objects.all():
        split_path = notification.path.split("/")
        type = (
            "report-approved"
            if "report-approved" in notification.path
            else "qa-comment"
        )
        alert = Alert.objects.create(
            type=type,
            case_id=split_path[2],
            target_user=notification.user,
            message=notification.body,
            read=notification.read,
        )
        alert.created = notification.created_date
        alert.save()
    for reminder in Reminder.objects.all():
        alert = Alert.objects.create(
            type="reminder",
            case=reminder.case,
            target_user=reminder.case.auditor,
            message=reminder.description,
            due_date=reminder.due_date,
            is_deleted=reminder.is_deleted,
        )
        if reminder.updated:
            alert.created = reminder.updated
            alert.updated = reminder.updated
            alert.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    Alert = apps.get_model("comments", "Alert")
    Alert.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0010_comment_type_alert"),
    ]

    operations = [
        migrations.RunPython(populate_alerts, reverse_code=reverse_code),
    ]
