# Generated by Django 5.2.1 on 2025-05-21 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0008_delete_event"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailedCase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("case_number", models.IntegerField(default=1)),
                ("created", models.DateTimeField(blank=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("home_page_url", models.TextField(blank=True, default="")),
                ("domain", models.TextField(blank=True, default="")),
                ("organisation_name", models.TextField(blank=True, default="")),
                (
                    "psb_location",
                    models.CharField(
                        choices=[
                            ("england", "England"),
                            ("scotland", "Scotland"),
                            ("wales", "Wales"),
                            ("northern_ireland", "Northern Ireland"),
                            ("uk_wide", "UK-wide"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "enforcement_body",
                    models.CharField(
                        choices=[
                            ("ehrc", "Equality and Human Rights Commission"),
                            ("ecni", "Equality Commission Northern Ireland"),
                        ],
                        default="ehrc",
                        max_length=20,
                    ),
                ),
                (
                    "is_complaint",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                ("previous_case_url", models.TextField(blank=True, default="")),
                ("trello_url", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "parental_organisation_name",
                    models.TextField(blank=True, default=""),
                ),
                ("website_name", models.TextField(blank=True, default="")),
                (
                    "is_feedback_requested",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "case_metadata_complete_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("010_initial", "Initial"),
                            ("020_contacting", "Seeking to contact"),
                            ("030_auditing", "Testing"),
                            ("040_reporting", "Writing report"),
                            ("050_qa_report", "QA in progress"),
                            ("060_await_response", "Awaiting response"),
                            ("070_reviewing_update", "Reviewing update"),
                            ("080_requires_decision", "Requires decision"),
                            ("090_waiting_12_weeks", "Waiting for 12-weeks"),
                        ],
                        default="010_initial",
                        max_length=30,
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detailed_case_auditor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detailed_case_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detailed_case_reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.sector",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.subcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="EventHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("model_update", "Model update"),
                            ("model_create", "Model create"),
                        ],
                        default="model_update",
                        max_length=100,
                    ),
                ),
                ("difference", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detailed_case_event_content_type",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detailed_case_event_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "detailed_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="detailed.detailedcase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Event histories",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="DetailedCaseStatusHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("010_initial", "Initial"),
                            ("020_contacting", "Seeking to contact"),
                            ("030_auditing", "Testing"),
                            ("040_reporting", "Writing report"),
                            ("050_qa_report", "QA in progress"),
                            ("060_await_response", "Awaiting response"),
                            ("070_reviewing_update", "Reviewing update"),
                            ("080_requires_decision", "Requires decision"),
                            ("090_waiting_12_weeks", "Waiting for 12-weeks"),
                        ],
                        default="010_initial",
                        max_length=30,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "detailed_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="detailed.detailedcase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Detailed Case status histories",
                "ordering": ["-created"],
            },
        ),
    ]
