# Generated by Django 5.2.3 on 2025-07-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detailedcasehistory",
            options={
                "ordering": ["-id"],
                "verbose_name_plural": "Detailed Case history",
            },
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="monitor_doc_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="service_type",
            field=models.CharField(
                choices=[("service", "Service"), ("website", "Website")],
                default="website",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_point",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="ZendeskTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_within_case", models.IntegerField(blank=True, default=1)),
                ("url", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "detailed_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="detailed.detailedcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
