# Generated by Django 5.2.3 on 2025-07-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcase",
            name="monitor_doc_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="service_type",
            field=models.CharField(
                choices=[("service", "Service"), ("website", "Website")],
                default="website",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_point",
            field=models.TextField(blank=True, default=""),
        ),
    ]
