# Generated by Django 5.2.3 on 2025-07-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detailedcasehistory",
            options={
                "ordering": ["-id"],
                "verbose_name_plural": "Detailed Case history",
            },
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="monitor_doc_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="recommendation_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="no_psb_contact",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="service_type",
            field=models.CharField(
                choices=[("service", "Service"), ("website", "Website")],
                default="website",
                max_length=20,
            ),
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="case_close_decision_sent_date",
            new_name="recommendation_decision_sent_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="case_close_decision_sent_to",
            new_name="recommendation_decision_sent_to",
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_point",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="detailedcasehistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("note", "Entered note"),
                    ("reminder", "Reminder set"),
                    ("status", "Changed status"),
                    ("contact_note", "Entered contact note"),
                    ("recommendation", "Entered enforcement recommendation"),
                    ("unresponsive_note", "Entered unresponsive PSB note"),
                ],
                default="note",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detailedcasehistory",
            name="detailed_case_status",
            field=models.CharField(
                choices=[
                    ("000-unassigned-case", "Unassigned case"),
                    ("010-initial-psb-info-requested", "Requested information"),
                    (
                        "020-initial-psb-info-chasing",
                        "Chasing - no response / missed deadline",
                    ),
                    ("030-initial-psb-info-req-ack", "Acknowledge our request"),
                    ("040-initial-psb-info-received", "Received Details/Access"),
                    ("050-test-in-progress", "Test in progress"),
                    ("060-report-in-progress", "Report in progress"),
                    ("070-unassigned-qa-case", "Report ready to QA"),
                    ("090-report-ready-to-send", "Report ready to send"),
                    ("100-in-report-correspondence", "Report sent"),
                    ("110-awaiting-report-ack", "Waiting for response"),
                    (
                        "120-in-12-week-period",
                        "Report acknowledged waiting for 12-week deadline",
                    ),
                    ("130-12-week-requested-update", "Requested update at 12 weeks"),
                    (
                        "140-after-12-week-correspondence",
                        "After 12-week correspondence",
                    ),
                    ("150-reviewing-changes", "Reviewing changes"),
                    (
                        "170-case-closed-waiting-to-be-sent",
                        "Case closed and waiting to be sent to equalities body",
                    ),
                    (
                        "180-case-closed-sent-to-equalities-body",
                        "Case closed and sent to equalities body",
                    ),
                    ("200-complete", "Complete"),
                ],
                default="000-unassigned-case",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="ZendeskTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_within_case", models.IntegerField(blank=True, default=1)),
                ("url", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "detailed_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="detailed.detailedcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
