# Generated by Django 5.2.1 on 2025-05-20 07:53

import csv
import re
from datetime import datetime, timezone
from typing import Match

from django.db import migrations

INPUT_FILE_NAME = "../detailed_cases.csv"


def extract_domain_from_url(url: str) -> str:
    """Extract and return domain string from url string"""
    if url.startswith("https://"):
        url = url[8:]
    elif url.startswith("http://"):
        url = url[7:]
    domain_match: Match[str] | None = re.search("([A-Za-z_0-9.-]+).*", url)
    return domain_match.group(1) if domain_match else ""


def populate_detailed_cases(apps, schema_editor):  # pylint: disable=unused-argument
    User = apps.get_model("auth", "User")
    try:
        paul = User.objects.get(first_name="Paul")
        auditors: dict[str, User] = {
            first_name: User.objects.get(first_name=first_name)
            for first_name in ["Andrew", "Katherine", "Kelly"]
        }
    except User.DoesNotExist:  # Automated tests
        return
    EventHistory = apps.get_model("detailed", "EventHistory")
    EventHistory.objects.all().delete()
    DetailedCase = apps.get_model("detailed", "DetailedCase")
    DetailedCase.objects.all().delete()
    try:
        with open(INPUT_FILE_NAME) as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                if row["Enforcement body"] == "":
                    continue
                case_number: int = int(row["Record "][1:])
                first_contact_date: str = row["First Contact Date"]  # dd/mm/yyyy
                created: datetime = datetime(
                    year=int(first_contact_date[6:10]),
                    month=int(first_contact_date[3:5]),
                    day=int(first_contact_date[0:2]),
                    tzinfo=timezone.utc,
                )
                last_date: str = row["Date decision email sent"]  # dd/mm/yyyy
                if len(last_date) == 10:
                    updated: datetime = datetime(
                        year=int(last_date[6:10]),
                        month=int(last_date[3:5]),
                        day=int(last_date[0:2]),
                        tzinfo=timezone.utc,
                    )
                else:
                    updated: datetime = created
                auditor: User = auditors.get(row["Auditor"], paul)
                url: str = row["URL"]
                enforcement_body: str = (
                    "ecni" if row["Enforcement body"] == "ECNI" else "ehrc"
                )
                is_complaint: str = (
                    "yes" if row["Is it a complaint?"] == "Yes" else "no"
                )
                DetailedCase.objects.create(
                    case_number=case_number,
                    created_by=paul,
                    created=created,
                    updated=updated,
                    auditor=auditor,
                    home_page_url=url,
                    domain=extract_domain_from_url(url=url),
                    organisation_name=row["Website"],
                    enforcement_body=enforcement_body,
                    is_complaint=is_complaint,
                    notes=row["Summary of progress made / response from PSB"],
                )
    except FileNotFoundError:
        pass


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    EventHistory = apps.get_model("detailed", "EventHistory")
    EventHistory.objects.all().delete()
    DetailedCase = apps.get_model("detailed", "DetailedCase")
    DetailedCase.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_detailed_cases, reverse_code=reverse_code),
    ]
