# Generated by Django 5.2.6 on 2025-09-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0002_populate_detailed_cases"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailedcase",
            old_name="monitor_folder_url",
            new_name="case_folder_url",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="case_close_decision_sent_date",
            new_name="contact_information_request_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="chasing_record_complete_date",
            new_name="contact_information_request_end_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="contact_acknowledged_date",
            new_name="contact_information_request_start_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="first_contact_date",
            new_name="final_report_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="information_delivered_complete_date",
            new_name="initial_test_end_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="initial_disproportionate_burden_complete_date",
            new_name="initial_test_start_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="number_of_days_to_retest",
            new_name="initial_total_number_of_pages",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="saved_to_google_drive",
            new_name="no_psb_contact",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="notes",
            new_name="no_psb_contact_info",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="public_report_url",
            new_name="psb_progress_info",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="report_draft_url",
            new_name="psb_statement_appeal_information",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="initial_statement_compliance_complete_date",
            new_name="qa_auditor_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="initial_test_date",
            new_name="recommendation_decision_sent_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="case_close_decision_sent_to",
            new_name="recommendation_decision_sent_to",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="retest_statement_backup_url",
            new_name="recommendation_info",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="initial_website_compliance_complete_date",
            new_name="report_ready_for_qa_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="publish_report_complete_date",
            new_name="retest_compliance_decisions_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="report_draft_complete_date",
            new_name="retest_start_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="request_contact_details_complete_date",
            new_name="statement_enforcement_complete_date",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="contact_point",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="type",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="contact_acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="first_contact_sent_to",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="report_acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="report_sent_to",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="retest_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="retest_disproportionate_burden_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="retest_metrics_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="retest_statement_compliance_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="retest_website_compliance_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="summary_of_changes_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="twelve_week_acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="twelve_week_update_to",
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contact",
            name="information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_disproportionate_burden_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_statement_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_website_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="service_type",
            field=models.CharField(
                choices=[("service", "Service"), ("website", "Website")],
                default="website",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detailedcasehistory",
            name="detailed_case_status",
            field=models.CharField(
                choices=[
                    ("000-unassigned-case", "Unassigned case"),
                    ("010-initial-psb-info-requested", "Requested information"),
                    ("020-initial-psb-info-chasing", "Chasing initial response"),
                    ("030-initial-psb-info-req-ack", "Acknowledge our request"),
                    ("040-initial-psb-info-received", "Received details and access"),
                    ("050-test-in-progress", "Test in progress"),
                    ("060-report-in-progress", "Report in progress"),
                    ("070-unassigned-qa-case", "Report ready to QA"),
                    ("090-report-ready-to-send", "Report ready to send"),
                    ("100-in-report-correspondence", "Report sent"),
                    ("110-awaiting-report-ack", "Waiting for response"),
                    (
                        "120-in-12-week-period",
                        "Report acknowledged waiting for 12-week deadline",
                    ),
                    ("130-12-week-requested-update", "Requested update at 12 weeks"),
                    (
                        "140-after-12-week-correspondence",
                        "After 12-week correspondence",
                    ),
                    ("150-reviewing-changes", "Reviewing changes"),
                    (
                        "170-case-closed-waiting-to-be-sent",
                        "Case closed and waiting to be sent to equalities body",
                    ),
                    (
                        "180-case-closed-sent-to-equalities-body",
                        "Case closed and sent to equalities body",
                    ),
                    ("200-complete", "Complete"),
                    ("210-blocked", "Blocked"),
                ],
                default="000-unassigned-case",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="detailedcasehistory",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="detailedcasehistory",
            name="label",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="detailedcasehistory",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="detailedcase",
            name="initial_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="detailedcase",
            name="initial_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="detailedcase",
            name="retest_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="detailedcase",
            name="retest_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="detailedcasehistory",
            name="event_type",
            field=models.CharField(
                choices=[("note", "Entered note"), ("status", "Changed status")],
                default="note",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ZendeskTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_within_case", models.IntegerField(blank=True, default=1)),
                ("url", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "detailed_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="detailed.detailedcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
