# Generated by Django 5.2.1 on 2025-05-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0002_populate_detailed_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcase",
            name="report_acknowledged_by",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="report_acknowledged_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="report_acknowledged_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="report_sent_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="report_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="report_sent_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="twelve_week_acknowledged_by",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="twelve_week_acknowledged_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="twelve_week_acknowledged_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="twelve_week_deadline_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="twelve_week_deadline_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="twelve_week_update_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="twelve_week_update_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="twelve_week_update_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
