# Generated by Django 5.2.1 on 2025-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0002_populate_detailed_cases"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcase",
            name="initial_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_disproportionate_burden_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_statement_compliance_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant or no statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_test_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_testing_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_testing_outcome_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_website_compliance_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="initial_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="monitor_folder_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
