# Generated by Django 5.2.3 on 2025-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0002_alter_detailedcasehistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcase",
            name="no_psb_contact",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="detailedcasehistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("note", "Entered note"),
                    ("reminder", "Reminder set"),
                    ("status", "Changed status"),
                    ("contact_note", "Entered contact note"),
                    ("recommendation", "Entered enforcement recommendation"),
                    ("unresponsive_note", "Entered unresponsive PSB note"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
