# Generated by Django 5.2.6 on 2025-09-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0003_rename_monitor_folder_url_detailedcase_case_folder_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailedcase",
            name="is_feedback_survey_sent",
        ),
    ]
