# Generated by Django 5.2.1 on 2025-05-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0003_detailedcase_report_acknowledged_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcase",
            name="case_close_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="case_close_decision_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="case_close_decision_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="case_close_decision_sent_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="case_close_decision_state",
            field=models.CharField(
                choices=[
                    (
                        "complete-send",
                        "Case is complete and is ready to send to the equality body",
                    ),
                    (
                        "complete-no-send",
                        "Case should not be sent to the equality body",
                    ),
                    ("no-decision", "Case still in progress"),
                ],
                default="no-decision",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="is_feedback_survey_sent",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="number_of_days_to_retest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_disproportionate_burden_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_metrics_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_result_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_statement_backup_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_statement_compliance_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant or no statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_website_compliance_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="summary_of_changes_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
