# Generated by Django 5.2.3 on 2025-08-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0003_alter_detailedcasehistory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="contact_point",
            new_name="contact_details",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="type",
        ),
        migrations.AddField(
            model_name="contact",
            name="information",
            field=models.TextField(blank=True, default=""),
        ),
    ]
