# Generated by Django 5.2.3 on 2025-08-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0004_alter_detailedcasehistory_detailed_case_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailedcase",
            name="report_acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="report_sent_to",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="twelve_week_acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="twelve_week_update_to",
        ),
    ]
