# Generated by Django 5.2.3 on 2025-08-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0004_rename_contact_point_contact_contact_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailedcase",
            name="chasing_record_complete_date",
        ),
        migrations.AlterField(
            model_name="detailedcasehistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("note", "Entered note"),
                    ("reminder", "Reminder set"),
                    ("status", "Changed status"),
                    ("recommendation", "Entered enforcement recommendation"),
                    ("unresponsive_note", "Entered unresponsive PSB note"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
