# Generated by Django 5.2.6 on 2025-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0005_alter_detailedcasehistory_detailed_case_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcase",
            name="case_recommendation_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
