# Generated by Django 5.2.3 on 2025-08-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0005_remove_detailedcase_chasing_record_complete_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailedcase",
            old_name="contact_acknowledged_date",
            new_name="contact_information_request_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="first_contact_date",
            new_name="contact_information_request_start_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="contact_acknowledged_by",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="first_contact_sent_to",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="information_delivered_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="request_contact_details_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="saved_to_google_drive",
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="contact_information_request_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
