# Generated by Django 5.2.3 on 2025-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0005_remove_detailedcase_report_acknowledged_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailedcase",
            old_name="retest_statement_backup_url",
            new_name="retest_disproportionate_burden_information",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="retest_date",
            new_name="retest_start_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="retest_disproportionate_burden_complete_date",
            new_name="retesting_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="retest_end_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="retest_statement_compliance_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="retest_website_compliance_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="summary_of_changes_complete_date",
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_statement_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="retest_website_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
    ]
