# Generated by Django 5.2.6 on 2025-10-13 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0006_detailedcase_case_recommendation_complete_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailedcase",
            old_name="twelve_week_acknowledged_complete_date",
            new_name="twelve_week_received_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="twelve_week_acknowledged_date",
            new_name="twelve_week_received_date",
        ),
    ]
