# Generated by Django 5.2.3 on 2025-08-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0006_rename_contact_acknowledged_date_detailedcase_contact_information_request_complete_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailedcase",
            name="initial_disproportionate_burden_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="initial_statement_compliance_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="initial_website_compliance_complete_date",
        ),
    ]
