# Generated by Django 5.2.5 on 2025-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0006_rename_retest_statement_backup_url_detailedcase_retest_disproportionate_burden_information_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detailedcasehistory",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "Detailed Case history",
            },
        ),
        migrations.AlterField(
            model_name="detailedcasehistory",
            name="event_type",
            field=models.CharField(
                choices=[("note", "Entered note"), ("status", "Changed status")],
                default="note",
                max_length=20,
            ),
        ),
    ]
