# Generated by Django 5.2.6 on 2025-10-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0007_alter_contact_detailed_case_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="detailed_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detailed_contacts",
                to="detailed.detailedcase",
            ),
        ),
    ]
