# Generated by Django 5.2.6 on 2025-11-17 09:14

from unittest.mock import Mock, patch

from django.db import migrations

from ...common.utils import amp_format_date


def populate_reminder_case_notes(apps, schema_editor):
    Task = apps.get_model("notifications", "Task")
    DetailedCaseHistory = apps.get_model("detailed", "DetailedCaseHistory")
    for reminder in Task.objects.filter(type="reminder"):
        if reminder.base_case.test_type != "detailed":
            continue
        with patch("django.utils.timezone.now", Mock(return_value=reminder.updated)):
            DetailedCaseHistory.objects.create(
                detailed_case_id=reminder.base_case.id,
                event_type="note",
                value=f"Due {amp_format_date(reminder.date)}:\n\n{reminder.description}",
                label="Reminder",
                created_by=reminder.user,
            )


def reverse_code(apps, schema_editor):
    DetailedCaseHistory = apps.get_model("detailed", "DetailedCaseHistory")
    for detailed_case_history in DetailedCaseHistory.objects.filter(label="Reminder"):
        detailed_case_history.delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0007_rename_twelve_week_acknowledged_complete_date_detailedcase_twelve_week_received_complete_date_and_mo",
        ),
    ]

    operations = [
        migrations.RunPython(populate_reminder_case_notes, reverse_code=reverse_code),
    ]
