# Generated by Django 5.2.3 on 2025-08-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0007_remove_detailedcase_initial_disproportionate_burden_complete_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailedcase",
            name="initial_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="detailedcase",
            name="retest_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
    ]
