# Generated by Django 5.2.6 on 2025-10-14 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0007_rename_twelve_week_acknowledged_complete_date_detailedcase_twelve_week_received_complete_date_and_mo",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="detailed_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detailed_contacts",
                to="detailed.detailedcase",
            ),
        ),
        migrations.AlterField(
            model_name="zendeskticket",
            name="detailed_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detailed_zendesktickets",
                to="detailed.detailedcase",
            ),
        ),
    ]
