# Generated by Django 5.2.6 on 2025-11-13 16:09
# Move description imported from Trello to bottom of Case notes history

from datetime import datetime, timezone

from django.db import migrations

TRELLO_DESCRIPTION_LABEL: str = "Description imported from Trello"
TRELLO_DESCRIPTION_DATETIME: datetime = datetime(
    2020, 1, 1, 0, 0, 0, tzinfo=timezone.utc
)


def move_trello_desc(apps, schema_editor):
    DetailedCaseHistory = apps.get_model("detailed", "DetailedCaseHistory")
    for detailed_case_history in DetailedCaseHistory.objects.filter(
        label=TRELLO_DESCRIPTION_LABEL
    ):
        detailed_case_history.created = TRELLO_DESCRIPTION_DATETIME
        detailed_case_history.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0007_rename_twelve_week_acknowledged_complete_date_detailedcase_twelve_week_received_complete_date_and_mo",
        ),
    ]

    operations = [
        migrations.RunPython(move_trello_desc, reverse_code=reverse_code),
    ]
