# Generated by Django 5.2.6 on 2025-11-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0007_rename_twelve_week_acknowledged_complete_date_detailedcase_twelve_week_received_complete_date_and_mo",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailedcasehistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("note", "Entered note"),
                    ("status", "Changed status"),
                    ("trello-description", "Description imported from Trello"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
