# Generated by Django 5.2.6 on 2025-09-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0008_rename_recommendation_notes_detailedcase_psb_progress_info_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailedcase",
            old_name="retesting_complete_date",
            new_name="retest_compliance_decisions_complete_date",
        ),
    ]
