# Generated by Django 5.2.3 on 2025-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0008_alter_detailedcase_initial_website_compliance_state_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcase",
            name="no_psb_contact_info",
            field=models.TextField(blank=True, default=""),
        ),
    ]
