# Generated by Django 5.2.6 on 2025-11-14 09:34

from django.db import migrations

TRELLO_DESCRIPTION_LABEL: str = "Description imported from Trello"
TRELLO_DESCRIPTION_EVENT_TYPE: str = "trello-description"


def move_trello_desc(apps, schema_editor):
    DetailedCaseHistory = apps.get_model("detailed", "DetailedCaseHistory")
    for detailed_case_history in DetailedCaseHistory.objects.filter(
        label=TRELLO_DESCRIPTION_LABEL
    ):
        detailed_case_history.event_type = TRELLO_DESCRIPTION_EVENT_TYPE
        detailed_case_history.save()


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0008_alter_detailedcasehistory_event_type"),
    ]

    operations = [
        migrations.RunPython(move_trello_desc, reverse_code=reverse_code),
    ]
