# Generated by Django 5.2.6 on 2025-09-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "detailed",
            "0009_rename_retesting_complete_date_detailedcase_retest_compliance_decisions_complete_date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedcase",
            name="post_case_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="psb_appeal_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="detailedcase",
            name="statement_enforcement_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
