# Generated by Django 5.2.3 on 2025-08-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0009_detailedcase_no_psb_contact_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailedcasehistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("note", "Entered note"),
                    ("status", "Changed status"),
                    ("recommendation", "Entered enforcement recommendation"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
