# Generated by Django 5.2.6 on 2025-09-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0010_detailedcase_psb_statement_appeal_information_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detailedcase",
            name="notes",
        ),
    ]
