# Generated by Django 5.2.3 on 2025-08-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detailed", "0010_alter_detailedcasehistory_event_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailedcase",
            old_name="publish_report_complete_date",
            new_name="final_report_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="report_draft_complete_date",
            new_name="qa_auditor_complete_date",
        ),
        migrations.RenameField(
            model_name="detailedcase",
            old_name="report_end_date",
            new_name="report_ready_for_qa_complete_date",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="public_report_url",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="report_draft_url",
        ),
        migrations.RemoveField(
            model_name="detailedcase",
            name="report_start_date",
        ),
    ]
