# Generated by Django 3.2.4 on 2021-06-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_local_website_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutsconversion',
            options={'managed': False},
        ),
    ]
