environment         = "test-env"
domain_name         = "accessibility-monitoring.service.gov.uk"
app_domain_name     = "platform-test.accessibility-monitoring.service.gov.uk"
app_two_domain_name = "reports-test.accessibility-monitoring.service.gov.uk"
image_tag           = "latest"
viewer_image_tag    = "latest"