services:
    db:
        image: postgres:18.6
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5435:5435"
        command: -p 5435

    web:
        platform: linux/amd64
        build:
            context: ../..
            dockerfile: ./Dockerfiles/amp_platform.DockerFile
        volumes:
            - "./cypress/:/code/stack_tests/integration_tests/cypress/"
            - "./fixtures/:/code/stack_tests/integration_tests/fixtures/"
        ports:
            - "8001:8001"
        depends_on:
            - db
            - localstack
        environment:
            - ALLOWED_HOSTS='* localhost 0.0.0.0 0.0.0.0:8001 web web:8001' # Only localhost:8001 works for localstack
            - SECRET_KEY='123456789'
            - DEBUG=FALSE
            - DOCKER_COMPOSE=TRUE
            - AMP_PROTOCOL=http://
            - AMP_VIEWER_DOMAIN=0.0.0.0:8002
            - BYPASS_SECURE_COOKIE=TRUE
            - TERRAFORM=TRUE
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=admin
            - BUCKET_NAME=amp-dummy-s3-bucket
            - 'DB_PASSWORD={"username": "admin", "password": "secret"}'
            - DB_PORT_DOCKER=5435
        command: >
            bash -c "
            make static_files_process &&
            python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            python manage.py init_int_test_data &&
            python manage.py recache_statuses &&
            python manage.py clearsessions &&
            python manage.py axes_reset_logs --age 7 &&
            exec waitress-serve --host=0.0.0.0 --port=8001 --log-untrusted-proxy-headers accessibility_monitoring_platform.wsgi:application
            "
        healthcheck:
            test: curl --fail http://localhost:8001/healthcheck || exit 1
            retries: 5
        stdin_open: true
        tty: true

    report_viewer:
        platform: linux/amd64
        build:
            context: ../..
            dockerfile: ./Dockerfiles/amp_viewer.DockerFile
        ports:
            - "8002:8001"
        depends_on:
            - db
            - localstack
            - web
        environment:
            - ALLOWED_HOSTS='* localhost 0.0.0.0 0.0.0.0:8001'
            - SECRET_KEY='123456789'
            - DEBUG=FALSE
            - DOCKER_COMPOSE=TRUE
            - BYPASS_SECURE_COOKIE=TRUE
            - TERRAFORM=TRUE
            - DB_HOST=db
            - DB_NAME=postgres
            - DB_USER=admin
            - BUCKET_NAME=amp-dummy-s3-bucket
            - 'DB_PASSWORD={"username": "admin", "password": "secret"}'
            - DB_PORT_DOCKER=5435

    localstack:
        image: localstack/localstack:4.14
        hostname: localstack
        ports:
            - "4567:4566"
            - "4572:4571"
        environment:
            - SERVICES=s3
            - AWS_DEFAULT_REGION=us-east-1
            - HOSTNAME_EXTERNAL=localstack
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

    cypress:
        image: "cypress/included:15.9.0"
        depends_on:
            web:
                condition: service_healthy
        environment:
            - CYPRESS_baseUrl=http://web:8001
        volumes:
            - ./cypress:/cypress
            - ./cypress.config.js:/cypress.config.js
            - ./entrypoint.sh:/entrypoint.sh
        working_dir: /cypress
        entrypoint: "/entrypoint.sh"
