# Generated by Django 5.2.1 on 2025-06-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0013_basecase"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileCase",
            fields=[
                (
                    "basecase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cases.basecase",
                    ),
                ),
                ("app_name", models.TextField(blank=True, default="")),
                ("app_store_url", models.TextField(blank=True, default="")),
                (
                    "app_os",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        default="ios",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "case_metadata_complete_date",
                    models.DateField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
            bases=("cases.basecase",),
        ),
        migrations.CreateModel(
            name="EventHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("model_update", "Model update"),
                            ("model_create", "Model create"),
                        ],
                        default="model_update",
                        max_length=100,
                    ),
                ),
                ("difference", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobile_case_event_content_type",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobile_case_event_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mobile_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.mobilecase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Event histories",
                "ordering": ["-created"],
            },
        ),
    ]
