# Generated by Django 5.2.1 on 2025-05-20 07:53


from django.db import migrations


def populate_mobile_cases(apps, schema_editor):  # pylint: disable=unused-argument
    pass


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_mobile_cases, reverse_code=reverse_code),
    ]
