# Generated by Django 5.2.6 on 2025-09-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0002_populate_mobile_cases"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilecase",
            name="case_folder_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_test_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_test_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MobileCaseHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("note", "Entered note"),
                            ("status", "Changed status"),
                            ("recommendation", "Entered enforcement recommendation"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mobile_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mobile.mobilecase",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mobile Case history",
                "ordering": ["-id"],
            },
        ),
    ]
