# Generated by Django 5.2.3 on 2025-08-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0003_mobilecasehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilecase",
            name="case_folder_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_test_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_test_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
