# Generated by Django 5.2.6 on 2025-11-21 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0003_mobilecase_case_folder_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobilecasehistory",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "Mobile Case history",
            },
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="app_store_url",
            new_name="android_app_url",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_test_end_date",
            new_name="case_close_complete_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="notes",
            new_name="case_close_decision_notes",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_test_start_date",
            new_name="case_recommendation_complete_date",
        ),
        migrations.RemoveField(
            model_name="mobilecase",
            name="app_os",
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="android_test_included",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("not-known", "Not known")],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="case_close_decision_state",
            field=models.CharField(
                choices=[
                    (
                        "complete-send",
                        "Case is complete and is ready to send to the equality body",
                    ),
                    (
                        "complete-no-send",
                        "Case should not be sent to the equality body",
                    ),
                    ("no-decision", "Case still in progress"),
                ],
                default="no-decision",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="contact_information_request_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="contact_information_request_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="contact_information_request_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_case_owner",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_closed_case_state",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("in-progress", "Case in progress"),
                    ("no", "No (or holding)"),
                ],
                default="no",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_completed_case_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_metadata_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_started_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="equality_body_report_url_android",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="equality_body_report_url_ios",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="final_report_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_app_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_outcome_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_test_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_test_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_android_total_number_of_screens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_auditor_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_app_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_outcome_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_test_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_test_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_total_number_of_screens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="ios_app_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="ios_test_included",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("not-known", "Not known")],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="is_case_added_to_stats",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="manage_contacts_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="no_psb_contact",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="no_psb_contact_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="previous_case_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="psb_progress_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="psb_statement_appeal_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="qa_approval_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="qa_auditor_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="recommendation_decision_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="recommendation_decision_sent_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="recommendation_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_acknowledged_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_acknowledged_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_approved_status",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("in-progress", "Further work is needed"),
                    ("not-started", "Not started"),
                ],
                default="not-started",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_ready_for_qa",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_ready_for_qa_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_sent_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_app_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_app_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_compliance_decisions_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_disproportionate_burden_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_result_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_statement_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_app_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_app_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_compliance_decisions_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_disproportionate_burden_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_result_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_statement_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="statement_enforcement_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="trello_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_deadline_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_deadline_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_received_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_update_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_update_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecasehistory",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="mobilecasehistory",
            name="label",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="mobilecasehistory",
            name="mobile_case_status",
            field=models.CharField(
                choices=[
                    ("000-unassigned-case", "Unassigned case"),
                    ("010-initial-psb-info-requested", "Requested information"),
                    ("020-initial-psb-info-chasing", "Chasing initial response"),
                    ("030-initial-psb-info-req-ack", "Acknowledged our request"),
                    ("040-initial-psb-info-received", "Received details and access"),
                    ("050-test-in-progress", "Test in progress"),
                    ("060-report-in-progress", "Report in progress"),
                    ("070-unassigned-qa-case", "Report ready to QA"),
                    ("090-report-ready-to-send", "Report ready to send"),
                    ("100-in-report-correspondence", "Report sent"),
                    ("120-in-12-week-period", "Waiting for 12-week deadline"),
                    (
                        "140-after-12-week-correspondence",
                        "After 12-week correspondence",
                    ),
                    ("150-reviewing-changes", "Reviewing changes"),
                    (
                        "170-case-closed-waiting-to-be-sent",
                        "Waiting to be sent to equalities body",
                    ),
                    (
                        "180-case-closed-sent-to-equalities-body",
                        "Sent to equalities body",
                    ),
                    ("200-complete", "Complete"),
                ],
                default="000-unassigned-case",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecasehistory",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mobilecasehistory",
            name="event_type",
            field=models.CharField(
                choices=[("note", "Entered note"), ("status", "Changed status")],
                default="note",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MobileContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("name", models.TextField(blank=True, default="")),
                ("job_title", models.CharField(blank=True, default="", max_length=200)),
                ("contact_details", models.TextField(blank=True, default="")),
                ("information", models.TextField(blank=True, default="")),
                (
                    "preferred",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unknown", "Not known"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mobile_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobile_contacts",
                        to="mobile.mobilecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-preferred", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MobileZendeskTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_within_case", models.IntegerField(blank=True, default=1)),
                ("url", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "mobile_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobile_zendesktickets",
                        to="mobile.mobilecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
