# Generated by Django 5.2.6 on 2025-10-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0003_mobilecase_case_folder_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilecase",
            old_name="notes",
            new_name="case_close_decision_notes",
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="case_close_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="case_close_decision_state",
            field=models.CharField(
                choices=[
                    (
                        "complete-send",
                        "Case is complete and is ready to send to the equality body",
                    ),
                    (
                        "complete-no-send",
                        "Case should not be sent to the equality body",
                    ),
                    ("no-decision", "Case still in progress"),
                ],
                default="no-decision",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="case_recommendation_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="contact_information_request_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="contact_information_request_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="contact_information_request_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_case_owner",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_closed_case_state",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("in-progress", "Case in progress"),
                    ("no", "No (or holding)"),
                ],
                default="no",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_completed_case_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_metadata_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="enforcement_body_started_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="equality_body_report_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="final_report_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_testing_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_testing_outcome_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_total_number_of_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="is_case_added_to_stats",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="manage_contacts_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="no_psb_contact",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="no_psb_contact_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="previous_case_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="psb_progress_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="psb_statement_appeal_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="qa_approval_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="qa_auditor_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="recommendation_decision_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="recommendation_decision_sent_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="recommendation_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_acknowledged_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_acknowledged_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_approved_status",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("in-progress", "Further work is needed"),
                    ("not-started", "Not started"),
                ],
                default="not-started",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_ready_for_qa",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_ready_for_qa_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_sent_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="report_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_compliance_decisions_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_disproportionate_burden_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_result_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_statement_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_website_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="statement_enforcement_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="trello_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_acknowledged_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_acknowledged_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_deadline_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_deadline_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_update_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="twelve_week_update_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MobileContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("name", models.TextField(blank=True, default="")),
                ("job_title", models.CharField(blank=True, default="", max_length=200)),
                ("contact_details", models.TextField(blank=True, default="")),
                ("information", models.TextField(blank=True, default="")),
                (
                    "preferred",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unknown", "Not known"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mobile_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobile_contacts",
                        to="mobile.mobilecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-preferred", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MobileZendeskTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_within_case", models.IntegerField(blank=True, default=1)),
                ("url", models.TextField(blank=True, default="")),
                ("summary", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "mobile_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mobile_zendesktickets",
                        to="mobile.mobilecase",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
