# Generated by Django 5.2.6 on 2025-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0004_alter_mobilecasehistory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilecase",
            old_name="app_store_url",
            new_name="android_app_store_url",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_test_end_date",
            new_name="initial_android_details_complete_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_disproportionate_burden_claim",
            new_name="initial_android_disproportionate_burden_claim",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_test_start_date",
            new_name="initial_android_outcome_complete_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_statement_compliance_state",
            new_name="initial_android_statement_compliance_state",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_testing_details_complete_date",
            new_name="initial_android_test_end_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_testing_outcome_complete_date",
            new_name="initial_android_test_start_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_total_number_of_issues",
            new_name="initial_android_total_number_of_issues",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_total_number_of_pages",
            new_name="initial_android_total_number_of_pages",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_website_compliance_state",
            new_name="initial_android_website_compliance_state",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_compliance_decisions_complete_date",
            new_name="initial_auditor_complete_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_result_complete_date",
            new_name="initial_ios_details_complete_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_disproportionate_burden_claim",
            new_name="initial_ios_disproportionate_burden_claim",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_start_date",
            new_name="initial_ios_outcome_complete_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_statement_compliance_state",
            new_name="initial_ios_statement_compliance_state",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_total_number_of_issues",
            new_name="initial_ios_total_number_of_issues",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_website_compliance_state",
            new_name="initial_ios_website_compliance_state",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_disproportionate_burden_information",
            new_name="ios_app_store_url",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_statement_compliance_information",
            new_name="retest_android_disproportionate_burden_information",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_website_compliance_information",
            new_name="retest_android_statement_compliance_information",
        ),
        migrations.RemoveField(
            model_name="mobilecase",
            name="app_os",
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="android_test_included",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_test_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_test_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="initial_ios_total_number_of_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="ios_test_included",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_compliance_decisions_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_result_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_website_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_android_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_compliance_decisions_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_disproportionate_burden_claim",
            field=models.CharField(
                choices=[
                    ("no-assessment", "Claim with no assessment"),
                    ("assessment", "Claim with assessment"),
                    ("no-claim", "No claim"),
                    ("no-statement", "No statement"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_disproportionate_burden_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_result_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_statement_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_statement_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("no-statement", "No statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_total_number_of_issues",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_website_compliance_information",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="retest_ios_website_compliance_state",
            field=models.CharField(
                choices=[
                    ("compliant", "Fully compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("not-known", "Not known"),
                ],
                default="not-known",
                max_length=20,
            ),
        ),
    ]
