# Generated by Django 5.2.6 on 2025-10-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0004_alter_mobilecasehistory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilecase",
            old_name="app_name",
            new_name="android_app_name",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="app_store_url",
            new_name="android_app_store_url",
        ),
        migrations.RemoveField(
            model_name="mobilecase",
            name="app_os",
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="ios_app_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="ios_app_store_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
