# Generated by Django 5.2.6 on 2025-10-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobile", "0004_rename_notes_mobilecase_case_close_decision_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilecase",
            old_name="twelve_week_acknowledged_complete_date",
            new_name="twelve_week_received_complete_date",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="twelve_week_acknowledged_date",
            new_name="twelve_week_received_date",
        ),
    ]
