# Generated by Django 5.2.6 on 2025-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobile",
            "0005_rename_app_store_url_mobilecase_android_app_store_url_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilecase",
            old_name="equality_body_report_url",
            new_name="equality_body_report_url_android",
        ),
        migrations.AddField(
            model_name="mobilecase",
            name="equality_body_report_url_ios",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="mobilecase",
            name="android_test_included",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("not-known", "Not known")],
                default="not-known",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mobilecase",
            name="ios_test_included",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("not-known", "Not known")],
                default="not-known",
                max_length=20,
            ),
        ),
    ]
