# Generated by Django 5.2.6 on 2025-10-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobile",
            "0005_rename_twelve_week_acknowledged_complete_date_mobilecase_twelve_week_received_complete_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobilecasehistory",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "Mobile Case history",
            },
        ),
        migrations.AddField(
            model_name="mobilecasehistory",
            name="id_within_case",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="mobilecasehistory",
            name="label",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="mobilecasehistory",
            name="mobile_case_status",
            field=models.CharField(
                choices=[
                    ("000-unassigned-case", "Unassigned case"),
                    ("010-initial-psb-info-requested", "Requested information"),
                    ("020-initial-psb-info-chasing", "Chasing initial response"),
                    ("030-initial-psb-info-req-ack", "Acknowledged our request"),
                    ("040-initial-psb-info-received", "Received details and access"),
                    ("050-test-in-progress", "Test in progress"),
                    ("060-report-in-progress", "Report in progress"),
                    ("070-unassigned-qa-case", "Report ready to QA"),
                    ("090-report-ready-to-send", "Report ready to send"),
                    ("100-in-report-correspondence", "Report sent"),
                    (
                        "120-in-12-week-period",
                        "Report acknowledged waiting for 12-week deadline",
                    ),
                    (
                        "140-after-12-week-correspondence",
                        "After 12-week correspondence",
                    ),
                    ("150-reviewing-changes", "Reviewing changes"),
                    (
                        "170-case-closed-waiting-to-be-sent",
                        "Case closed and waiting to be sent to equalities body",
                    ),
                    (
                        "180-case-closed-sent-to-equalities-body",
                        "Case closed and sent to equalities body",
                    ),
                    ("200-complete", "Complete"),
                ],
                default="000-unassigned-case",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="mobilecasehistory",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mobilecasehistory",
            name="event_type",
            field=models.CharField(
                choices=[("note", "Entered note"), ("status", "Changed status")],
                default="note",
                max_length=20,
            ),
        ),
    ]
