# Generated by Django 5.2.6 on 2025-11-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobile",
            "0006_rename_equality_body_report_url_mobilecase_equality_body_report_url_android_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_android_website_compliance_state",
            new_name="initial_android_app_compliance_state",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_ios_website_compliance_state",
            new_name="initial_ios_app_compliance_state",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_android_website_compliance_information",
            new_name="retest_android_app_compliance_information",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_android_website_compliance_state",
            new_name="retest_android_app_compliance_state",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_ios_website_compliance_information",
            new_name="retest_ios_app_compliance_information",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="retest_ios_website_compliance_state",
            new_name="retest_ios_app_compliance_state",
        ),
    ]
