# Generated by Django 5.2.6 on 2025-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobile",
            "0007_rename_initial_android_website_compliance_state_mobilecase_initial_android_app_compliance_state_and_",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilecase",
            old_name="android_app_store_url",
            new_name="android_app_url",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="ios_app_store_url",
            new_name="ios_app_url",
        ),
        migrations.AlterField(
            model_name="mobilecasehistory",
            name="mobile_case_status",
            field=models.CharField(
                choices=[
                    ("000-unassigned-case", "Unassigned case"),
                    ("010-initial-psb-info-requested", "Requested information"),
                    ("020-initial-psb-info-chasing", "Chasing initial response"),
                    ("030-initial-psb-info-req-ack", "Acknowledged our request"),
                    ("040-initial-psb-info-received", "Received details and access"),
                    ("050-test-in-progress", "Test in progress"),
                    ("060-report-in-progress", "Report in progress"),
                    ("070-unassigned-qa-case", "Report ready to QA"),
                    ("090-report-ready-to-send", "Report ready to send"),
                    ("100-in-report-correspondence", "Report sent"),
                    ("120-in-12-week-period", "Waiting for 12-week deadline"),
                    (
                        "140-after-12-week-correspondence",
                        "After 12-week correspondence",
                    ),
                    ("150-reviewing-changes", "Reviewing changes"),
                    (
                        "170-case-closed-waiting-to-be-sent",
                        "Waiting to be sent to equalities body",
                    ),
                    (
                        "180-case-closed-sent-to-equalities-body",
                        "Sent to equalities body",
                    ),
                    ("200-complete", "Complete"),
                ],
                default="000-unassigned-case",
                max_length=200,
            ),
        ),
    ]
