# Generated by Django 5.2.6 on 2025-11-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mobile",
            "0008_rename_android_app_store_url_mobilecase_android_app_url_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_android_total_number_of_pages",
            new_name="initial_android_total_number_of_screens",
        ),
        migrations.RenameField(
            model_name="mobilecase",
            old_name="initial_ios_total_number_of_pages",
            new_name="initial_ios_total_number_of_screens",
        ),
    ]
