"""
URLS for cases
"""

from django.contrib.auth.decorators import login_required
from django.urls import path
from django.urls.resolvers import URLPattern

from accessibility_monitoring_platform.apps.detailed.views import (
    ContactChasingRecordUpdateView,
    ContactCreateView,
    ContactInformationDeliveredUpdateView,
    ContactInformationRequestUpdateView,
    ContactUpdateView,
    DetailedCaseCreateView,
    DetailedCaseDetailView,
    DetailedCaseListView,
    DetailedCaseMetadataUpdateView,
    DetailedCaseNoteCreateView,
    DetailedCaseStatusUpdateView,
    InitialDisproportionateBurdenUpdateView,
    InitialStatementComplianceUpdateView,
    InitialTestingDetailsUpdateView,
    InitialTestingOutcomeUpdateView,
    InitialWebsiteComplianceUpdateView,
    ManageContactDetailsUpdateView,
    PublishReportUpdateView,
    QAApprovalUpdateView,
    ReportDraftUpdateView,
)

app_name: str = "detailed"
urlpatterns: list[URLPattern] = [
    path(
        "create/",
        login_required(DetailedCaseCreateView.as_view()),
        name="case-create",
    ),
    path(
        "<int:pk>/case-detail/",
        login_required(DetailedCaseDetailView.as_view()),
        name="case-detail",
    ),
    path(
        "case-list/",
        login_required(DetailedCaseListView.as_view()),
        name="case-list",
    ),
    path(
        "<int:pk>/case-metadata/",
        login_required(DetailedCaseMetadataUpdateView.as_view()),
        name="edit-case-metadata",
    ),
    path(
        "<int:pk>/case-status/",
        login_required(DetailedCaseStatusUpdateView.as_view()),
        name="edit-case-status",
    ),
    path(
        "<int:case_id>/case-note-create/",
        login_required(DetailedCaseNoteCreateView.as_view()),
        name="create-case-note",
    ),
    path(
        "<int:pk>/manage-contact-details/",
        login_required(ManageContactDetailsUpdateView.as_view()),
        name="manage-contact-details",
    ),
    path(
        "<int:case_id>/edit-contact-create/",
        login_required(ContactCreateView.as_view()),
        name="edit-contact-create",
    ),
    path(
        "<int:pk>/edit-contact-update/",
        login_required(ContactUpdateView.as_view()),
        name="edit-contact-update",
    ),
    path(
        "<int:pk>/edit-request-contact-details/",
        login_required(ContactInformationRequestUpdateView.as_view()),
        name="edit-request-contact-details",
    ),
    path(
        "<int:pk>/edit-chasing-record/",
        login_required(ContactChasingRecordUpdateView.as_view()),
        name="edit-chasing-record",
    ),
    path(
        "<int:pk>/edit-information-delivered/",
        login_required(ContactInformationDeliveredUpdateView.as_view()),
        name="edit-information-delivered",
    ),
    path(
        "<int:pk>/edit-initial-testing-details/",
        login_required(InitialTestingDetailsUpdateView.as_view()),
        name="edit-initial-testing-details",
    ),
    path(
        "<int:pk>/edit-initial-testing-outcome/",
        login_required(InitialTestingOutcomeUpdateView.as_view()),
        name="edit-initial-testing-outcome",
    ),
    path(
        "<int:pk>/edit-initial-website-compliance/",
        login_required(InitialWebsiteComplianceUpdateView.as_view()),
        name="edit-initial-website-compliance",
    ),
    path(
        "<int:pk>/edit-disproportionate-burden-compliance/",
        login_required(InitialDisproportionateBurdenUpdateView.as_view()),
        name="edit-disproportionate-burden-compliance",
    ),
    path(
        "<int:pk>/edit-initial-statement-compliance/",
        login_required(InitialStatementComplianceUpdateView.as_view()),
        name="edit-initial-statement-compliance",
    ),
    path(
        "<int:pk>/edit-report-draft/",
        login_required(ReportDraftUpdateView.as_view()),
        name="edit-report-draft",
    ),
    path(
        "<int:pk>/edit-qa-approval/",
        login_required(QAApprovalUpdateView.as_view()),
        name="edit-qa-approval",
    ),
    path(
        "<int:pk>/edit-publish-report/",
        login_required(PublishReportUpdateView.as_view()),
        name="edit-publish-report",
    ),
]
