"""
URLS for cases
"""

from django.contrib.auth.decorators import login_required
from django.urls import path
from django.urls.resolvers import URLPattern

from accessibility_monitoring_platform.apps.detailed.views import (
    CaseCloseUpdateView,
    CaseZendeskTicketsDetailView,
    ContactCreateView,
    ContactInformationRequestUpdateView,
    ContactUpdateView,
    CorrespondenceReportAcknowledgedUpdateView,
    CorrespondenceReportSentUpdateView,
    CorrespondenceTwelveWeekAcknowledgedUpdateView,
    CorrespondenceTwelveWeekDeadlineUpdateView,
    CorrespondenceTwelveWeekRequestUpdateView,
    DetailedCaseCreateView,
    DetailedCaseDetailView,
    DetailedCaseHistoryDetailView,
    DetailedCaseMetadataUpdateView,
    DetailedCaseNoteCreateView,
    DetailedCaseNoteUpdateView,
    DetailedCaseStatusUpdateView,
    EnforcementBodyMetadataUpdateView,
    InitialTestingDetailsUpdateView,
    InitialTestingOutcomeUpdateView,
    ManageContactDetailsUpdateView,
    PublishReportUpdateView,
    QAApprovalUpdateView,
    ReportDraftUpdateView,
    RetestDisproportionateBurdenUpdateView,
    RetestResultUpdateView,
    RetestStatementComplianceUpdateView,
    RetestSummaryUpdateView,
    RetestWebsiteComplianceUpdateView,
    UnresponsivePSBUpdateView,
    ZendeskTicketConfirmDeleteUpdateView,
    ZendeskTicketCreateView,
    ZendeskTicketUpdateView,
)

app_name: str = "detailed"
urlpatterns: list[URLPattern] = [
    path(
        "create/",
        login_required(DetailedCaseCreateView.as_view()),
        name="case-create",
    ),
    path(
        "<int:pk>/case-detail/",
        login_required(DetailedCaseDetailView.as_view()),
        name="case-detail",
    ),
    path(
        "<int:pk>/case-metadata/",
        login_required(DetailedCaseMetadataUpdateView.as_view()),
        name="edit-case-metadata",
    ),
    path(
        "<int:pk>/case-status/",
        login_required(DetailedCaseStatusUpdateView.as_view()),
        name="edit-case-status",
    ),
    path(
        "<int:case_id>/create-case-note/",
        login_required(DetailedCaseNoteCreateView.as_view()),
        name="create-case-note",
    ),
    path(
        "notes/<int:pk>/edit-case-note/",
        login_required(DetailedCaseNoteUpdateView.as_view()),
        name="edit-case-note",
    ),
    path(
        "<int:pk>/manage-contact-details/",
        login_required(ManageContactDetailsUpdateView.as_view()),
        name="manage-contact-details",
    ),
    path(
        "<int:case_id>/edit-contact-create/",
        login_required(ContactCreateView.as_view()),
        name="edit-contact-create",
    ),
    path(
        "<int:pk>/edit-contact-update/",
        login_required(ContactUpdateView.as_view()),
        name="edit-contact-update",
    ),
    path(
        "<int:pk>/edit-request-contact-details/",
        login_required(ContactInformationRequestUpdateView.as_view()),
        name="edit-request-contact-details",
    ),
    path(
        "<int:pk>/edit-initial-testing-details/",
        login_required(InitialTestingDetailsUpdateView.as_view()),
        name="edit-initial-testing-details",
    ),
    path(
        "<int:pk>/edit-initial-testing-outcome/",
        login_required(InitialTestingOutcomeUpdateView.as_view()),
        name="edit-initial-testing-outcome",
    ),
    path(
        "<int:pk>/edit-report-draft/",
        login_required(ReportDraftUpdateView.as_view()),
        name="edit-report-draft",
    ),
    path(
        "<int:pk>/edit-qa-approval/",
        login_required(QAApprovalUpdateView.as_view()),
        name="edit-qa-approval",
    ),
    path(
        "<int:pk>/edit-publish-report/",
        login_required(PublishReportUpdateView.as_view()),
        name="edit-publish-report",
    ),
    path(
        "<int:pk>/edit-report-sent/",
        login_required(CorrespondenceReportSentUpdateView.as_view()),
        name="edit-report-sent",
    ),
    path(
        "<int:pk>/edit-report-acknowledged/",
        login_required(CorrespondenceReportAcknowledgedUpdateView.as_view()),
        name="edit-report-acknowledged",
    ),
    path(
        "<int:pk>/edit-12-week-deadline/",
        login_required(CorrespondenceTwelveWeekDeadlineUpdateView.as_view()),
        name="edit-12-week-deadline",
    ),
    path(
        "<int:pk>/edit-12-week-request-update/",
        login_required(CorrespondenceTwelveWeekRequestUpdateView.as_view()),
        name="edit-12-week-request-update",
    ),
    path(
        "<int:pk>/edit-12-week-acknowledged/",
        login_required(CorrespondenceTwelveWeekAcknowledgedUpdateView.as_view()),
        name="edit-12-week-acknowledged",
    ),
    path(
        "<int:pk>/edit-retest-result/",
        login_required(RetestResultUpdateView.as_view()),
        name="edit-retest-result",
    ),
    path(
        "<int:pk>/edit-retest-summary/",
        login_required(RetestSummaryUpdateView.as_view()),
        name="edit-retest-summary",
    ),
    path(
        "<int:pk>/edit-retest-website-compliance/",
        login_required(RetestWebsiteComplianceUpdateView.as_view()),
        name="edit-retest-website-compliance",
    ),
    path(
        "<int:pk>/edit-retest-disproportionate-burden/",
        login_required(RetestDisproportionateBurdenUpdateView.as_view()),
        name="edit-retest-disproportionate-burden",
    ),
    path(
        "<int:pk>/edit-retest-statement-compliance/",
        login_required(RetestStatementComplianceUpdateView.as_view()),
        name="edit-retest-statement-compliance",
    ),
    path(
        "<int:pk>/edit-case-close/",
        login_required(CaseCloseUpdateView.as_view()),
        name="edit-case-close",
    ),
    path(
        "<int:pk>/edit-equality-body-metadata/",
        login_required(EnforcementBodyMetadataUpdateView.as_view()),
        name="edit-equality-body-metadata",
    ),
    path(
        "<int:pk>/zendesk-tickets/",
        login_required(CaseZendeskTicketsDetailView.as_view()),
        name="zendesk-tickets",
    ),
    path(
        "<int:case_id>/create-zendesk-ticket/",
        login_required(ZendeskTicketCreateView.as_view()),
        name="create-zendesk-ticket",
    ),
    path(
        "<int:pk>/update-zendesk-ticket/",
        login_required(ZendeskTicketUpdateView.as_view()),
        name="update-zendesk-ticket",
    ),
    path(
        "<int:pk>/confirm-delete-zendesk-ticket/",
        login_required(ZendeskTicketConfirmDeleteUpdateView.as_view()),
        name="confirm-delete-zendesk-ticket",
    ),
    path(
        "<int:pk>/edit-unresponsive-psb/",
        login_required(UnresponsivePSBUpdateView.as_view()),
        name="edit-unresponsive-psb",
    ),
    path(
        "<int:pk>/history/",
        login_required(DetailedCaseHistoryDetailView.as_view()),
        name="case-history",
    ),
]
