# Generated by Django 4.2.8 on 2024-01-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("notifications", "0001_initial"),
        ("notifications", "0002_auto_20210930_1621"),
        ("notifications", "0003_auto_20220127_1444"),
        ("notifications", "0004_rename_notifications_notification_and_more"),
        ("notifications", "0005_alter_notification_list_description_and_more"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="notification_settings_user",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("email_notifications_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "NotificationSetting",
                "verbose_name_plural": "NotificationSettings",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                ("path", models.TextField(default="")),
                ("list_description", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_date"],
            },
        ),
    ]
