# Generated by Django 5.0.6 on 2024-06-12 08:10

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_populate_wcag_definitions"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("qa-comment", "QA comment"),
                            ("report-approved", "Report approved"),
                            ("reminder", "Reminder"),
                            ("overdue", "Overdue"),
                            ("postcase", "Post case"),
                        ],
                        default="reminder",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(default="")),
                ("read", models.BooleanField(default=False)),
                ("action", models.TextField(default="N/A")),
                ("updated", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
