# Generated by Django 5.2.1 on 2025-06-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_basecase"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="base_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cases.basecase",
            ),
        ),
    ]
