# Generated by Django 3.2.8 on 2022-01-27 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_auto_20210930_1621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notificationssettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name="notification_settings_user",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
