# Generated by Django 5.2.1 on 2025-06-04 13:39

from django.db import migrations


def populate_base_case(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")
    Task = apps.get_model("notifications", "Task")
    for count, simplified_case in enumerate(
        SimplifiedCase.objects.all().order_by("id"), start=1
    ):
        print(f"{count}: Migrating Tasks Case number {simplified_case.case_number}")
        for task in Task.objects.filter(case_id=simplified_case.case_id):
            task.base_case_id = simplified_case.basecase_ptr
            task.save()


def reverse_code(apps, schema_editor):
    Task = apps.get_model("notifications", "Task")
    Task.objects.all().update(base_case_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_task_base_case"),
        ("simplified", "0003_populate_simplified_cases"),
    ]

    operations = [
        migrations.RunPython(populate_base_case, reverse_code=reverse_code),
    ]
