# Generated by Django 5.0.6 on 2024-06-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_populate_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
