# Generated by Django 4.1a1 on 2022-06-09 07:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0003_auto_20220127_1444"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notifications",
            new_name="Notification",
        ),
        migrations.RenameModel(
            old_name="NotificationsSettings",
            new_name="NotificationSetting",
        ),
    ]
