# Generated by Django 5.0.6 on 2024-07-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_task_updated"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
