# Generated by Django 4.1.1 on 2022-09-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_rename_notifications_notification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="list_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="notification",
            name="path",
            field=models.TextField(default=""),
        ),
    ]
