# Generated by Django 6.0.1 on 2026-01-26 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_alter_basecase_status"),
        ("notifications", "0004_remove_task_case"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("qa-comment", "QA comment"),
                            ("report-approved", "Report approved"),
                            ("reminder", "Reminder"),
                            ("postcase", "Post case"),
                        ],
                        default="reminder",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("text", models.TextField(default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "base_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cases.basecase"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casetask_completedby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casetask_createdby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("recipients", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
