# Generated by Django 6.0.1 on 2026-01-26 09:32
from datetime import datetime, timezone
from unittest.mock import Mock, patch

from django.db import migrations

DEFAULT_CREATED_DATE: datetime = datetime(1970, 1, 1, tzinfo=timezone.utc)


def populate_casetasks(apps, schema_editor):  # pylint: disable=unused-argument
    Task = apps.get_model("notifications", "Task")
    CaseTask = apps.get_model("notifications", "CaseTask")
    for task in Task.objects.all().order_by("id"):
        with patch(
            "django.utils.timezone.now",
            Mock(return_value=DEFAULT_CREATED_DATE),
        ):
            case_task = CaseTask.objects.create(
                type=task.type,
                due_date=task.date,
                text=task.description,
                base_case=task.base_case,
                is_complete=task.read,
            )
            case_task.recipients.add(task.user)
        with patch(
            "django.utils.timezone.now",
            Mock(return_value=task.updated),
        ):
            case_task.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    CaseTask = apps.get_model("notifications", "CaseTask")
    for case_task in CaseTask.objects.all():
        case_task.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_casetask"),
    ]

    operations = [
        migrations.RunPython(populate_casetasks, reverse_code=reverse_code),
    ]
