# Generated by Django 4.2.8 on 2024-02-02 09:52

from django.db import migrations


def update_notification_paths(apps, schema_editor):  # pylint: disable=unused-argument
    Notification = apps.get_model("notifications", "Notification")
    for notification in Notification.objects.all():
        path = notification.path
        if "qa-process" in path:
            notification.path = path.replace("qa-process", "qa-comments")
            notification.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_notification_list_description_and_more"),
    ]

    operations = [
        migrations.RunPython(update_notification_paths, reverse_code=reverse_code),
    ]
