# Generated by Django 5.0.4 on 2024-05-29 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cases",
            "0094_alter_casecompliance_statement_compliance_state_12_week_and_more",
        ),
        ("notifications", "0006_migrate_notification_paths"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("qa-comment", "QA comment"),
                            ("report-approved", "Report approved"),
                            ("reminder", "Reminder"),
                        ],
                        default="notification",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(default="")),
                ("action", models.TextField(default="N/A")),
                ("read", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
