# Generated by Django 5.0.4 on 2024-05-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_populate_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
