"""
Initial migration for cases app

Generated by Django 3.2.4 on 2021-06-11 10:07
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("", "All"),
                            ("new-case", "New case"),
                            ("test-in-progress", "Test in progress"),
                            ("report-in-progress", "Report in progress"),
                            ("awaiting-response", "Awaiting response to report"),
                            ("12w-due", "12 Week review due"),
                            ("12w-sent", "12 Week review sent"),
                            ("escalated", "Case sent to supporting bodies"),
                            ("complete", "Complete"),
                            ("archived", "Archived"),
                            ("not-a-psb", "Not a public sector body"),
                        ],
                        default="new-case",
                        max_length=200,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[("simple", "Simple"), ("detailed", "Detailed")],
                        default="simple",
                        max_length=10,
                    ),
                ),
                ("home_page_url", models.TextField(blank=True, default="")),
                ("domain", models.TextField(blank=True, default="")),
                ("application", models.CharField(default="N/A", max_length=200)),
                ("organisation_name", models.TextField(blank=True, default="")),
                ("service_name", models.TextField(blank=True, default="")),
                (
                    "website_type",
                    models.CharField(
                        choices=[
                            ("public", "Public website"),
                            ("int-extranet", "Intranet/Extranet"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="public",
                        max_length=100,
                    ),
                ),
                (
                    "case_origin",
                    models.CharField(
                        choices=[
                            ("org", "Organisation"),
                            ("list", "Website list"),
                            ("complaint", "Complaint"),
                        ],
                        default="org",
                        max_length=200,
                    ),
                ),
                (
                    "zendesk_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "trello_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_public_sector_body", models.BooleanField(default=True)),
                (
                    "test_results_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "test_status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("in-progress", "In progress"),
                            ("not-started", "Not started"),
                        ],
                        default="not-started",
                        max_length=200,
                    ),
                ),
                ("is_website_compliant", models.BooleanField(default=False)),
                ("test_notes", models.TextField(blank=True, default="")),
                (
                    "report_draft_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "report_review_status",
                    models.CharField(
                        choices=[
                            ("ready-to-review", "Yes"),
                            ("in-progress", "In progress"),
                            ("not-started", "Not started"),
                        ],
                        default="not-started",
                        max_length=200,
                    ),
                ),
                (
                    "report_approved_status",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "Further work is needed")],
                        default="no",
                        max_length=200,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True, default="")),
                (
                    "report_final_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("report_sent_date", models.DateField(blank=True, null=True)),
                ("report_acknowledged_date", models.DateField(blank=True, null=True)),
                ("week_12_followup_date", models.DateField(blank=True, null=True)),
                ("psb_progress_notes", models.TextField(blank=True, default="")),
                (
                    "week_12_followup_email_sent_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "week_12_followup_email_acknowledgement_date",
                    models.DateField(blank=True, null=True),
                ),
                ("is_website_retested", models.BooleanField(default=False)),
                ("is_disproportionate_claimed", models.BooleanField(default=False)),
                ("disproportionate_notes", models.TextField(blank=True, default="")),
                (
                    "accessibility_statement_decison",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("partially", "Partially compliant"),
                            ("not-compliant", "Not compliant"),
                            ("other", "Other"),
                        ],
                        default="not-compliant",
                        max_length=200,
                    ),
                ),
                (
                    "accessibility_statement_url",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "accessibility_statement_notes",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "compliance_decision",
                    models.CharField(
                        choices=[
                            ("inaction", "No further action"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=200,
                    ),
                ),
                ("compliance_decision_notes", models.TextField(blank=True, default="")),
                ("compliance_email_sent_date", models.DateField(blank=True, null=True)),
                (
                    "sent_to_enforcement_body_sent_date",
                    models.DateField(blank=True, null=True),
                ),
                ("is_case_completed", models.BooleanField(default=False)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "simplified_test_filename",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_auditor_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ManyToManyField(blank=True, null=True, to="common.Region"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_reviewer_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=200)),
                ("job_title", models.CharField(blank=True, default="", max_length=200)),
                ("detail", models.CharField(blank=True, default="", max_length=200)),
                ("preferred", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField()),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.case"
                    ),
                ),
            ],
        ),
    ]
