# Generated by Django 3.2.2 on 2021-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="accessibility_statement_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="accessibility_statement_url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="auditor",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="compliance_decision_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="compliance_email_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="created",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="disproportionate_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="domain",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="home_page_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="organisation_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="psb_progress_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="region",
            field=models.CharField(blank=True, default="London", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="report_acknowledged_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="report_draft_url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="report_final_url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="report_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="reviewer",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="reviewer_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="sector",
            field=models.CharField(blank=True, default="Sector", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="sent_to_enforcement_body_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="simplified_test_filename",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "All"),
                    ("new-case", "New case"),
                    ("test-in-progress", "Test in progress"),
                    ("report-in-progress", "Report in progress"),
                    ("awaiting-response", "Awaiting response to report"),
                    ("12w-due", "12 Week review due"),
                    ("12w-sent", "12 Week review sent"),
                    ("escalated", "Case sent to supporting bodies"),
                    ("complete", "Complete"),
                    ("archived", "Archived"),
                    ("not-a-psb", "Not a public sector body"),
                ],
                default="new-case",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="test_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="test_results_url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="trello_url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="week_12_followup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="week_12_followup_email_acknowledgement_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="week_12_followup_email_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="zendesk_url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="detail",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
