# Generated by Django 3.2.4 on 2021-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='accessibility_statement_decison',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('partially', 'Partially compliant'), ('not-compliant', 'Not compliant'), ('missing', 'Missing accessibility statement'), ('unknown', 'Not known')], default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='escalation_state',
            field=models.CharField(choices=[('no-action', 'No further action is required and correspondence has closed regarding this issue'), ('ongoing', 'Correspondence ongoing'), ('not-started', 'Not started')], default='not-started', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_type',
            field=models.CharField(choices=[('simplified', 'Simplified'), ('detailed', 'Detailed'), ('mobile', 'Mobile')], default='simplified', max_length=10),
        ),
    ]
