# Generated by Django 3.2.4 on 2021-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="contact_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="enforcement_correspondence_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="final_decision_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="report_correspondence_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="reporting_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="testing_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="twelve_week_correspondence_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="accessibility_statement_state",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="accessibility_statement_state_final",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="enforcement_body",
            field=models.CharField(
                choices=[
                    ("ehrc", "Equality and Human Rights Commission"),
                    ("ecni", "Equality Commission Northern Ireland"),
                ],
                default="ehrc",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_website_compliant",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("no-further-action", "No further action"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_website_compliant_final",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("no-further-action", "No further action"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
