# Generated by Django 3.2.4 on 2021-08-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accessibility_statement_decison_twelve_weeks',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('partially', 'Partially compliant'), ('not-compliant', 'Not compliant'), ('missing', 'Statement missing'), ('unknown', 'Not known')], default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='accessibility_statement_notes_twelve_weeks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='compliance_decision_notes_twelve_weeks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='case',
            name='is_website_compliant_twelve_weeks',
            field=models.CharField(choices=[('yes', 'Compliant'), ('partially', 'Partially compliant'), ('no', 'Not compliant'), ('unknown', 'Not known')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_completed',
            field=models.CharField(choices=[('no-action', 'The case requires no further action'), ('escalated', 'The audit needs to be sent to the relevant equalities body'), ('no-decision', 'Decision not reached')], default='no-decision', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('', 'All'), ('unknown', 'Unknown'), ('unassigned-case', 'Unassigned case'), ('new-case', 'New case'), ('test-in-progress', 'Test in progress'), ('report-in-progress', 'Report in progress'), ('qa-in-progress', 'QA in progress'), ('report-ready-to-send', 'Report ready to send'), ('in-report-correspondence', 'In report correspondence'), ('in-probation-period', 'In probation period'), ('in-12-week-correspondence', 'In 12 week correspondence'), ('final-decision-due', 'Final decision due'), ('in-correspondence-with-equalities-body', 'In correspondence with equalities body'), ('complete', 'Complete'), ('archived', 'Archived')], default='new-case', max_length=200),
        ),
    ]
