# Generated by Django 3.2.4 on 2021-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='is_case_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_disproportionate_claimed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='is_website_compliant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='test_type',
            field=models.CharField(choices=[('simple', 'Simplified'), ('detailed', 'Detailed')], default='simple', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
