# Generated by Django 3.2.2 on 2021-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="domain",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
