# Generated by Django 3.2.4 on 2021-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="case_origin",
        ),
        migrations.AddField(
            model_name="case",
            name="enforcement_body",
            field=models.CharField(
                choices=[
                    ("ecni", "Equality Commission Northern Ireland"),
                    ("ehrc", "Equality and Himan Rights Commission"),
                ],
                default="ehrc",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="is_complaint",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("simple", "Simplified"),
                    ("detailed", "Detailed"),
                    ("mobile", "Mobile"),
                ],
                default="simple",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="website_type",
            field=models.CharField(
                choices=[
                    ("public", "Public website"),
                    ("int-extranet", "Intranet/Extranet"),
                    ("n/a", "N/A"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
