# Generated by Django 3.2.4 on 2021-06-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_auto_20210624_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="website_type",
            field=models.CharField(
                choices=[
                    ("public", "Public website"),
                    ("int-extranet", "Intranet/Extranet"),
                    ("n/a", "N/A"),
                ],
                default="public",
                max_length=100,
            ),
        ),
    ]
