# Generated by Django 3.2.4 on 2021-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_auto_20210812_1011"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="psb_appeal_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="accessibility_statement_decison",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("partially", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("missing", "Missing accessibility statement"),
                    ("unknown", "Not known"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="accessibility_statement_decison_final",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("partially", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("missing", "Missing accessibility statement"),
                    ("unknown", "Not known"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_completed",
            field=models.CharField(
                choices=[
                    ("no-action", "The case requires no further action"),
                    (
                        "escalated",
                        "The audit needs to be sent to the relevant equalities body",
                    ),
                    ("no-decision", "Decision not reached"),
                ],
                default="no-decision",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="escalation_state",
            field=models.CharField(
                choices=[
                    (
                        "no-action",
                        "No further action is required and correspondence has closed regarding this issue",
                    ),
                    ("ongoing", "Correspondence ongoing"),
                    ("not-started", "Not started"),
                ],
                default="not-started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "All"),
                    ("unknown", "Unknown"),
                    ("unassigned-case", "Unassigned case"),
                    ("new-case", "New case"),
                    ("test-in-progress", "Test in progress"),
                    ("report-in-progress", "Report in progress"),
                    ("qa-in-progress", "QA in progress"),
                    ("report-ready-to-send", "Report ready to send"),
                    ("in-report-correspondence", "In report correspondence"),
                    ("in-probation-period", "In probation period"),
                    ("in-12-week-correspondence", "In 12 week correspondence"),
                    ("final-decision-due", "Final decision due"),
                    (
                        "in-correspondence-with-equalities-body",
                        "In correspondence with equalities body",
                    ),
                    ("complete", "Complete"),
                    ("archived", "Archived"),
                ],
                default="new-case",
                max_length=200,
            ),
        ),
    ]
