# Generated by Django 3.2.4 on 2021-07-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_auto_20210727_1151"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="detail",
            new_name="email",
        ),
    ]
