# Generated by Django 5.0.6 on 2024-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_populate_wcag_definitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="no_contact_four_week_chaser_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="no_contact_four_week_chaser_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="no_contact_four_week_chaser_sent_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="no_contact_one_week_chaser_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="no_contact_one_week_chaser_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="no_contact_one_week_chaser_sent_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="seven_day_no_contact_request_sent_to",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
