# Generated by Django 3.2.2 on 2021-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_case_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="website_name",
            new_name="organisation_name",
        ),
        migrations.AddField(
            model_name="case",
            name="application",
            field=models.CharField(default="N/A", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="case_origin",
            field=models.CharField(default="Organisation", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="is_public_sector_body",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="case",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="region",
            field=models.CharField(default="London", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="sector",
            field=models.CharField(default="Sector", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="test_type",
            field=models.CharField(
                choices=[("simple", "Simple"), ("detailed", "Detailed")],
                default="simple",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="trello_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="website_type",
            field=models.CharField(
                choices=[("public", "Public Website"), ("intranet", "Intranet")],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="zendesk_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "All"),
                    ("new-case", "New case"),
                    ("test-in-progress", "Test in progress"),
                    ("report-in-progress", "Report in progress"),
                    ("awaiting-response", "Awaiting response to report"),
                    ("12w-due", "12 Week review due"),
                    ("12w-sent", "12 Week review sent"),
                    ("escalated", "Case sent to supporting bodies"),
                    ("complete", "Complete"),
                    ("archived", "Archived"),
                    ("not-a-psb", "Not a public sector body"),
                ],
                max_length=50,
            ),
        ),
    ]
