# Generated by Django 3.2.4 on 2021-09-03 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_auto_20210903_0805"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="is_12_week_correspondence_complete",
        ),
        migrations.RemoveField(
            model_name="case",
            name="is_case_details_complete",
        ),
        migrations.RemoveField(
            model_name="case",
            name="is_contact_details_complete",
        ),
        migrations.RemoveField(
            model_name="case",
            name="is_enforcement_correspondence_complete",
        ),
        migrations.RemoveField(
            model_name="case",
            name="is_final_decision_complete",
        ),
        migrations.RemoveField(
            model_name="case",
            name="is_report_correspondence_complete",
        ),
        migrations.RemoveField(
            model_name="case",
            name="is_reporting_details_complete",
        ),
        migrations.RemoveField(
            model_name="case",
            name="is_testing_details_complete",
        ),
    ]
