# Generated by Django 3.2.4 on 2021-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20210816_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='psb_location',
            field=models.CharField(choices=[('england', 'England'), ('scotland', 'Scotland'), ('wales', 'Wales'), ('northern_ireland', 'Northern Ireland'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_completed',
            field=models.CharField(choices=[('escalated', 'The audit needs to be sent to the relevant equalities body'), ('no-action', 'The case requires no further action'), ('no-decision', 'Decision not reached')], default='no-decision', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('', 'All'), ('unknown', 'Unknown'), ('unassigned-case', 'Unassigned case'), ('new-case', 'New case'), ('test-in-progress', 'Test in progress'), ('report-in-progress', 'Report in progress'), ('qa-in-progress', 'QA in progress'), ('report-ready-to-send', 'Report ready to send'), ('in-report-correspondence', 'In report correspondence'), ('in-probation-period', 'In probation period'), ('in-12-week-correspondence', 'In 12 week correspondence'), ('final-decision-due', 'Final decision due'), ('in-correspondence-with-equalities-body', 'In correspondence with equalities body'), ('complete', 'Complete'), ('deleted', 'Deleted')], default='new-case', max_length=200),
        ),
    ]
