# Generated by Django 5.0.7 on 2024-07-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_case_no_contact_four_week_chaser_due_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="find_contact_details_complete_date",
            new_name="four_week_contact_details_complete_date",
        ),
        migrations.AddField(
            model_name="case",
            name="no_psb_contact_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="one_week_contact_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="request_contact_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
