# Generated by Django 3.2.4 on 2021-07-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_rename_detail_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="report_final_url",
        ),
        migrations.RemoveField(
            model_name="case",
            name="report_is_approved",
        ),
        migrations.RemoveField(
            model_name="case",
            name="report_is_ready_to_review",
        ),
        migrations.AddField(
            model_name="case",
            name="report_final_odt_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="report_final_pdf_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="accessibility_statement_decison",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("partially", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("missing", "Statement missing"),
                    ("unknown", "Not known"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="accessibility_statement_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="archive_reason",
            field=models.CharField(
                choices=[
                    ("not-psb", "Organisation is not a public sector body"),
                    ("mistake", "Case was opened by mistake"),
                    ("duplicate", "This case was a duplicate case"),
                    ("other", "Other"),
                ],
                default="not-psb",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_website_compliant",
            field=models.CharField(
                choices=[
                    ("yes", "Compliant"),
                    ("partially", "Partially compliant"),
                    ("no", "Not compliant"),
                    ("unknown", "Not known"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="report_approved_status",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("in-progress", "Further work is needed"),
                    ("not-started", "Not started"),
                ],
                default="not-started",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="report_draft_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="test_results_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="trello_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="zendesk_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
