# Generated by Django 3.2.4 on 2021-09-07 10:50

from django.db import migrations

UPDATE_SQL =  """
UPDATE cases_case SET accessibility_statement_state = 'compliant' WHERE accessibility_statement_state = 'yes';
UPDATE cases_case SET accessibility_statement_state = 'not-compliant' WHERE accessibility_statement_state = 'no';
UPDATE cases_case SET accessibility_statement_state_final = 'compliant' WHERE accessibility_statement_state_final = 'yes';
UPDATE cases_case SET accessibility_statement_state_final = 'not-compliant' WHERE accessibility_statement_state_final = 'no';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20210903_0831'),
    ]

    operations = [
        migrations.RunSQL(UPDATE_SQL, reverse_sql="")
    ]
