# Generated by Django 5.0.7 on 2024-08-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cases",
            "0005_rename_find_contact_details_complete_date_case_four_week_contact_details_complete_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="enable_correspondence_process",
            field=models.BooleanField(default=False),
        ),
    ]
