# Generated by Django 5.1.1 on 2024-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_enable_cores_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="qa_approval_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
