# Generated by Django 3.2.4 on 2021-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20210714_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='correspondance_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
