# Generated by Django 3.2.2 on 2021-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_contact_detail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="name",
        ),
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_origin",
            field=models.CharField(
                choices=[
                    ("org", "Organisation"),
                    ("list", "Website list"),
                    ("complaint", "Complaint"),
                ],
                default="org",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="website_type",
            field=models.CharField(
                choices=[
                    ("public", "Public website"),
                    ("int-extranet", "Intranet/Extranet"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="public",
                max_length=100,
            ),
        ),
    ]
