# Generated by Django 3.2.2 on 2021-06-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_auto_20210603_1412"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
