# Generated by Django 3.2.7 on 2021-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0007_case_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_completed",
            field=models.CharField(
                choices=[
                    ("further-action-required", "Yes"),
                    ("no-action", "No"),
                    ("no-decision", "Not selected"),
                ],
                default="no-decision",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="recommendation_for_enforcement",
            field=models.CharField(
                choices=[
                    ("no-further-action", "No further action"),
                    ("other", "No recommendation made"),
                    ("unknown", "Not selected"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "All"),
                    ("unknown", "Unknown"),
                    ("unassigned-case", "Unassigned case"),
                    ("new-case", "New case"),
                    ("test-in-progress", "Test in progress"),
                    ("report-in-progress", "Report in progress"),
                    ("unassigned-qa-case", "Report ready to QA"),
                    ("qa-in-progress", "QA in progress"),
                    ("report-ready-to-send", "Report ready to send"),
                    ("in-report-correspondence", "Report sent"),
                    (
                        "in-probation-period",
                        "Report acknowledged waiting for 12 week deadline",
                    ),
                    ("in-12-week-correspondence", "After 12 week correspondence"),
                    ("final-decision-due", "Final decision due"),
                    (
                        "in-correspondence-with-equalities-body",
                        "In correspondence with equalities body",
                    ),
                    ("complete", "Complete"),
                    ("deleted", "Deleted"),
                ],
                default="new-case",
                max_length=200,
            ),
        ),
    ]
