# Generated by Django 5.1.8 on 2025-04-08 15:02

from datetime import datetime, timezone

from django.db import migrations


def reset_case_updated(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    lowest_unix_datetime: datetime = datetime(1970, 1, 1, tzinfo=timezone.utc)
    Case.objects.all().update(updated=lowest_unix_datetime)


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_archive_pre_statement_check_cases"),
    ]

    operations = [
        migrations.RunPython(reset_case_updated, reverse_code=reverse_code),
    ]
