# Generated by Django 3.2.4 on 2021-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_auto_20210716_0923"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="no_psb_contact",
            field=models.BooleanField(default=False),
        ),
    ]
