# Generated by Django 3.2.2 on 2021-06-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_contact_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="test_notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="test_results_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="test_status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("in-progress", "In progress"),
                    ("not-started", "Not started"),
                ],
                default="not-started",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="website_compliant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="case",
            name="domain",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="home_page_url",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="organisation_name",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "All"),
                    ("new-case", "New case"),
                    ("test-in-progress", "Test in progress"),
                    ("report-in-progress", "Report in progress"),
                    ("awaiting-response", "Awaiting response to report"),
                    ("12w-due", "12 Week review due"),
                    ("12w-sent", "12 Week review sent"),
                    ("escalated", "Case sent to supporting bodies"),
                    ("complete", "Complete"),
                    ("archived", "Archived"),
                    ("not-a-psb", "Not a public sector body"),
                ],
                max_length=200,
            ),
        ),
    ]
