# Generated by Django 3.2.7 on 2021-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0008_auto_20210909_1347"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-preferred", "-id"]},
        ),
        migrations.AddField(
            model_name="case",
            name="accessibility_statement_screenshot_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_website_compliant",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("partially-compliant", "Partially compliant"),
                    ("other", "Other"),
                    ("unknown", "Not selected"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
