# Generated by Django 3.2.4 on 2021-07-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_case_no_psb_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='enforcement_body_correspondance_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
