# Generated by Django 3.2.2 on 2021-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_rename_website_compliant_case_is_website_compliant"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="report_acknowledged_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="report_approved_status",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "Further work is needed")],
                default="no",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="report_draft_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="report_final_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="report_review_status",
            field=models.CharField(
                choices=[
                    ("ready-to-review", "Yes"),
                    ("in-progress", "In progress"),
                    ("not-started", "Not started"),
                ],
                default="not-started",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="report_sent_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="reviewer",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="reviewer_notes",
            field=models.TextField(default=""),
        ),
    ]
