# Generated by Django 5.2.1 on 2025-05-14 09:41
import ast
import json

from django.db import migrations


def cleanup_case_histories(apps, schema_editor):
    EventHistory = apps.get_model("cases", "EventHistory")
    count: int = 0

    for event_history in EventHistory.objects.all():
        try:
            difference_dict: dict[str, str] = json.loads(event_history.difference)
        except json.decoder.JSONDecodeError:
            difference_dict: dict[str, str] = ast.literal_eval(event_history.difference)
            event_history.difference = json.dumps(difference_dict)
            event_history.save()
            count += 1
            if count % 1000 == 0:
                print(f"{count} case event history entries converted to valid json")


def reverse_code(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_populate_events"),
    ]

    operations = [
        migrations.RunPython(cleanup_case_histories, reverse_code=reverse_code),
    ]
