# Generated by Django 3.2.7 on 2021-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0010_alter_case_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="is_website_compliant_final",
        ),
        migrations.AlterField(
            model_name="case",
            name="case_completed",
            field=models.CharField(
                choices=[
                    ("further-action", "Yes"),
                    ("no-action", "No"),
                    ("no-decision", "Not selected"),
                ],
                default="no-decision",
                max_length=30,
            ),
        ),
    ]
