# Generated by Django 5.2.1 on 2025-05-21 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_cleanup_case_histories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventhistory",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "Event histories",
            },
        ),
        migrations.AlterField(
            model_name="casestatus",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="cases.case"
            ),
        ),
    ]
