# Generated by Django 3.2.7 on 2021-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0011_remove_case_is_website_compliant_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="enforcement_body_interested",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("not-selected", "Not selected"),
                ],
                default="not-selected",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="twelve_week_response_state",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("not-selected", "Not selected"),
                ],
                default="not-selected",
                max_length=20,
            ),
        ),
    ]
