# Generated by Django 3.2.2 on 2021-06-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_auto_20210604_1233"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="accessibility_statement_decison",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("partially", "Partially compliant"),
                    ("not-compliant", "Not compliant"),
                    ("other", "Other"),
                ],
                default="not-compliant",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="accessibility_statement_notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="accessibility_statement_url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="completed",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="compliance_decision",
            field=models.CharField(
                choices=[
                    ("inaction", "No further action"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="compliance_decision_notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="compliance_email_sent_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="disproportionate_notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="is_case_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="case",
            name="is_disproportionate_claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="case",
            name="is_website_retested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="case",
            name="psb_progress_notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="sent_to_enforcement_body_sent_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="week_12_followup_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="week_12_followup_email_acknowledgement_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="week_12_followup_email_sent_date",
            field=models.DateField(null=True),
        ),
    ]
