# Generated by Django 5.2.1 on 2025-06-03 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_alter_eventhistory_options_alter_casestatus_case"),
        ("common", "0008_delete_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseCase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("case_number", models.IntegerField(default=1)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("unassigned-case", "Unassigned case"),
                            ("test-in-progress", "Test in progress"),
                            ("report-in-progress", "Report in progress"),
                            ("unassigned-qa-case", "Report ready to QA"),
                            ("qa-in-progress", "QA in progress"),
                            ("report-ready-to-send", "Report ready to send"),
                            ("in-report-correspondence", "Report sent"),
                            (
                                "in-probation-period",
                                "Report acknowledged waiting for 12-week deadline",
                            ),
                            (
                                "in-12-week-correspondence",
                                "After 12-week correspondence",
                            ),
                            ("reviewing-changes", "Reviewing changes"),
                            ("final-decision-due", "Final decision due"),
                            (
                                "case-closed-waiting-to-be-sent",
                                "Case closed and waiting to be sent to equalities body",
                            ),
                            (
                                "case-closed-sent-to-equalities-body",
                                "Case closed and sent to equalities body",
                            ),
                            (
                                "in-correspondence-with-equalities-body",
                                "In correspondence with equalities body",
                            ),
                            ("complete", "Complete"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="unassigned-case",
                        max_length=200,
                    ),
                ),
                ("created", models.DateTimeField(blank=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("simplified", "Simplified"),
                            ("detailed", "Detailed"),
                            ("mobile", "Mobile"),
                        ],
                        default="simplified",
                        max_length=10,
                    ),
                ),
                ("home_page_url", models.TextField(blank=True, default="")),
                ("domain", models.TextField(blank=True, default="")),
                ("organisation_name", models.TextField(blank=True, default="")),
                (
                    "psb_location",
                    models.CharField(
                        choices=[
                            ("england", "England"),
                            ("scotland", "Scotland"),
                            ("wales", "Wales"),
                            ("northern_ireland", "Northern Ireland"),
                            ("uk_wide", "UK-wide"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "enforcement_body",
                    models.CharField(
                        choices=[
                            ("ehrc", "Equality and Human Rights Commission"),
                            ("ecni", "Equality Commission Northern Ireland"),
                        ],
                        default="ehrc",
                        max_length=20,
                    ),
                ),
                (
                    "is_complaint",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                (
                    "parental_organisation_name",
                    models.TextField(blank=True, default=""),
                ),
                ("website_name", models.TextField(blank=True, default="")),
                (
                    "is_feedback_requested",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="no",
                        max_length=20,
                    ),
                ),
                ("case_details_complete_date", models.DateField(blank=True, null=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basecase_auditor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basecase_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basecase_reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.sector",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.subcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
