# Generated by Django 5.2.1 on 2025-06-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_basecase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basecase",
            options={"ordering": ["-id"]},
        ),
    ]
