# Generated by Django 3.2.8 on 2021-10-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_alter_case_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="qa_process_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="report_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
