# Generated by Django 5.2.3 on 2025-07-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0020_alter_retest_options_remove_audit_case_and_more"),
        ("cases", "0014_alter_basecase_options"),
        ("comments", "0004_remove_comment_case"),
        ("exports", "0004_remove_exportcase_case"),
        ("notifications", "0004_remove_task_case"),
        ("reports", "0011_remove_report_case_remove_reportvisitsmetrics_case"),
        ("s3_read_write", "0004_remove_s3report_case"),
        ("simplified", "0005_remove_simplifiedcase_case"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="auditor",
        ),
        migrations.RemoveField(
            model_name="case",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="case",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="case",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="case",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="zendeskticket",
            name="case",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="case",
        ),
        migrations.RemoveField(
            model_name="equalitybodycorrespondence",
            name="case",
        ),
        migrations.RemoveField(
            model_name="caseevent",
            name="case",
        ),
        migrations.RemoveField(
            model_name="eventhistory",
            name="case",
        ),
        migrations.RemoveField(
            model_name="casecompliance",
            name="case",
        ),
        migrations.RemoveField(
            model_name="caseevent",
            name="done_by",
        ),
        migrations.RemoveField(
            model_name="eventhistory",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="eventhistory",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="CaseStatus",
        ),
        migrations.DeleteModel(
            name="ZendeskTicket",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="EqualityBodyCorrespondence",
        ),
        migrations.DeleteModel(
            name="Case",
        ),
        migrations.DeleteModel(
            name="CaseCompliance",
        ),
        migrations.DeleteModel(
            name="CaseEvent",
        ),
        migrations.DeleteModel(
            name="EventHistory",
        ),
    ]
