# Generated by Django 3.2.8 on 2021-10-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0015_case_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="twelve_week_correspondence_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
