# Generated by Django 3.2.4 on 2021-07-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_auto_20210721_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='equalities_body_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('no-correspondence', 'No correspondence'), ('in-correspondence', 'In correspondence'), ('completed', 'Completed')], default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='qa_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('unassigned-qa-case', 'Unassigned QA case'), ('in-qa', 'In QA'), ('qa-approved', 'QA approved')], default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('', 'All'), ('unknown', 'Unknown'), ('unassigned-case', 'Unassigned case'), ('new-case', 'New case'), ('test-in-progress', 'Test in progress'), ('report-in-progress', 'Report in progress'), ('qa-in-progress', 'QA in progress'), ('report-ready-to-send', 'Report ready to send'), ('in-report-correspondence', 'In report correspondence'), ('in-probation-period', 'In probation period'), ('in-12-week-correspondence', 'In 12 week correspondence'), ('final-decision', 'Final decision'), ('complete', 'Complete'), ('archived', 'Archived')], default='new-case', max_length=200),
        ),
    ]
