# Generated by Django 3.2.8 on 2021-10-27 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0016_case_twelve_week_correspondence_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="service_name",
        ),
    ]
