# Generated by Django 5.2.5 on 2025-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_cleanup_case_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecase",
            name="psb_location",
            field=models.CharField(
                choices=[
                    ("england", "England"),
                    ("scotland", "Scotland"),
                    ("wales", "Wales"),
                    ("northern_ireland", "Northern Ireland"),
                    ("uk_wide", "UK-wide or multiple countries"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
