# Generated by Django 5.2.6 on 2025-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_cleanup_case_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecase",
            name="enforcement_body",
            field=models.CharField(
                choices=[
                    ("ehrc", "Equality and Human Rights Commission"),
                    ("ecni", "Equality Commission for Northern Ireland"),
                ],
                default="ehrc",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="basecase",
            name="psb_location",
            field=models.CharField(
                choices=[
                    ("england", "England"),
                    ("scotland", "Scotland"),
                    ("wales", "Wales"),
                    ("northern_ireland", "Northern Ireland"),
                    ("uk_wide", "UK-wide or multiple countries"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="basecase",
            name="status",
            field=models.CharField(
                choices=[
                    ("000-unassigned-case", "Unassigned case"),
                    ("010-initial-psb-info-requested", "Requested information"),
                    ("020-initial-psb-info-chasing", "Chasing initial response"),
                    ("030-initial-psb-info-req-ack", "Acknowledge our request"),
                    ("040-initial-psb-info-received", "Received details and access"),
                    ("050-test-in-progress", "Test in progress"),
                    ("060-report-in-progress", "Report in progress"),
                    ("070-unassigned-qa-case", "Report ready to QA"),
                    ("080-qa-in-progress", "QA in progress"),
                    ("090-report-ready-to-send", "Report ready to send"),
                    ("100-in-report-correspondence", "Report sent"),
                    ("110-awaiting-report-ack", "Waiting for response"),
                    (
                        "120-in-12-week-period",
                        "Report acknowledged waiting for 12-week deadline",
                    ),
                    ("130-12-week-requested-update", "Requested update at 12 weeks"),
                    (
                        "140-after-12-week-correspondence",
                        "After 12-week correspondence",
                    ),
                    ("150-reviewing-changes", "Reviewing changes"),
                    ("160-final-decision-due", "Final decision due"),
                    (
                        "170-case-closed-waiting-to-be-sent",
                        "Case closed and waiting to be sent to equalities body",
                    ),
                    (
                        "180-case-closed-sent-to-equalities-body",
                        "Case closed and sent to equalities body",
                    ),
                    (
                        "190-in-correspondence-with-equalities-body",
                        "In correspondence with equalities body",
                    ),
                    ("200-complete", "Complete"),
                    ("210-blocked", "Blocked"),
                    ("900-deactivated", "Deactivated"),
                    ("910-unknown", "Unknown"),
                ],
                default="000-unassigned-case",
                max_length=200,
            ),
        ),
    ]
