# Generated by Django 5.2.3 on 2025-07-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_cleanup_case_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecase",
            name="status",
            field=models.CharField(
                choices=[
                    ("000-unassigned-case", "Unassigned case"),
                    ("010-initial-psb-info-requested", "Requested information (D&M)"),
                    (
                        "020-initial-psb-info-chasing",
                        "Chasing - no response / missed deadline (D&M)",
                    ),
                    ("030-initial-psb-info-req-ack", "Acknowledge our request (D&M)"),
                    ("040-initial-psb-info-received", "Received Details/Access (D&M)"),
                    ("050-test-in-progress", "Test in progress"),
                    ("060-report-in-progress", "Report in progress"),
                    ("070-unassigned-qa-case", "Report ready to QA"),
                    ("080-qa-in-progress", "QA in progress (S)"),
                    ("090-report-ready-to-send", "Report ready to send"),
                    ("100-in-report-correspondence", "Report sent"),
                    ("110-awaiting-report-ack", "Waiting for response (D)"),
                    (
                        "120-in-12-week-period",
                        "Report acknowledged waiting for 12-week deadline",
                    ),
                    (
                        "130-12-week-requested-update",
                        "Requested update at 12 weeks (D)",
                    ),
                    (
                        "140-after-12-week-correspondence",
                        "After 12-week correspondence",
                    ),
                    ("150-reviewing-changes", "Reviewing changes"),
                    ("160-final-decision-due", "Final decision due (S)"),
                    (
                        "170-case-closed-waiting-to-be-sent",
                        "Case closed and waiting to be sent to equalities body",
                    ),
                    (
                        "180-case-closed-sent-to-equalities-body",
                        "Case closed and sent to equalities body",
                    ),
                    (
                        "190-in-correspondence-with-equalities-body",
                        "In correspondence with equalities body (S)",
                    ),
                    ("200-complete", "Complete"),
                    ("900-deactivated", "Deactivated (S)"),
                    ("910-unknown", "Unknown (S)"),
                ],
                default="000-unassigned-case",
                max_length=200,
            ),
        ),
    ]
