# Generated by Django 3.2.8 on 2021-12-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0018_alter_case_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="psb_location",
            field=models.CharField(
                choices=[
                    ("england", "England"),
                    ("scotland", "Scotland"),
                    ("wales", "Wales"),
                    ("northern_ireland", "Northern Ireland"),
                    ("uk_wide", "UK-wide"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
