# Generated by Django 3.2.8 on 2021-12-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_alter_case_psb_location"),
        ("cases", "0019_alter_case_sector"),
    ]

    operations = []
