# Generated by Django 6.0.1 on 2026-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_alter_basecase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="basecase",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
