# Generated by Django 6.0.1 on 2026-01-27 13:31
from datetime import date

from django.db import migrations

DEFAULT_DUE_DATE: date = date(2026, 7, 1)


def populate_due_date(apps, schema_editor):
    Task = apps.get_model("notifications", "Task")
    BaseCase = apps.get_model("cases", "BaseCase")
    for base_case in BaseCase.objects.filter(status="000-unassigned-case"):
        base_case.due_date = DEFAULT_DUE_DATE
        base_case.save()

    for task in Task.objects.filter(read=False):
        task.base_case.due_date = task.date
        task.base_case.save()


def reverse_code(apps, schema_editor):
    BaseCase = apps.get_model("cases", "BaseCase")
    for base_case in BaseCase.objects.exclude(due_date=None):
        base_case.due_date = None
        base_case.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_basecase_due_date"),
    ]

    operations = [
        migrations.RunPython(populate_due_date, reverse_code=reverse_code),
    ]
