# Generated by Django 3.2.11 on 2022-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0023_auto_20220201_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_updated_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="post_case_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="post_case_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
