# Generated by Django 3.2.11 on 2022-02-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20220201_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='twelve_week_retest_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
