# Generated by Django 4.0.2 on 2022-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_add_post_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='twelve_week_4_week_chaser_sent_date',
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('', 'All'), ('unknown', 'Unknown'), ('unassigned-case', 'Unassigned case'), ('test-in-progress', 'Test in progress'), ('report-in-progress', 'Report in progress'), ('unassigned-qa-case', 'Report ready to QA'), ('qa-in-progress', 'QA in progress'), ('report-ready-to-send', 'Report ready to send'), ('in-report-correspondence', 'Report sent'), ('in-probation-period', 'Report acknowledged waiting for 12 week deadline'), ('in-12-week-correspondence', 'After 12 week correspondence'), ('reviewing-changes', 'Reviewing changes'), ('final-decision-due', 'Final decision due'), ('case-closed-waiting-to-be-sent', 'Case closed and waiting to be sent to equalities body'), ('case-closed-sent-to-equalities-body', 'Case closed and sent to equalities body'), ('in-correspondence-with-equalities-body', 'In correspondence with equalities body'), ('complete', 'Complete'), ('deleted', 'Deleted')], default='unassigned-case', max_length=200),
        ),
    ]
