# Generated by Django 4.0.2 on 2022-04-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_remove_report_ready_for_qa"),
        ("cases", "0027_report_generator"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="published_report_sent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_published_report_sent",
                to="reports.publishedreport",
            ),
        ),
    ]
