# Generated by Django 4.0.2 on 2022-05-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0029_remove_case_published_report_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="enforcement_body_pursuing",
            field=models.CharField(
                choices=[
                    ("yes-completed", "Yes, completed"),
                    ("yes-in-progress", "Yes, in progress"),
                    ("no", "No"),
                ],
                default="no",
                max_length=20,
            ),
        ),
    ]
