# Generated by Django 4.0.2 on 2022-05-17 12:12

from django.db import migrations


def populate_enforcement_body_pursuing(
    apps, schema_editor
):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.all():
        if case.enforcement_body_interested == "yes":
            if case.escalation_state == "no-action":
                case.enforcement_body_pursuing = "yes-completed"
            else:
                case.enforcement_body_pursuing = "yes-in-progress"
            case.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0030_case_enforcement_body_pursuing"),
    ]

    operations = [
        migrations.RunPython(
            populate_enforcement_body_pursuing, reverse_code=reverse_code
        ),
    ]
