# Generated by Django 4.0.2 on 2022-05-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0032_remove_case_enforcement_body_interested_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="twelve_week_4_week_chaser_due_date",
        ),
    ]
