# Generated by Django 4.1a1 on 2022-06-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0034_alter_case_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.TextField(blank=True, default=""),
        ),
    ]
