# Generated by Django 4.1a1 on 2022-06-08 09:21

from django.db import migrations


def populate_contact_name(apps, schema_editor):  # pylint: disable=unused-argument
    Contact = apps.get_model("cases", "Contact")
    for contact in Contact.objects.all():
        contact.name = f"{contact.first_name} {contact.last_name}"
        contact.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0035_contact_name"),
    ]

    operations = [
        migrations.RunPython(populate_contact_name, reverse_code=reverse_code),
    ]
