# Generated by Django 4.1a1 on 2022-06-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0036_populate_contact_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_name",
        ),
    ]
