""" Generated by Django 4.1a1 on 2022-07-13 08:56 """

from django.db import migrations


def data_cleanup(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.filter(status="suspended"):
        case.status = "deactivated"
        case.save()


def undo_cleanup(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.filter(status="deactivated"):
        case.status = "suspended"
        case.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0038_rename_suspend_date_case_deactivate_date_and_more"),
    ]

    operations = [
        migrations.RunPython(
            data_cleanup, reverse_code=undo_cleanup
        ),
    ]
