# Generated by Django 4.1.4 on 2023-01-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0046_populate_case_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="qa_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("unassigned-qa-case", "Unassigned QA case"),
                    ("in-qa", "In QA"),
                    ("qa-approved", "QA approved"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
    ]
