# Generated by Django 4.1.4 on 2023-02-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0047_alter_case_qa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="enforcement_retest_document_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
