# Generated by Django 4.1.4 on 2023-02-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0048_convert_qa_notes_to_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="enforcement_retest_document_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
