# Generated by Django 4.1.7 on 2023-04-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0050_case_updated_contact_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="contact_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
