# Generated by Django 4.1.7 on 2023-04-12 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0052_populate_case_contact_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="notes",
        ),
    ]
