# Generated by Django 4.1.7 on 2023-05-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0052_populate_case_contact_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="recommendation_for_enforcement",
            field=models.CharField(
                choices=[
                    ("no-further-action", "No further action"),
                    ("other", "For enforcement consideration"),
                    ("unknown", "Not selected"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
