# Generated by Django 4.1.7 on 2023-05-15 07:44

from django.db import migrations


def change_report_review_status_to_boolean(
    apps, schema_editor
):  # pylint: disable=unused-argument
    """Replace report review status choices with boolean yes/no"""
    # pylint: disable=invalid-name
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.all():
        if case.report_review_status in ["ready-to-review", "in-progress"]:
            case.report_review_status = "yes"
        else:
            case.report_review_status = "no"
        case.save()


def no_op(apps, schema_editor):  # pylint: disable=unused-argument
    """Cannot undo migration as data is destroyed"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0053_alter_case_recommendation_for_enforcement"),
    ]

    operations = [
        migrations.RunPython(change_report_review_status_to_boolean, reverse_code=no_op)
    ]
