# Generated by Django 4.1.7 on 2023-05-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0055_alter_case_report_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="is_feedback_requested",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="no", max_length=20
            ),
        ),
    ]
