# Generated by Django 4.1.7 on 2023-06-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0056_case_is_feedback_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="seven_day_no_contact_email_sent_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
