# Generated by Django 4.1.7 on 2023-05-26 12:58

from django.db import migrations


def populate_case_website_compliance_state_initial(
    apps, schema_editor
):  # pylint: disable=unused-argument
    """Populate website_compliance_state_initial in cases"""
    # pylint: disable=invalid-name
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.all():
        if (
            case.is_website_compliant == "other"
            or case.is_website_compliant == "unknown"
        ):
            case.website_compliance_state_initial = "not-known"
        elif case.is_website_compliant == "compliant":
            case.website_compliance_state_initial = "compliant"
        elif (
            case.is_website_compliant == "not-compliant"
            or case.is_website_compliant == "partially-compliant"
        ):
            case.website_compliance_state_initial = "partially-compliant"
        case.save()


def no_op(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0058_case_website_compliance_state_initial_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_case_website_compliance_state_initial, reverse_code=no_op
        )
    ]
