# Generated by Django 4.1.7 on 2023-05-26 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0059_populate_website_initial_compliance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="is_website_compliant",
        ),
    ]
