# Generated by Django 4.1.7 on 2023-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0060_remove_case_is_website_compliant"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="enforcement_body_finished_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
