# Generated by Django 4.1.10 on 2023-07-06 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0061_case_enforcement_body_finished_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="notes",
        ),
    ]
