# Generated by Django 4.2.4 on 2023-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0062_remove_contact_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="archive",
            field=models.TextField(blank=True, default=""),
        ),
    ]
