# Generated by Django 4.2.4 on 2023-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0063_set_statement_states"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="archive",
            field=models.TextField(blank=True, default=""),
        ),
    ]
