# Generated by Django 4.2.4 on 2023-10-02 14:05
import json

from django.db import migrations


def archive_old_fields(apps, schema_editor):  # pylint: disable=unused-argument
    User = apps.get_model("auth", "User")
    users = {user.id: user for user in User.objects.all()}
    Sector = apps.get_model("common", "Sector")
    sectors = {sector.id: sector for sector in Sector.objects.all()}
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.filter(testing_methodology="spreadsheet"):
        if case.auditor:
            auditor = users.get(case.auditor.id)
            auditor_display = f"{auditor.first_name} {auditor.last_name}"
        else:
            auditor = None
            auditor_display = None
        archive = [
            {
                "name": "Archived",
                "complete": None,
                "fields": [
                    {
                        "name": "testing_methodology",
                        "type": "str",
                        "label": "Testing methodology",
                        "value": case.testing_methodology,
                        "value_display": case.get_testing_methodology_display(),
                    },
                    {
                        "name": "report_methodology",
                        "type": "str",
                        "label": "Report methodology",
                        "value": case.report_methodology,
                        "value_display": case.get_report_methodology_display(),
                    },
                    {
                        "name": "test_results_url",
                        "type": "link",
                        "label": "Link to test results",
                        "value": case.test_results_url,
                        "value_display": case.test_results_url,
                    },
                    {
                        "name": "test_status",
                        "type": "str",
                        "label": "Test status",
                        "value": case.test_status,
                        "value_display": case.get_test_status_display(),
                    },
                    {
                        "name": "report_draft_url",
                        "type": "link",
                        "label": "Link to report draft",
                        "value": case.report_draft_url,
                        "value_display": "Report draft",
                    },
                    {
                        "name": "report_notes",
                        "type": "markdown",
                        "label": "Report notes",
                        "value": case.report_notes,
                        "value_display": None,
                    },
                    {
                        "name": "report_final_pdf_url",
                        "type": "link",
                        "label": "Link to test results",
                        "value": case.report_final_pdf_url,
                        "value_display": case.report_final_pdf_url,
                    },
                    {
                        "name": "report_final_odt_url",
                        "type": "link",
                        "label": "Link to test results",
                        "value": case.report_final_odt_url,
                        "value_display": case.report_final_odt_url,
                    },
                    {
                        "name": "notes",
                        "type": "markdown",
                        "label": "Notes",
                        "value": case.notes,
                        "value_display": None,
                    },
                ],
            },
            {
                "name": "Case details",
                "complete": case.case_details_complete_date.isoformat()
                if case.case_details_complete_date
                else None,
                "fields": [
                    {
                        "name": "created",
                        "type": "date",
                        "label": "Date created",
                        "value": case.created.isoformat(),
                        "value_display": f"{case.created:%-d %B %Y}",
                    },
                    {
                        "name": "status",
                        "type": "str",
                        "label": "Status",
                        "value": case.status,
                        "value_display": case.get_status_display(),
                    },
                    {
                        "name": "auditor",
                        "type": "str",
                        "label": "Auditor",
                        "value": case.auditor_id,
                        "value_display": auditor_display,
                    },
                    {
                        "name": "home_page_url",
                        "type": "link",
                        "label": "Full URL",
                        "value": case.home_page_url,
                        "value_display": case.home_page_url,
                    },
                    {
                        "name": "organisation_name",
                        "type": "str",
                        "label": "Organisation name",
                        "value": case.organisation_name,
                        "value_display": case.organisation_name,
                    },
                    {
                        "name": "enforcement_body",
                        "type": "str",
                        "label": "Which equalities body will check the case?",
                        "value": case.enforcement_body,
                        "value_display": case.get_enforcement_body_display(),
                    },
                    {
                        "name": "psb_location",
                        "type": "str",
                        "label": "Public sector body location",
                        "value": case.psb_location,
                        "value_display": case.get_psb_location_display(),
                    },
                    {
                        "name": "psb_location",
                        "type": "str",
                        "label": "Sector",
                        "value": case.sector_id,
                        "value_display": sectors.get(case.sector_id).name,
                    },
                    {
                        "name": "is_complaint",
                        "type": "str",
                        "label": "Complaint?",
                        "value": case.is_complaint,
                        "value_display": case.get_is_complaint_display(),
                    },
                    {
                        "name": "previous_case_url",
                        "type": "link",
                        "label": "URL to previous case",
                        "value": case.previous_case_url,
                        "value_display": case.previous_case_url,
                    },
                    {
                        "name": "trello_url",
                        "type": "link",
                        "label": "Trello ticket URL",
                        "value": case.trello_url,
                        "value_display": case.trello_url,
                    },
                ],
            },
        ]
        case.archive = json.dumps(archive)
        case.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.exclude(archive=""):
        case.archive = ""
        case.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0064_case_archive"),
    ]

    operations = [
        migrations.RunPython(archive_old_fields, reverse_code=reverse_code),
    ]
