# Generated by Django 4.2.4 on 2023-10-02 14:05
import json

from django.db import migrations


def archive_old_fields(apps, schema_editor):  # pylint: disable=unused-argument
    User = apps.get_model("auth", "User")
    users = {user.id: user for user in User.objects.all()}
    Sector = apps.get_model("common", "Sector")
    sectors = {sector.id: sector for sector in Sector.objects.all()}
    Case = apps.get_model("cases", "Case")
    Contact = apps.get_model("cases", "Contact")
    Comment = apps.get_model("comments", "Comment")
    for case in Case.objects.filter(testing_methodology="spreadsheet"):
        if case.auditor:
            auditor = users.get(case.auditor.id)
            auditor_display = f"{auditor.first_name} {auditor.last_name}"
        else:
            auditor = None
            auditor_display = None
        if case.reviewer:
            reviewer = users.get(case.reviewer.id)
            reviewer_display = f"{reviewer.first_name} {reviewer.last_name}"
        else:
            reviewer = None
            reviewer_display = None
        contacts = Contact.objects.filter(case=case)
        contact_fields = []
        for count, contact in enumerate(contacts, start=1):
            contact_fields.append(
                {
                    "name": f"contact_{count}_name",
                    "type": "str",
                    "label": f"Contact {count} Name",
                    "value": contact.name,
                    "value_display": contact.name,
                }
            )
            contact_fields.append(
                {
                    "name": f"contact_{count}_job_title",
                    "type": "str",
                    "label": f"Contact {count} Job title",
                    "value": contact.job_title,
                    "value_display": contact.job_title,
                }
            )
            contact_fields.append(
                {
                    "name": f"contact_{count}_email",
                    "type": "str",
                    "label": f"Contact {count} Email",
                    "value": contact.email,
                    "value_display": contact.email,
                }
            )
            if len(contacts) > 1:
                contact_fields.append(
                    {
                        "name": f"contact_{count}_preferred",
                        "type": "str",
                        "label": f"Contact {count} Preferred contact",
                        "value": contact.preferred,
                        "value_display": contact.get_preferred_display(),
                    }
                )
        comments = Comment.objects.filter(case=case)
        archive = [
            {
                "name": "Case details",
                "complete": case.case_details_complete_date.isoformat()
                if case.case_details_complete_date
                else None,
                "fields": [
                    {
                        "name": "created",
                        "type": "date",
                        "label": "Date created",
                        "value": case.created.isoformat(),
                        "value_display": f"{case.created:%-d %B %Y}",
                    },
                    {
                        "name": "status",
                        "type": "str",
                        "label": "Status",
                        "value": case.status,
                        "value_display": case.get_status_display(),
                    },
                    {
                        "name": "auditor",
                        "type": "str",
                        "label": "Auditor",
                        "value": case.auditor_id,
                        "value_display": auditor_display,
                    },
                    {
                        "name": "home_page_url",
                        "type": "link",
                        "label": "Full URL",
                        "value": case.home_page_url,
                        "value_display": case.home_page_url,
                    },
                    {
                        "name": "organisation_name",
                        "type": "str",
                        "label": "Organisation name",
                        "value": case.organisation_name,
                        "value_display": case.organisation_name,
                    },
                    {
                        "name": "enforcement_body",
                        "type": "str",
                        "label": "Which equalities body will check the case?",
                        "value": case.enforcement_body,
                        "value_display": case.get_enforcement_body_display(),
                    },
                    {
                        "name": "psb_location",
                        "type": "str",
                        "label": "Public sector body location",
                        "value": case.psb_location,
                        "value_display": case.get_psb_location_display(),
                    },
                    {
                        "name": "psb_location",
                        "type": "str",
                        "label": "Sector",
                        "value": case.sector_id,
                        "value_display": sectors.get(case.sector_id).name,
                    },
                    {
                        "name": "is_complaint",
                        "type": "str",
                        "label": "Complaint?",
                        "value": case.is_complaint,
                        "value_display": case.get_is_complaint_display(),
                    },
                    {
                        "name": "previous_case_url",
                        "type": "link",
                        "label": "URL to previous case",
                        "value": case.previous_case_url,
                        "value_display": case.previous_case_url,
                    },
                    {
                        "name": "trello_url",
                        "type": "link",
                        "label": "Trello ticket URL",
                        "value": case.trello_url,
                        "value_display": case.trello_url,
                    },
                ],
            },
            {
                "name": "Testing details",
                "complete": case.testing_details_complete_date.isoformat()
                if case.testing_details_complete_date
                else None,
                "fields": [
                    {
                        "name": "test_results_url",
                        "type": "link",
                        "label": "Link to test results",
                        "value": case.test_results_url,
                        "value_display": "Monitor document",
                    },
                    {
                        "name": "test_status",
                        "type": "str",
                        "label": "Test status",
                        "value": case.test_status,
                        "value_display": case.get_test_status_display(),
                    },
                    {
                        "name": "accessibility_statement_state",
                        "type": "str",
                        "label": "Initial accessibility statement decision",
                        "value": case.accessibility_statement_state,
                        "value_display": case.get_accessibility_statement_state_display(),
                    },
                    {
                        "name": "accessibility_statement_notes",
                        "type": "markdown",
                        "label": "Accessibility statement notes",
                        "value": case.accessibility_statement_notes,
                        "value_display": None,
                    },
                    {
                        "name": "website_compliance_state_initial",
                        "type": "str",
                        "label": "Initial compliance decision",
                        "value": case.website_compliance_state_initial,
                        "value_display": case.get_website_compliance_state_initial_display(),
                    },
                    {
                        "name": "compliance_decision_notes",
                        "type": "markdown",
                        "label": "Initial website compliance notes",
                        "value": case.compliance_decision_notes,
                        "value_display": None,
                    },
                ],
            },
            {
                "name": "Report details",
                "complete": case.reporting_details_complete_date.isoformat()
                if case.reporting_details_complete_date
                else None,
                "fields": [
                    {
                        "name": "report_draft_url",
                        "type": "link",
                        "label": "Link to report draft",
                        "value": case.report_draft_url,
                        "value_display": "Report draft",
                    },
                    {
                        "name": "report_notes",
                        "type": "markdown",
                        "label": "Report details notes",
                        "value": case.report_notes,
                        "value_display": None,
                    },
                ],
            },
            {
                "name": "QA process",
                "complete": case.qa_process_complete_date.isoformat()
                if case.qa_process_complete_date
                else None,
                "fields": [
                    {
                        "name": "report_review_status",
                        "type": "str",
                        "label": "Report ready to be reviewed",
                        "value": case.report_review_status,
                        "value_display": case.get_report_review_status_display(),
                    },
                    {
                        "name": "reviewer",
                        "type": "str",
                        "label": "QA auditor",
                        "value": case.reviewer_id,
                        "value_display": reviewer_display,
                    },
                    {
                        "name": "qa_comments",
                        "type": "str",
                        "label": "Comments",
                        "value": comments.count(),
                        "value_display": comments.count(),
                    },
                    {
                        "name": "report_approved_status",
                        "type": "str",
                        "label": "Report approved?",
                        "value": case.report_approved_status,
                        "value_display": case.get_report_approved_status_display(),
                    },
                    {
                        "name": "report_final_odt_url",
                        "type": "link",
                        "label": "Link to final ODT report",
                        "value": case.report_final_odt_url,
                        "value_display": "Final draft (ODT)",
                    },
                    {
                        "name": "report_final_pdf_url",
                        "type": "link",
                        "label": "Link to final PDF report",
                        "value": case.report_final_pdf_url,
                        "value_display": "Final draft (PDF)",
                    },
                ],
            },
            {
                "name": "Contact details",
                "complete": case.contact_details_complete_date.isoformat()
                if case.contact_details_complete_date
                else None,
                "fields": [
                    {
                        "name": "contact_notes",
                        "type": "markdown",
                        "label": "Contact details notes",
                        "value": case.contact_notes,
                        "value_display": None,
                    },
                ]
                + contact_fields,
            },
            {
                "name": "Archived",
                "complete": None,
                "fields": [
                    {
                        "name": "testing_methodology",
                        "type": "str",
                        "label": "Testing methodology",
                        "value": case.testing_methodology,
                        "value_display": case.get_testing_methodology_display(),
                    },
                    {
                        "name": "report_methodology",
                        "type": "str",
                        "label": "Report methodology",
                        "value": case.report_methodology,
                        "value_display": case.get_report_methodology_display(),
                    },
                    {
                        "name": "notes",
                        "type": "markdown",
                        "label": "Notes",
                        "value": case.notes,
                        "value_display": None,
                    },
                ],
            },
        ]
        case.archive = json.dumps(archive)
        case.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.exclude(archive=""):
        case.archive = ""
        case.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0064_case_archive"),
    ]

    operations = [
        migrations.RunPython(archive_old_fields, reverse_code=reverse_code),
    ]
