# Generated by Django 4.2.4 on 2023-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0065_archive_non_platform_tested"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="test_status",
        ),
        migrations.RemoveField(
            model_name="case",
            name="testing_methodology",
        ),
        migrations.AlterField(
            model_name="case",
            name="report_methodology",
            field=models.CharField(
                choices=[("platform", "Platform"), ("odt", "ODT templates")],
                default="platform",
                max_length=20,
            ),
        ),
    ]
