# Generated by Django 4.2.4 on 2023-10-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0066_remove_case_test_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="enforcement_body_case_owner",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="enforcement_body_closed_case",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No (or don't know)")],
                default="no",
                max_length=20,
            ),
        ),
    ]
