# Generated by Django 4.2.4 on 2023-10-13 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0067_archive_non_platform_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="report_methodology",
        ),
    ]
