# Generated by Django 4.2.4 on 2023-10-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0068_populate_enforcement_body_closed_case"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="created_by",
        ),
        migrations.CreateModel(
            name="EqualityBodyCorrespondence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_within_case", models.IntegerField(blank=True, default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("request-retest", "Retest request"),
                        ],
                        default="question",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("zendesk_url", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outstanding", "Unresolved"),
                            ("resolved", "Resolved"),
                        ],
                        default="outstanding",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cases.case"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
