# Generated by Django 4.2.4 on 2023-10-26 07:16

from django.db import migrations


def populate_enforcement_body_closed_case(
    apps, schema_editor
):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.all():
        if case.enforcement_body_pursuing in ["no", "yes-completed"]:
            case.enforcement_body_closed_case = "yes"
        else:
            case.enforcement_body_closed_case = "no"
        case.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0069_remove_contact_created_by_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_enforcement_body_closed_case, reverse_code=reverse_code
        ),
    ]
