# Generated by Django 4.2.4 on 2023-10-25 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0070_populate_new_compliance_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="accessibility_statement_notes",
        ),
        migrations.RemoveField(
            model_name="case",
            name="accessibility_statement_notes_final",
        ),
        migrations.RemoveField(
            model_name="case",
            name="accessibility_statement_state",
        ),
        migrations.RemoveField(
            model_name="case",
            name="accessibility_statement_state_final",
        ),
        migrations.RemoveField(
            model_name="case",
            name="compliance_decision_notes",
        ),
        migrations.RemoveField(
            model_name="case",
            name="website_compliance_state_initial",
        ),
        migrations.RemoveField(
            model_name="case",
            name="website_state_final",
        ),
        migrations.RemoveField(
            model_name="case",
            name="website_state_notes_final",
        ),
    ]
