# Generated by Django 4.2.4 on 2023-11-01 15:05

from django.db import migrations


def populate_enforcement_body_closed_case(
    apps, schema_editor
):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    Audit = apps.get_model("audits", "Audit")
    StatementCheckResult = apps.get_model("audits", "StatementCheckResult")
    Report = apps.get_model("reports", "Report")
    for case in Case.objects.all():
        if case.enforcement_body_pursuing in ["no", "yes-completed"]:
            case.enforcement_body_closed_case = "yes"
        else:
            case.enforcement_body_closed_case = "no"

        if Audit.objects.filter(case=case).count() == 0:
            case.variant = "archived"
        else:
            audit = Audit.objects.get(case=case)
            if StatementCheckResult.objects.filter(audit=audit).count() > 0:
                case.variant = "statement-content"
            elif Report.objects.filter(case=case).count() > 0:
                case.variant = "reporting"
            else:
                case.variant = "archived"

        case.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0073_remove_contact_created_by_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_enforcement_body_closed_case, reverse_code=reverse_code
        ),
    ]
