# Generated by Django 4.2.4 on 2023-11-22 11:10

from django.db import migrations


def populate_case_status(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    CaseStatus = apps.get_model("cases", "CaseStatus")
    for case in Case.objects.all():
        CaseStatus.objects.create(case=case, status=case.status)


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    CaseStatus = apps.get_model("cases", "CaseStatus")
    CaseStatus.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0075_casestatus"),
    ]

    operations = [
        migrations.RunPython(populate_case_status, reverse_code=reverse_code),
    ]
