# Generated by Django 4.2.4 on 2023-11-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0076_populate_case_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="status",
        ),
        migrations.AlterField(
            model_name="casestatus",
            name="case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status",
                to="cases.case",
            ),
        ),
    ]
