# Generated by Django 4.2.8 on 2023-12-11 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0077_remove_case_status_alter_casestatus_case"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casestatus",
            options={"verbose_name_plural": "Case statuses"},
        ),
    ]
