# Generated by Django 4.2.8 on 2024-01-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0078_alter_casestatus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("unassigned-case", "Unassigned case"),
                    ("test-in-progress", "Test in progress"),
                    ("report-in-progress", "Report in progress"),
                    ("unassigned-qa-case", "Report ready to QA"),
                    ("qa-in-progress", "QA in progress"),
                    ("report-ready-to-send", "Report ready to send"),
                    ("in-report-correspondence", "Report sent"),
                    (
                        "in-probation-period",
                        "Report acknowledged waiting for 12-week deadline",
                    ),
                    ("in-12-week-correspondence", "After 12-week correspondence"),
                    ("reviewing-changes", "Reviewing changes"),
                    ("final-decision-due", "Final decision due"),
                    (
                        "case-closed-waiting-to-be-sent",
                        "Case closed and waiting to be sent to equalities body",
                    ),
                    (
                        "case-closed-sent-to-equalities-body",
                        "Case closed and sent to equalities body",
                    ),
                    (
                        "in-correspondence-with-equalities-body",
                        "In correspondence with equalities body",
                    ),
                    ("complete", "Complete"),
                    ("deactivated", "Deactivated"),
                ],
                default="unassigned-case",
                max_length=200,
            ),
        ),
    ]
