# Generated by Django 4.2.8 on 2023-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0078_alter_casestatus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="compliance_decision_sent_to_email",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="contact_details_found",
            field=models.CharField(
                choices=[
                    ("found", "Contact details found"),
                    ("not-found", "No contact details found"),
                    ("not-checked", "Not checked"),
                ],
                default="not-checked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="cores_overview_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="find_contact_details_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="four_week_followup_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="four_week_followup_sent_to_email",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="one_week_followup_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="one_week_followup_final_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="one_week_followup_sent_to_email",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="organisation_response",
            field=models.CharField(
                choices=[
                    ("no-response", "Organisation did not respond to 12-week update"),
                    (
                        "not-applicable",
                        "Not applicable or organisation responded to 12-week update",
                    ),
                ],
                default="not-applicable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="report_acknowledged_by_email",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="report_acknowledged_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="report_sent_on_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="report_sent_to_email",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="twelve_week_1_week_chaser_sent_to_email",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="twelve_week_correspondence_acknowledged_by_email",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="twelve_week_update_request_ack_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="twelve_week_update_request_sent_to_email",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="case",
            name="twelve_week_update_requested_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
