# Generated by Django 4.2.8 on 2024-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0081_alter_casestatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="equality_body_case_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
