# Generated by Django 4.2.8 on 2024-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0082_case_equality_body_case_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="qa_approved_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="qa_auditor_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="report_ready_for_qa_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
