# Generated by Django 4.2.8 on 2024-01-30 14:55

from django.db import migrations


def migrate_statement_compliance(
    apps, schema_editor
):  # pylint: disable=unused-argument
    """ "
        unknown -> Not assessed
        Other -> Not compliant
        Not-compliant -> Not-compliant
        Not-found -> Not compliant
        Compliant -> Compliant

    class StatementCompliance(models.TextChoices):
        COMPLIANT = "compliant", "Compliant"
        NOT_COMPLIANT = "not-compliant", "Not compliant"
        NOT_FOUND = "not-found", "Not found"
        OTHER = "other", "Other"
        UNKNOWN = "unknown", "Not assessed"
    """
    CaseCompliance = apps.get_model("cases", "CaseCompliance")
    for case_compliance in CaseCompliance.objects.all():
        if case_compliance.statement_compliance_state_initial in [
            "compliant",
            "not-compliant",
            "unknown",
        ] and case_compliance.statement_compliance_state_12_week in [
            "compliant",
            "not-compliant",
            "unknown",
        ]:
            continue

        if (
            case_compliance.statement_compliance_state_initial == "not-found"
            or case_compliance.statement_compliance_state_initial == "other"
        ):
            case_compliance.statement_compliance_state_initial = "not-compliant"

        if (
            case_compliance.statement_compliance_state_12_week == "not-found"
            or case_compliance.statement_compliance_state_12_week == "other"
        ):
            case_compliance.statement_compliance_state_12_week = "not-compliant"
        case_compliance.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0083_case_qa_approved_complete_date_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_statement_compliance, reverse_code=reverse_code),
    ]
