# Generated by Django 4.2.8 on 2024-01-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0084_migrate_statement_compliance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casecompliance",
            name="statement_compliance_state_12_week",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="casecompliance",
            name="statement_compliance_state_initial",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
    ]
