# Generated by Django 4.2.8 on 2024-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "cases",
            "0085_alter_casecompliance_statement_compliance_state_12_week_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="enforcement_recommendation_complete_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
