# Generated by Django 4.2.8 on 2024-02-20 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "cases",
            "0085_alter_casecompliance_statement_compliance_state_12_week_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="qa_approved_complete_date",
        ),
        migrations.RemoveField(
            model_name="case",
            name="report_ready_for_qa_complete_date",
        ),
    ]
