# Generated by Django 4.2.8 on 2024-02-20 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0086_case_enforcement_recommendation_complete_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="qa_approved_complete_date",
        ),
        migrations.RemoveField(
            model_name="case",
            name="report_ready_for_qa_complete_date",
        ),
    ]
