# Generated by Django 4.2.10 on 2024-03-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0087_remove_case_qa_approved_complete_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="equality_body_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
