# Generated by Django 5.0.3 on 2024-03-25 16:19

from django.db import migrations


def migrate_zendesk_urls(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    ZendeskTicket = apps.get_model("cases", "ZendeskTicket")
    for case in Case.objects.filter(
        variant__in=["statement-content", "close-case"]
    ).exclude(zendesk_url=""):
        print(f"{case}: {case.variant}, {case.zendesk_url}")
        ZendeskTicket.objects.create(
            case=case, url=case.zendesk_url, summary="Migrated URL"
        )


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    ZendeskTicket = apps.get_model("cases", "ZendeskTicket")
    ZendeskTicket.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0089_zendeskticket"),
    ]

    operations = [
        migrations.RunPython(migrate_zendesk_urls, reverse_code=reverse_code),
    ]
