# Generated by Django 5.0.4 on 2024-04-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0090_migrate_zendesk_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casecompliance",
            name="statement_compliance_state_12_week",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant or no statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="casecompliance",
            name="statement_compliance_state_initial",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("not-compliant", "Not compliant or no statement"),
                    ("unknown", "Not assessed"),
                ],
                default="unknown",
                max_length=200,
            ),
        ),
    ]
