# Generated by Django 5.0.4 on 2024-04-16 13:16

from django.db import migrations


def populate_case_numbers(apps, schema_editor):  # pylint: disable=unused-argument
    Case = apps.get_model("cases", "Case")
    for case in Case.objects.all():
        case.case_number = case.id
        case.save()


def reverse_code(apps, schema_editor):  # pylint: disable=unused-argument
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0091_case_case_number_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_case_numbers, reverse_code=reverse_code),
    ]
