"""
URLS for cases
"""

from django.contrib.auth.decorators import login_required
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import (
    CaseCloseUpdateView,
    CaseCreateReportUpdateView,
    CaseCreateView,
    CaseDeactivateUpdateView,
    CaseDetailView,
    CaseEmailTemplateListView,
    CaseEmailTemplatePreviewDetailView,
    CaseEnforcementRecommendationUpdateView,
    CaseEqualityBodyCorrespondenceUpdateView,
    CaseEqualityBodyMetadataUpdateView,
    CaseFourWeekContactDetailsUpdateView,
    CaseHistoryDetailView,
    CaseMetadataUpdateView,
    CaseNoPSBResponseUpdateView,
    CaseOneWeekContactDetailsUpdateView,
    CaseOneWeekFollowup12WeekUpdateView,
    CaseOutstandingIssuesDetailView,
    CasePublishReportUpdateView,
    CaseQAApprovalUpdateView,
    CaseQAAuditorUpdateView,
    CaseQACommentsUpdateView,
    CaseReactivateUpdateView,
    CaseReportAcknowledgedUpdateView,
    CaseReportFourWeekFollowupUpdateView,
    CaseReportOneWeekFollowupUpdateView,
    CaseReportReadyForQAUpdateView,
    CaseReportSentOnUpdateView,
    CaseRequestContactDetailsUpdateView,
    CaseRetestCreateErrorTemplateView,
    CaseRetestOverviewTemplateView,
    CaseReviewChangesUpdateView,
    CaseSearchView,
    CaseStatementEnforcementUpdateView,
    CaseStatusWorkflowDetailView,
    CaseTestResultsUpdateView,
    CaseTwelveWeekRetestUpdateView,
    CaseTwelveWeekUpdateAcknowledgedUpdateView,
    CaseTwelveWeekUpdateRequestedUpdateView,
    CaseZendeskTicketsDetailView,
    ContactCreateView,
    ContactUpdateView,
    EqualityBodyCorrespondenceCreateView,
    ListCaseEqualityBodyCorrespondenceUpdateView,
    ManageContactDetailsUpdateView,
    ZendeskTicketConfirmDeleteUpdateView,
    ZendeskTicketCreateView,
    ZendeskTicketUpdateView,
    enable_correspondence_process,
    export_cases,
    export_feedback_survey_cases,
    mark_qa_comments_as_read,
)

app_name: str = "simplified"
urlpatterns: list[URLPattern] = [
    path(
        "export-feedback-survey-cases-csv/",
        login_required(export_feedback_survey_cases),
        name="export-feedback-survey-cases",
    ),
    path("export-as-csv/", login_required(export_cases), name="case-export-list"),
    path("create/", login_required(CaseCreateView.as_view()), name="case-create"),
    path(
        "<int:pk>/view/", login_required(CaseDetailView.as_view()), name="case-detail"
    ),
    path(
        "<int:pk>/case-view-and-search/",
        login_required(CaseSearchView.as_view()),
        name="case-view-and-search",
    ),
    path(
        "<int:pk>/edit-case-metadata/",
        login_required(CaseMetadataUpdateView.as_view()),
        name="edit-case-metadata",
    ),
    path(
        "<int:pk>/edit-test-results/",
        login_required(CaseTestResultsUpdateView.as_view()),
        name="edit-test-results",
    ),
    path(
        "<int:pk>/edit-create-report/",
        login_required(CaseCreateReportUpdateView.as_view()),
        name="edit-create-report",
    ),
    path(
        "<int:pk>/edit-report-ready-for-qa/",
        login_required(CaseReportReadyForQAUpdateView.as_view()),
        name="edit-report-ready-for-qa",
    ),
    path(
        "<int:pk>/edit-qa-auditor/",
        login_required(CaseQAAuditorUpdateView.as_view()),
        name="edit-qa-auditor",
    ),
    path(
        "<int:pk>/edit-qa-comments/",
        login_required(CaseQACommentsUpdateView.as_view()),
        name="edit-qa-comments",
    ),
    path(
        "<int:pk>/mark-qa-comments-as-read/",
        login_required(mark_qa_comments_as_read),
        name="mark-qa-comments-as-read",
    ),
    path(
        "<int:pk>/edit-qa-approval/",
        login_required(CaseQAApprovalUpdateView.as_view()),
        name="edit-qa-approval",
    ),
    path(
        "<int:pk>/edit-publish-report/",
        login_required(CasePublishReportUpdateView.as_view()),
        name="edit-publish-report",
    ),
    path(
        "<int:pk>/manage-contact-details/",
        login_required(ManageContactDetailsUpdateView.as_view()),
        name="manage-contact-details",
    ),
    path(
        "<int:case_id>/edit-contact-create/",
        login_required(ContactCreateView.as_view()),
        name="edit-contact-create",
    ),
    path(
        "contacts/<int:pk>/edit-contact-update/",
        login_required(ContactUpdateView.as_view()),
        name="edit-contact-update",
    ),
    path(
        "<int:pk>/enable-correspondence-process/",
        login_required(enable_correspondence_process),
        name="enable-correspondence-process",
    ),
    path(
        "<int:pk>/edit-request-contact-details/",
        login_required(CaseRequestContactDetailsUpdateView.as_view()),
        name="edit-request-contact-details",
    ),
    path(
        "<int:pk>/edit-one-week-contact-details/",
        login_required(CaseOneWeekContactDetailsUpdateView.as_view()),
        name="edit-one-week-contact-details",
    ),
    path(
        "<int:pk>/edit-four-week-contact-details/",
        login_required(CaseFourWeekContactDetailsUpdateView.as_view()),
        name="edit-four-week-contact-details",
    ),
    path(
        "<int:pk>/edit-no-psb-response/",
        login_required(CaseNoPSBResponseUpdateView.as_view()),
        name="edit-no-psb-response",
    ),
    path(
        "<int:pk>/edit-report-sent-on/",
        login_required(CaseReportSentOnUpdateView.as_view()),
        name="edit-report-sent-on",
    ),
    path(
        "<int:pk>/edit-report-one-week-followup/",
        login_required(CaseReportOneWeekFollowupUpdateView.as_view()),
        name="edit-report-one-week-followup",
    ),
    path(
        "<int:pk>/edit-report-four-week-followup/",
        login_required(CaseReportFourWeekFollowupUpdateView.as_view()),
        name="edit-report-four-week-followup",
    ),
    path(
        "<int:pk>/edit-report-acknowledged/",
        login_required(CaseReportAcknowledgedUpdateView.as_view()),
        name="edit-report-acknowledged",
    ),
    path(
        "<int:pk>/edit-12-week-update-requested/",
        login_required(CaseTwelveWeekUpdateRequestedUpdateView.as_view()),
        name="edit-12-week-update-requested",
    ),
    path(
        "<int:pk>/edit-12-week-one-week-followup-final/",
        login_required(CaseOneWeekFollowup12WeekUpdateView.as_view()),
        name="edit-12-week-one-week-followup-final",
    ),
    path(
        "<int:pk>/edit-12-week-update-request-ack/",
        login_required(CaseTwelveWeekUpdateAcknowledgedUpdateView.as_view()),
        name="edit-12-week-update-request-ack",
    ),
    path(
        "<int:pk>/edit-twelve-week-retest/",
        login_required(CaseTwelveWeekRetestUpdateView.as_view()),
        name="edit-twelve-week-retest",
    ),
    path(
        "<int:pk>/edit-review-changes/",
        login_required(CaseReviewChangesUpdateView.as_view()),
        name="edit-review-changes",
    ),
    path(
        "<int:pk>/edit-enforcement-recommendation/",
        login_required(CaseEnforcementRecommendationUpdateView.as_view()),
        name="edit-enforcement-recommendation",
    ),
    path(
        "<int:pk>/edit-case-close/",
        login_required(CaseCloseUpdateView.as_view()),
        name="edit-case-close",
    ),
    path(
        "<int:pk>/deactivate-case/",
        login_required(CaseDeactivateUpdateView.as_view()),
        name="deactivate-case",
    ),
    path(
        "<int:pk>/reactivate-case/",
        login_required(CaseReactivateUpdateView.as_view()),
        name="reactivate-case",
    ),
    path(
        "<int:pk>/status-workflow/",
        login_required(CaseStatusWorkflowDetailView.as_view()),
        name="status-workflow",
    ),
    path(
        "<int:pk>/outstanding-issues/",
        login_required(CaseOutstandingIssuesDetailView.as_view()),
        name="outstanding-issues",
    ),
    path(
        "<int:pk>/statement-enforcement/",
        login_required(CaseStatementEnforcementUpdateView.as_view()),
        name="edit-statement-enforcement",
    ),
    path(
        "<int:pk>/equality-body-metadata/",
        login_required(CaseEqualityBodyMetadataUpdateView.as_view()),
        name="edit-equality-body-metadata",
    ),
    path(
        "<int:pk>/list-equality-body-correspondence/",
        login_required(ListCaseEqualityBodyCorrespondenceUpdateView.as_view()),
        name="list-equality-body-correspondence",
    ),
    path(
        "<int:case_id>/create-equality-body-correspondence/",
        login_required(EqualityBodyCorrespondenceCreateView.as_view()),
        name="create-equality-body-correspondence",
    ),
    path(
        "<int:pk>/edit-equality-body-correspondence/",
        login_required(CaseEqualityBodyCorrespondenceUpdateView.as_view()),
        name="edit-equality-body-correspondence",
    ),
    path(
        "<int:pk>/retest-overview/",
        login_required(CaseRetestOverviewTemplateView.as_view()),
        name="edit-retest-overview",
    ),
    path(
        "<int:pk>/retest-create-error/",
        login_required(CaseRetestCreateErrorTemplateView.as_view()),
        name="retest-create-error",
    ),
    path(
        "<int:pk>/zendesk-tickets/",
        login_required(CaseZendeskTicketsDetailView.as_view()),
        name="zendesk-tickets",
    ),
    path(
        "<int:case_id>/create-zendesk-ticket/",
        login_required(ZendeskTicketCreateView.as_view()),
        name="create-zendesk-ticket",
    ),
    path(
        "<int:pk>/update-zendesk-ticket/",
        login_required(ZendeskTicketUpdateView.as_view()),
        name="update-zendesk-ticket",
    ),
    path(
        "<int:pk>/confirm-delete-zendesk-ticket/",
        login_required(ZendeskTicketConfirmDeleteUpdateView.as_view()),
        name="confirm-delete-zendesk-ticket",
    ),
    path(
        "<int:case_id>/email-template-list/",
        login_required(CaseEmailTemplateListView.as_view()),
        name="email-template-list",
    ),
    path(
        "<int:case_id>/<int:pk>/email-template-preview/",
        login_required(CaseEmailTemplatePreviewDetailView.as_view()),
        name="email-template-preview",
    ),
    path(
        "<int:pk>/history/",
        login_required(CaseHistoryDetailView.as_view()),
        name="case-history",
    ),
]
