# Generated by Django 5.2.1 on 2025-06-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplified", "0001_initial"),
        ("exports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportcase",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="exportcase",
            name="simplified_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="simplified.simplifiedcase",
            ),
        ),
    ]
