# Generated by Django 5.2.1 on 2025-06-04 13:34

from django.db import migrations


def populate_base_case(apps, schema_editor):
    SimplifiedCase = apps.get_model("simplified", "SimplifiedCase")
    ExportCase = apps.get_model("exports", "ExportCase")
    for count, simplified_case in enumerate(
        SimplifiedCase.objects.all().order_by("id"), start=1
    ):
        print(
            f"{count}: Migrating ExportCase Case number {simplified_case.case_number}"
        )
        for export_case in ExportCase.objects.filter(case_id=simplified_case.case_id):
            export_case.simplified_case_id = simplified_case.id
            export_case.save()


def reverse_code(apps, schema_editor):
    ExportCase = apps.get_model("exports", "ExportCase")
    ExportCase.objects.all().update(simplified_case_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0002_exportcase_simplified_case"),
        ("simplified", "0003_populate_simplified_cases"),
    ]

    operations = [
        migrations.RunPython(populate_base_case, reverse_code=reverse_code),
    ]
