# Generated by Django 5.2.6 on 2025-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0004_remove_exportcase_case"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="enforcement_body",
            field=models.CharField(
                choices=[
                    ("ehrc", "Equality and Human Rights Commission"),
                    ("ecni", "Equality Commission for Northern Ireland"),
                ],
                default="ehrc",
                max_length=20,
            ),
        ),
    ]
