name: Deploy to AWS
on:
  push:
    branches:
      - aws-migration
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Install AWS Copilot
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        # download copilot
        curl -Lo copilot-linux https://github.com/aws/copilot-cli/releases/download/v1.8.3/copilot-linux && \
        # make copilot bin executable
        chmod +x copilot-linux && \
        # move to path
        mv copilot-linux $GITHUB_WORKSPACE/bin/copilot && \
        # add to PATH
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        copilot app ls

    - name: Deploy to AWS
      run: |
        copilot app init amp-app-2
        copilot svc deploy --name viewer-svc --env test-env
        copilot svc deploy --name amp-svc --env test-env
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_COPILOT }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_COPILOT }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION_COPILOT }}
