name: Test
on: push
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          python manage.py collectstatic
          export DEBUG=TRUE
          export ALLOWED_HOSTS='localhost 127.0.0.1 0.0.0.0'
          export SECRET_KEY=1234
          export VCAP_SERVICES="{'postgres':[{'credentials': { 'uri': 'postgres://admin:secret@localhost:5432/accessibility_monitoring_app' }},{'credentials': { 'uri': 'postgres://admin:secret@localhost:5432/domain_register' }}]}"
          python3 manage.py test
        env:
          DEBUG: TRUE
          SECRET_KEY: 1234
          ALLOWED_HOSTS: 'localhost 127.0.0.1 0.0.0.0'
          EMAIL_BACKEND: default