name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read Ubuntu version
      run: echo ::set-output name=UBUNTU_VERSION::$(lsb_release -r -s)
      id: ubuntu-version

    - name: Setup python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        node-version: 14.x

    - name: Install python dependencies
      run: |
        pip install pipenv
        pipenv install -d
      if: steps.python-cache.outputs.cache-hit != 'true'

    - name: Run python tests
      run: coverage run --source='.' manage.py test