name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pipenv
          pipenv install -d
          export DEBUG=TRUE
          export ALLOWED_HOSTS='localhost 127.0.0.1 0.0.0.0'
          coverage run --source='.' manage.py test
        env:
          DEBUG: TRUE
          SECRET_KEY: 1234
          ALLOWED_HOSTS: 'localhost 127.0.0.1 0.0.0.0'
          EMAIL_BACKEND: default