name: Test
on: pull_request
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: Smoke tests
      run: |
        cd stack_tests/smoke_tests
        docker-compose up --abort-on-container-exit
      env:
        SMOKE_TESTS_USERNAME: ${{ secrets.SMOKE_TESTS_USERNAME }}
        SMOKE_TESTS_PASSWORD: ${{ secrets.SMOKE_TESTS_PASSWORD }}


  int-test:
    needs: test
    name: Integration tests
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Integration tests
      run: |
        cd stack_tests/integration_tests
        docker-compose up --abort-on-container-exit
      env:
        AWS_ACCESS_KEY_ID_S3_STORE: ${{ secrets.AWS_ACCESS_KEY_ID_S3_STORE }}
        AWS_SECRET_ACCESS_KEY_S3_STORE: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3_STORE }}
        AWS_DEFAULT_REGION_S3_STORE: ${{ secrets.AWS_DEFAULT_REGION_S3_STORE }}
