name: Test
on: pull_request
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Unit tests
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements_for_test.txt
        export DEBUG=TRUE
        export SECRET_KEY=12345678
        export ALLOWED_HOSTS='localhost 127.0.0.1'
        export TERRAFORM=TRUE
        export DB_HOST=localhost
        export DB_NAME=accessibility_monitoring_app
        export DB_USER=admin
        export BUCKET_NAME=amp-dummy-s3-bucket
        export DB_PASSWORD='{"username": "admin", "password": "secret"}'
        export AMP_PROTOCOL='http://'
        export AMP_VIEWER_DOMAIN='127.0.0.1:8082'
        npm i
        make static_files_process
        make test

  int-test:
    needs: test
    name: Integration tests
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Integration tests
      run: |
        docker compose --file stack_tests/integration_tests/docker-compose.yml up --abort-on-container-exit
