name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Read Ubuntu version
      run: echo ::set-output name=UBUNTU_VERSION::$(lsb_release -r -s)
      id: ubuntu-version

    - name: Install python dependencies
      uses: actions/setup-python@v2
      run: |
        pip install pipenv
        pipenv install -d
      if: steps.python-cache.outputs.cache-hit != 'true'

    - name: Run python tests
      uses: actions/setup-python@v2
      run: coverage run --source='.' manage.py test